using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.AzureAD;

/// <summary>
/// Manages a azuread_service_principal_password resource.
/// </summary>
public class AzureadServicePrincipalPassword : TerraformResource
{
    public AzureadServicePrincipalPassword(string name) : base("azuread_service_principal_password", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("key_id");
        this.DeclareOutput("value");
    }

    /// <summary>
    /// A display name for the password
    /// </summary>
    public TerraformLiteralProperty<string>? DisplayName
    {
        get => GetProperty<TerraformLiteralProperty<string>>("display_name");
        set => this.WithProperty("display_name", value);
    }

    /// <summary>
    /// The end date until which the password is valid, formatted as an RFC3339 date string (e.g. `2018-01-01T01:02:03Z`)
    /// </summary>
    public TerraformLiteralProperty<string>? EndDate
    {
        get => GetProperty<TerraformLiteralProperty<string>>("end_date");
        set => this.WithProperty("end_date", value);
    }

    /// <summary>
    /// A relative duration for which the password is valid until, for example `240h` (10 days) or `2400h30m`. Changing this field forces a new resource to be created
    /// </summary>
    [Obsolete("This property is deprecated.")]
    public TerraformLiteralProperty<string>? EndDateRelative
    {
        get => GetProperty<TerraformLiteralProperty<string>>("end_date_relative");
        set => this.WithProperty("end_date_relative", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? Id
    {
        get => GetProperty<TerraformLiteralProperty<string>>("id");
        set => this.WithProperty("id", value);
    }

    /// <summary>
    /// Arbitrary map of values that, when changed, will trigger rotation of the password
    /// </summary>
    public TerraformLiteralProperty<Dictionary<string, string>>? RotateWhenChanged
    {
        get => GetProperty<TerraformLiteralProperty<Dictionary<string, string>>>("rotate_when_changed");
        set => this.WithProperty("rotate_when_changed", value);
    }

    /// <summary>
    /// The ID of the service principal for which this password should be created
    /// </summary>
    public TerraformLiteralProperty<string>? ServicePrincipalId
    {
        get => GetProperty<TerraformLiteralProperty<string>>("service_principal_id");
        set => this.WithProperty("service_principal_id", value);
    }

    /// <summary>
    /// The start date from which the password is valid, formatted as an RFC3339 date string (e.g. `2018-01-01T01:02:03Z`). If this isn&#39;t specified, the current date is used
    /// </summary>
    public TerraformLiteralProperty<string>? StartDate
    {
        get => GetProperty<TerraformLiteralProperty<string>>("start_date");
        set => this.WithProperty("start_date", value);
    }

    /// <summary>
    /// A UUID used to uniquely identify this password credential
    /// </summary>
    public TerraformExpression KeyId => this["key_id"];

    /// <summary>
    /// The password for this service principal, which is generated by Azure Active Directory
    /// </summary>
    public TerraformExpression Value => this["value"];

}
