using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.AzureRM;

/// <summary>
/// Block type for service_location in .
/// Nesting mode: set
/// </summary>
public class AzurermVoiceServicesCommunicationsGatewayServiceLocationBlock
{
    /// <summary>
    /// The allowed_media_source_address_prefixes attribute.
    /// </summary>
    [TerraformPropertyName("allowed_media_source_address_prefixes")]
    // Optional argument - user may or may not set a value
    public TerraformSet<string>? AllowedMediaSourceAddressPrefixes { get; set; }

    /// <summary>
    /// The allowed_signaling_source_address_prefixes attribute.
    /// </summary>
    [TerraformPropertyName("allowed_signaling_source_address_prefixes")]
    // Optional argument - user may or may not set a value
    public TerraformSet<string>? AllowedSignalingSourceAddressPrefixes { get; set; }

    /// <summary>
    /// The esrp_addresses attribute.
    /// </summary>
    [TerraformPropertyName("esrp_addresses")]
    // Optional argument - user may or may not set a value
    public TerraformSet<string>? EsrpAddresses { get; set; }

    /// <summary>
    /// The location attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Location is required")]
    [TerraformPropertyName("location")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> Location { get; set; }

    /// <summary>
    /// The operator_addresses attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "OperatorAddresses is required")]
    [TerraformPropertyName("operator_addresses")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformSet<string> OperatorAddresses { get; set; }

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class AzurermVoiceServicesCommunicationsGatewayTimeoutsBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    [TerraformPropertyName("create")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Create { get; set; }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    [TerraformPropertyName("delete")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Delete { get; set; }

    /// <summary>
    /// The read attribute.
    /// </summary>
    [TerraformPropertyName("read")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Read { get; set; }

    /// <summary>
    /// The update attribute.
    /// </summary>
    [TerraformPropertyName("update")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Update { get; set; }

}

/// <summary>
/// Manages a azurerm_voice_services_communications_gateway resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public class AzurermVoiceServicesCommunicationsGateway : TerraformResource
{
    public AzurermVoiceServicesCommunicationsGateway(string name) : base("azurerm_voice_services_communications_gateway", name)
    {
    }

    /// <summary>
    /// The api_bridge attribute.
    /// </summary>
    [TerraformPropertyName("api_bridge")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? ApiBridge { get; set; }

    /// <summary>
    /// The auto_generated_domain_name_label_scope attribute.
    /// </summary>
    [TerraformPropertyName("auto_generated_domain_name_label_scope")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? AutoGeneratedDomainNameLabelScope { get; set; }

    /// <summary>
    /// The codecs attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Codecs is required")]
    [TerraformPropertyName("codecs")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> Codecs { get; set; }

    /// <summary>
    /// The connectivity attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Connectivity is required")]
    [TerraformPropertyName("connectivity")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> Connectivity { get; set; }

    /// <summary>
    /// The e911_type attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "E911Type is required")]
    [TerraformPropertyName("e911_type")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> E911Type { get; set; }

    /// <summary>
    /// The emergency_dial_strings attribute.
    /// </summary>
    [TerraformPropertyName("emergency_dial_strings")]
    // Optional argument - user may or may not set a value
    public TerraformList<string>? EmergencyDialStrings { get; set; }

    /// <summary>
    /// The id attribute.
    /// </summary>
    [TerraformPropertyName("id")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Id { get; set; } = default!;

    /// <summary>
    /// The location attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Location is required")]
    [TerraformPropertyName("location")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> Location { get; set; }

    /// <summary>
    /// The microsoft_teams_voicemail_pilot_number attribute.
    /// </summary>
    [TerraformPropertyName("microsoft_teams_voicemail_pilot_number")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? MicrosoftTeamsVoicemailPilotNumber { get; set; }

    /// <summary>
    /// The name attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    [TerraformPropertyName("name")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> Name { get; set; }

    /// <summary>
    /// The on_prem_mcp_enabled attribute.
    /// </summary>
    [TerraformPropertyName("on_prem_mcp_enabled")]
    // Optional argument - user may or may not set a value
    public TerraformValue<bool>? OnPremMcpEnabled { get; set; }

    /// <summary>
    /// The platforms attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Platforms is required")]
    [TerraformPropertyName("platforms")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public TerraformList<string>? Platforms { get; set; }

    /// <summary>
    /// The resource_group_name attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ResourceGroupName is required")]
    [TerraformPropertyName("resource_group_name")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> ResourceGroupName { get; set; }

    /// <summary>
    /// The tags attribute.
    /// </summary>
    [TerraformPropertyName("tags")]
    // Optional argument - user may or may not set a value
    public TerraformMap<string>? Tags { get; set; }

    /// <summary>
    /// Block for service_location.
    /// Nesting mode: set
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ServiceLocation is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 ServiceLocation block(s) required")]
    [TerraformPropertyName("service_location")]
    public TerraformSet<TerraformBlock<AzurermVoiceServicesCommunicationsGatewayServiceLocationBlock>>? ServiceLocation { get; set; }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    [TerraformPropertyName("timeouts")]
    public TerraformBlock<AzurermVoiceServicesCommunicationsGatewayTimeoutsBlock>? Timeouts { get; set; }

}
