using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Azurerm;

/// <summary>
/// Block type for service_location in AzurermVoiceServicesCommunicationsGateway.
/// Nesting mode: set
/// </summary>
public class AzurermVoiceServicesCommunicationsGatewayServiceLocationBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "service_location";

    /// <summary>
    /// The allowed_media_source_address_prefixes attribute.
    /// </summary>
    public TerraformSet<string>? AllowedMediaSourceAddressPrefixes
    {
        get => GetArgument<TerraformSet<string>>("allowed_media_source_address_prefixes");
        set => SetArgument("allowed_media_source_address_prefixes", value);
    }

    /// <summary>
    /// The allowed_signaling_source_address_prefixes attribute.
    /// </summary>
    public TerraformSet<string>? AllowedSignalingSourceAddressPrefixes
    {
        get => GetArgument<TerraformSet<string>>("allowed_signaling_source_address_prefixes");
        set => SetArgument("allowed_signaling_source_address_prefixes", value);
    }

    /// <summary>
    /// The esrp_addresses attribute.
    /// </summary>
    public TerraformSet<string>? EsrpAddresses
    {
        get => GetArgument<TerraformSet<string>>("esrp_addresses");
        set => SetArgument("esrp_addresses", value);
    }

    /// <summary>
    /// The location attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Location is required")]
    public required TerraformValue<string> Location
    {
        get => GetRequiredArgument<TerraformValue<string>>("location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// The operator_addresses attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "OperatorAddresses is required")]
    public required TerraformSet<string> OperatorAddresses
    {
        get => GetRequiredArgument<TerraformSet<string>>("operator_addresses");
        set => SetArgument("operator_addresses", value);
    }

}


/// <summary>
/// Block type for timeouts in AzurermVoiceServicesCommunicationsGateway.
/// Nesting mode: single
/// </summary>
public class AzurermVoiceServicesCommunicationsGatewayTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "timeouts";

    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformValue<string>? Create
    {
        get => GetArgument<TerraformValue<string>>("create");
        set => SetArgument("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformValue<string>? Delete
    {
        get => GetArgument<TerraformValue<string>>("delete");
        set => SetArgument("delete", value);
    }

    /// <summary>
    /// The read attribute.
    /// </summary>
    public TerraformValue<string>? Read
    {
        get => GetArgument<TerraformValue<string>>("read");
        set => SetArgument("read", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformValue<string>? Update
    {
        get => GetArgument<TerraformValue<string>>("update");
        set => SetArgument("update", value);
    }

}


/// <summary>
/// Represents a azurerm_voice_services_communications_gateway Terraform resource.
/// Manages a azurerm_voice_services_communications_gateway resource.
/// </summary>
public partial class AzurermVoiceServicesCommunicationsGateway(string name) : TerraformResource("azurerm_voice_services_communications_gateway", name)
{
    /// <summary>
    /// The api_bridge attribute.
    /// </summary>
    public TerraformValue<string>? ApiBridge
    {
        get => GetArgument<TerraformValue<string>>("api_bridge");
        set => SetArgument("api_bridge", value);
    }

    /// <summary>
    /// The auto_generated_domain_name_label_scope attribute.
    /// </summary>
    public TerraformValue<string>? AutoGeneratedDomainNameLabelScope
    {
        get => GetArgument<TerraformValue<string>>("auto_generated_domain_name_label_scope");
        set => SetArgument("auto_generated_domain_name_label_scope", value);
    }

    /// <summary>
    /// The codecs attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Codecs is required")]
    public required TerraformValue<string> Codecs
    {
        get => GetRequiredArgument<TerraformValue<string>>("codecs");
        set => SetArgument("codecs", value);
    }

    /// <summary>
    /// The connectivity attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Connectivity is required")]
    public required TerraformValue<string> Connectivity
    {
        get => GetRequiredArgument<TerraformValue<string>>("connectivity");
        set => SetArgument("connectivity", value);
    }

    /// <summary>
    /// The e911_type attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "E911Type is required")]
    public required TerraformValue<string> E911Type
    {
        get => GetRequiredArgument<TerraformValue<string>>("e911_type");
        set => SetArgument("e911_type", value);
    }

    /// <summary>
    /// The emergency_dial_strings attribute.
    /// </summary>
    public TerraformList<string>? EmergencyDialStrings
    {
        get => GetArgument<TerraformList<string>>("emergency_dial_strings");
        set => SetArgument("emergency_dial_strings", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformValue<string> Id
    {
        get => GetArgument<TerraformValue<string>>("id") ?? CreateReference("id");
        set => SetArgument("id", value);
    }

    /// <summary>
    /// The location attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Location is required")]
    public required TerraformValue<string> Location
    {
        get => GetRequiredArgument<TerraformValue<string>>("location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// The microsoft_teams_voicemail_pilot_number attribute.
    /// </summary>
    public TerraformValue<string>? MicrosoftTeamsVoicemailPilotNumber
    {
        get => GetArgument<TerraformValue<string>>("microsoft_teams_voicemail_pilot_number");
        set => SetArgument("microsoft_teams_voicemail_pilot_number", value);
    }

    /// <summary>
    /// The name attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    public required TerraformValue<string> Name
    {
        get => GetRequiredArgument<TerraformValue<string>>("name");
        set => SetArgument("name", value);
    }

    /// <summary>
    /// The on_prem_mcp_enabled attribute.
    /// </summary>
    public TerraformValue<bool>? OnPremMcpEnabled
    {
        get => GetArgument<TerraformValue<bool>>("on_prem_mcp_enabled");
        set => SetArgument("on_prem_mcp_enabled", value);
    }

    /// <summary>
    /// The platforms attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Platforms is required")]
    public TerraformList<string>? Platforms
    {
        get => GetArgument<TerraformList<string>>("platforms");
        set => SetArgument("platforms", value);
    }

    /// <summary>
    /// The resource_group_name attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ResourceGroupName is required")]
    public required TerraformValue<string> ResourceGroupName
    {
        get => GetRequiredArgument<TerraformValue<string>>("resource_group_name");
        set => SetArgument("resource_group_name", value);
    }

    /// <summary>
    /// The tags attribute.
    /// </summary>
    public TerraformMap<string>? Tags
    {
        get => GetArgument<TerraformMap<string>>("tags");
        set => SetArgument("tags", value);
    }

    /// <summary>
    /// ServiceLocation block (nesting mode: set).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ServiceLocation is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 ServiceLocation block(s) required")]
    public required TerraformSet<AzurermVoiceServicesCommunicationsGatewayServiceLocationBlock> ServiceLocation
    {
        get => GetRequiredArgument<TerraformSet<AzurermVoiceServicesCommunicationsGatewayServiceLocationBlock>>("service_location");
        set => SetArgument("service_location", value);
    }

    /// <summary>
    /// Timeouts block (nesting mode: single).
    /// </summary>
    public AzurermVoiceServicesCommunicationsGatewayTimeoutsBlock? Timeouts
    {
        get => GetArgument<AzurermVoiceServicesCommunicationsGatewayTimeoutsBlock>("timeouts");
        set => SetArgument("timeouts", value);
    }

}
