using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.AzureRM;

/// <summary>
/// Block type for service_location in .
/// Nesting mode: set
/// </summary>
public class AzurermVoiceServicesCommunicationsGatewayServiceLocationBlock : TerraformBlock
{
    /// <summary>
    /// The allowed_media_source_address_prefixes attribute.
    /// </summary>
    public HashSet<TerraformProperty<string>>? AllowedMediaSourceAddressPrefixes
    {
        set => SetProperty("allowed_media_source_address_prefixes", value);
    }

    /// <summary>
    /// The allowed_signaling_source_address_prefixes attribute.
    /// </summary>
    public HashSet<TerraformProperty<string>>? AllowedSignalingSourceAddressPrefixes
    {
        set => SetProperty("allowed_signaling_source_address_prefixes", value);
    }

    /// <summary>
    /// The esrp_addresses attribute.
    /// </summary>
    public HashSet<TerraformProperty<string>>? EsrpAddresses
    {
        set => SetProperty("esrp_addresses", value);
    }

    /// <summary>
    /// The location attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Location is required")]
    public required TerraformProperty<string> Location
    {
        set => SetProperty("location", value);
    }

    /// <summary>
    /// The operator_addresses attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "OperatorAddresses is required")]
    public HashSet<TerraformProperty<string>>? OperatorAddresses
    {
        set => SetProperty("operator_addresses", value);
    }

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class AzurermVoiceServicesCommunicationsGatewayTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformProperty<string>? Create
    {
        set => SetProperty("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformProperty<string>? Delete
    {
        set => SetProperty("delete", value);
    }

    /// <summary>
    /// The read attribute.
    /// </summary>
    public TerraformProperty<string>? Read
    {
        set => SetProperty("read", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformProperty<string>? Update
    {
        set => SetProperty("update", value);
    }

}

/// <summary>
/// Manages a azurerm_voice_services_communications_gateway resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public class AzurermVoiceServicesCommunicationsGateway : TerraformResource
{
    public AzurermVoiceServicesCommunicationsGateway(string name) : base("azurerm_voice_services_communications_gateway", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        SetOutput("api_bridge");
        SetOutput("auto_generated_domain_name_label_scope");
        SetOutput("codecs");
        SetOutput("connectivity");
        SetOutput("e911_type");
        SetOutput("emergency_dial_strings");
        SetOutput("id");
        SetOutput("location");
        SetOutput("microsoft_teams_voicemail_pilot_number");
        SetOutput("name");
        SetOutput("on_prem_mcp_enabled");
        SetOutput("platforms");
        SetOutput("resource_group_name");
        SetOutput("tags");
    }

    /// <summary>
    /// The api_bridge attribute.
    /// </summary>
    public TerraformProperty<string> ApiBridge
    {
        get => GetRequiredOutput<TerraformProperty<string>>("api_bridge");
        set => SetProperty("api_bridge", value);
    }

    /// <summary>
    /// The auto_generated_domain_name_label_scope attribute.
    /// </summary>
    public TerraformProperty<string> AutoGeneratedDomainNameLabelScope
    {
        get => GetRequiredOutput<TerraformProperty<string>>("auto_generated_domain_name_label_scope");
        set => SetProperty("auto_generated_domain_name_label_scope", value);
    }

    /// <summary>
    /// The codecs attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Codecs is required")]
    public required TerraformProperty<string> Codecs
    {
        get => GetRequiredOutput<TerraformProperty<string>>("codecs");
        set => SetProperty("codecs", value);
    }

    /// <summary>
    /// The connectivity attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Connectivity is required")]
    public required TerraformProperty<string> Connectivity
    {
        get => GetRequiredOutput<TerraformProperty<string>>("connectivity");
        set => SetProperty("connectivity", value);
    }

    /// <summary>
    /// The e911_type attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "E911Type is required")]
    public required TerraformProperty<string> E911Type
    {
        get => GetRequiredOutput<TerraformProperty<string>>("e911_type");
        set => SetProperty("e911_type", value);
    }

    /// <summary>
    /// The emergency_dial_strings attribute.
    /// </summary>
    public List<TerraformProperty<string>> EmergencyDialStrings
    {
        get => GetRequiredOutput<List<TerraformProperty<string>>>("emergency_dial_strings");
        set => SetProperty("emergency_dial_strings", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformProperty<string> Id
    {
        get => GetRequiredOutput<TerraformProperty<string>>("id");
        set => SetProperty("id", value);
    }

    /// <summary>
    /// The location attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Location is required")]
    public required TerraformProperty<string> Location
    {
        get => GetRequiredOutput<TerraformProperty<string>>("location");
        set => SetProperty("location", value);
    }

    /// <summary>
    /// The microsoft_teams_voicemail_pilot_number attribute.
    /// </summary>
    public TerraformProperty<string> MicrosoftTeamsVoicemailPilotNumber
    {
        get => GetRequiredOutput<TerraformProperty<string>>("microsoft_teams_voicemail_pilot_number");
        set => SetProperty("microsoft_teams_voicemail_pilot_number", value);
    }

    /// <summary>
    /// The name attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    public required TerraformProperty<string> Name
    {
        get => GetRequiredOutput<TerraformProperty<string>>("name");
        set => SetProperty("name", value);
    }

    /// <summary>
    /// The on_prem_mcp_enabled attribute.
    /// </summary>
    public TerraformProperty<bool> OnPremMcpEnabled
    {
        get => GetRequiredOutput<TerraformProperty<bool>>("on_prem_mcp_enabled");
        set => SetProperty("on_prem_mcp_enabled", value);
    }

    /// <summary>
    /// The platforms attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Platforms is required")]
    public List<TerraformProperty<string>> Platforms
    {
        get => GetRequiredOutput<List<TerraformProperty<string>>>("platforms");
        set => SetProperty("platforms", value);
    }

    /// <summary>
    /// The resource_group_name attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ResourceGroupName is required")]
    public required TerraformProperty<string> ResourceGroupName
    {
        get => GetRequiredOutput<TerraformProperty<string>>("resource_group_name");
        set => SetProperty("resource_group_name", value);
    }

    /// <summary>
    /// The tags attribute.
    /// </summary>
    public Dictionary<string, TerraformProperty<string>> Tags
    {
        get => GetRequiredOutput<Dictionary<string, TerraformProperty<string>>>("tags");
        set => SetProperty("tags", value);
    }

    /// <summary>
    /// Block for service_location.
    /// Nesting mode: set
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ServiceLocation is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 ServiceLocation block(s) required")]
    public HashSet<AzurermVoiceServicesCommunicationsGatewayServiceLocationBlock>? ServiceLocation
    {
        set => SetProperty("service_location", value);
    }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    public AzurermVoiceServicesCommunicationsGatewayTimeoutsBlock? Timeouts
    {
        set => SetProperty("timeouts", value);
    }

}
