using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleEndpointsServiceTimeoutsBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    [TerraformPropertyName("create")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Create { get; set; }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    [TerraformPropertyName("delete")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Delete { get; set; }

    /// <summary>
    /// The update attribute.
    /// </summary>
    [TerraformPropertyName("update")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Update { get; set; }

}

/// <summary>
/// Manages a google_endpoints_service resource.
/// </summary>
public class GoogleEndpointsService : TerraformResource
{
    public GoogleEndpointsService(string name) : base("google_endpoints_service", name)
    {
    }

    /// <summary>
    /// The full text of the Service Config YAML file (Example located here). If provided, must also provide protoc_output_base64. open_api config must not be provided.
    /// </summary>
    [TerraformPropertyName("grpc_config")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? GrpcConfig { get; set; }

    /// <summary>
    /// The id attribute.
    /// </summary>
    [TerraformPropertyName("id")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Id { get; set; } = default!;

    /// <summary>
    /// The full text of the OpenAPI YAML configuration as described here. Either this, or both of grpc_config and protoc_output_base64 must be specified.
    /// </summary>
    [TerraformPropertyName("openapi_config")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? OpenapiConfig { get; set; }

    /// <summary>
    /// The project ID that the service belongs to. If not provided, provider project is used.
    /// </summary>
    [TerraformPropertyName("project")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Project { get; set; } = default!;

    /// <summary>
    /// The full contents of the Service Descriptor File generated by protoc. This should be a compiled .pb file, base64-encoded.
    /// </summary>
    [TerraformPropertyName("protoc_output_base64")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? ProtocOutputBase64 { get; set; }

    /// <summary>
    /// The name of the service. Usually of the form $apiname.endpoints.$projectid.cloud.goog.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ServiceName is required")]
    [TerraformPropertyName("service_name")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> ServiceName { get; set; }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    [TerraformPropertyName("timeouts")]
    public TerraformBlock<GoogleEndpointsServiceTimeoutsBlock>? Timeouts { get; set; }

    /// <summary>
    /// A list of API objects.
    /// </summary>
    [TerraformPropertyName("apis")]
    // Output-only attribute - read-only reference
    public TerraformList<object> Apis => new TerraformReference(this, "apis");

    /// <summary>
    /// The autogenerated ID for the configuration that is rolled out as part of the creation of this resource. Must be provided to compute engine instances as a tag.
    /// </summary>
    [TerraformPropertyName("config_id")]
    // Output-only attribute - read-only reference
    public TerraformValue<string> ConfigId => new TerraformReference(this, "config_id");

    /// <summary>
    /// The address at which the service can be found - usually the same as the service name.
    /// </summary>
    [TerraformPropertyName("dns_address")]
    // Output-only attribute - read-only reference
    public TerraformValue<string> DnsAddress => new TerraformReference(this, "dns_address");

    /// <summary>
    /// A list of Endpoint objects.
    /// </summary>
    [TerraformPropertyName("endpoints")]
    // Output-only attribute - read-only reference
    public TerraformList<object> Endpoints => new TerraformReference(this, "endpoints");

}
