using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for access_settings in .
/// Nesting mode: list
/// </summary>
public class GoogleIapSettingsAccessSettingsBlock
{
    /// <summary>
    /// Identity sources that IAP can use to authenticate the end user. Only one identity source
    /// can be configured. The possible values are:
    /// 
    /// * &#39;WORKFORCE_IDENTITY_FEDERATION&#39;: Use external identities set up on Google Cloud Workforce
    ///   				     Identity Federation. Possible values: [&amp;quot;WORKFORCE_IDENTITY_FEDERATION&amp;quot;]
    /// </summary>
    [TerraformPropertyName("identity_sources")]
    // Optional argument - user may or may not set a value
    public TerraformList<string>? IdentitySources { get; set; }

}

/// <summary>
/// Block type for application_settings in .
/// Nesting mode: list
/// </summary>
public class GoogleIapSettingsApplicationSettingsBlock
{
    /// <summary>
    /// The Domain value to set for cookies generated by IAP. This value is not validated by the API,
    /// but will be ignored at runtime if invalid.
    /// </summary>
    [TerraformPropertyName("cookie_domain")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? CookieDomain { get; set; }

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleIapSettingsTimeoutsBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    [TerraformPropertyName("create")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Create { get; set; }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    [TerraformPropertyName("delete")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Delete { get; set; }

    /// <summary>
    /// The update attribute.
    /// </summary>
    [TerraformPropertyName("update")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Update { get; set; }

}

/// <summary>
/// Manages a google_iap_settings resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public class GoogleIapSettings : TerraformResource
{
    public GoogleIapSettings(string name) : base("google_iap_settings", name)
    {
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    [TerraformPropertyName("id")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Id { get; set; } = default!;

    /// <summary>
    /// The resource name of the IAP protected resource. Name can have below resources:
    /// * organizations/{organization_id}
    /// * folders/{folder_id}
    /// * projects/{project_id}
    /// * projects/{project_id}/iap_web
    /// * projects/{project_id}/iap_web/compute
    /// * projects/{project_id}/iap_web/compute-{region}
    /// * projects/{project_id}/iap_web/compute/services/{service_id}
    /// * projects/{project_id}/iap_web/compute-{region}/services/{service_id}
    /// * projects/{project_id}/iap_web/appengine-{app_id}
    /// * projects/{project_id}/iap_web/appengine-{app_id}/services/{service_id}
    /// * projects/{project_id}/iap_web/appengine-{app_id}/services/{service_id}/version/{version_id}
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    [TerraformPropertyName("name")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> Name { get; set; }

    /// <summary>
    /// Block for access_settings.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 AccessSettings block(s) allowed")]
    [TerraformPropertyName("access_settings")]
    public TerraformList<TerraformBlock<GoogleIapSettingsAccessSettingsBlock>>? AccessSettings { get; set; }

    /// <summary>
    /// Block for application_settings.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ApplicationSettings block(s) allowed")]
    [TerraformPropertyName("application_settings")]
    public TerraformList<TerraformBlock<GoogleIapSettingsApplicationSettingsBlock>>? ApplicationSettings { get; set; }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    [TerraformPropertyName("timeouts")]
    public TerraformBlock<GoogleIapSettingsTimeoutsBlock>? Timeouts { get; set; }

}
