using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for config in GooglePrivatecaCertificate.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "config";

    /// <summary>
    /// PublicKey block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "PublicKey is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 PublicKey block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 PublicKey block(s) allowed")]
    public required TerraformList<GooglePrivatecaCertificateConfigBlockPublicKeyBlock> PublicKey
    {
        get => GetRequiredArgument<TerraformList<GooglePrivatecaCertificateConfigBlockPublicKeyBlock>>("public_key");
        set => SetArgument("public_key", value);
    }

    /// <summary>
    /// SubjectConfig block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "SubjectConfig is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 SubjectConfig block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 SubjectConfig block(s) allowed")]
    public required TerraformList<GooglePrivatecaCertificateConfigBlockSubjectConfigBlock> SubjectConfig
    {
        get => GetRequiredArgument<TerraformList<GooglePrivatecaCertificateConfigBlockSubjectConfigBlock>>("subject_config");
        set => SetArgument("subject_config", value);
    }

    /// <summary>
    /// SubjectKeyId block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 SubjectKeyId block(s) allowed")]
    public TerraformList<GooglePrivatecaCertificateConfigBlockSubjectKeyIdBlock>? SubjectKeyId
    {
        get => GetArgument<TerraformList<GooglePrivatecaCertificateConfigBlockSubjectKeyIdBlock>>("subject_key_id");
        set => SetArgument("subject_key_id", value);
    }

    /// <summary>
    /// X509Config block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "X509Config is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 X509Config block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 X509Config block(s) allowed")]
    public required TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlock> X509Config
    {
        get => GetRequiredArgument<TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlock>>("x509_config");
        set => SetArgument("x509_config", value);
    }

}

/// <summary>
/// Block type for public_key in GooglePrivatecaCertificateConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockPublicKeyBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "public_key";

    /// <summary>
    /// The format of the public key. Currently, only PEM format is supported. Possible values: [&amp;quot;KEY_TYPE_UNSPECIFIED&amp;quot;, &amp;quot;PEM&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Format is required")]
    public required TerraformValue<string> Format
    {
        get => GetRequiredArgument<TerraformValue<string>>("format");
        set => SetArgument("format", value);
    }

    /// <summary>
    /// Required. A public key. When this is specified in a request, the padding and encoding can be any of the options described by the respective &#39;KeyType&#39; value. When this is generated by the service, it will always be an RFC 5280 SubjectPublicKeyInfo structure containing an algorithm identifier and a key. A base64-encoded string.
    /// </summary>
    public TerraformValue<string>? Key
    {
        get => GetArgument<TerraformValue<string>>("key");
        set => SetArgument("key", value);
    }

}

/// <summary>
/// Block type for subject_config in GooglePrivatecaCertificateConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockSubjectConfigBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "subject_config";

    /// <summary>
    /// Subject block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Subject is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 Subject block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 Subject block(s) allowed")]
    public required TerraformList<GooglePrivatecaCertificateConfigBlockSubjectConfigBlockSubjectBlock> Subject
    {
        get => GetRequiredArgument<TerraformList<GooglePrivatecaCertificateConfigBlockSubjectConfigBlockSubjectBlock>>("subject");
        set => SetArgument("subject", value);
    }

    /// <summary>
    /// SubjectAltName block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 SubjectAltName block(s) allowed")]
    public TerraformList<GooglePrivatecaCertificateConfigBlockSubjectConfigBlockSubjectAltNameBlock>? SubjectAltName
    {
        get => GetArgument<TerraformList<GooglePrivatecaCertificateConfigBlockSubjectConfigBlockSubjectAltNameBlock>>("subject_alt_name");
        set => SetArgument("subject_alt_name", value);
    }

}

/// <summary>
/// Block type for subject in GooglePrivatecaCertificateConfigBlockSubjectConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockSubjectConfigBlockSubjectBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "subject";

    /// <summary>
    /// The common name of the distinguished name.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "CommonName is required")]
    public required TerraformValue<string> CommonName
    {
        get => GetRequiredArgument<TerraformValue<string>>("common_name");
        set => SetArgument("common_name", value);
    }

    /// <summary>
    /// The country code of the subject.
    /// </summary>
    public TerraformValue<string>? CountryCode
    {
        get => GetArgument<TerraformValue<string>>("country_code");
        set => SetArgument("country_code", value);
    }

    /// <summary>
    /// The locality or city of the subject.
    /// </summary>
    public TerraformValue<string>? Locality
    {
        get => GetArgument<TerraformValue<string>>("locality");
        set => SetArgument("locality", value);
    }

    /// <summary>
    /// The organization of the subject.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Organization is required")]
    public required TerraformValue<string> Organization
    {
        get => GetRequiredArgument<TerraformValue<string>>("organization");
        set => SetArgument("organization", value);
    }

    /// <summary>
    /// The organizational unit of the subject.
    /// </summary>
    public TerraformValue<string>? OrganizationalUnit
    {
        get => GetArgument<TerraformValue<string>>("organizational_unit");
        set => SetArgument("organizational_unit", value);
    }

    /// <summary>
    /// The postal code of the subject.
    /// </summary>
    public TerraformValue<string>? PostalCode
    {
        get => GetArgument<TerraformValue<string>>("postal_code");
        set => SetArgument("postal_code", value);
    }

    /// <summary>
    /// The province, territory, or regional state of the subject.
    /// </summary>
    public TerraformValue<string>? Province
    {
        get => GetArgument<TerraformValue<string>>("province");
        set => SetArgument("province", value);
    }

    /// <summary>
    /// The street address of the subject.
    /// </summary>
    public TerraformValue<string>? StreetAddress
    {
        get => GetArgument<TerraformValue<string>>("street_address");
        set => SetArgument("street_address", value);
    }

}

/// <summary>
/// Block type for subject_alt_name in GooglePrivatecaCertificateConfigBlockSubjectConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockSubjectConfigBlockSubjectAltNameBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "subject_alt_name";

    /// <summary>
    /// Contains only valid, fully-qualified host names.
    /// </summary>
    public TerraformList<string>? DnsNames
    {
        get => GetArgument<TerraformList<string>>("dns_names");
        set => SetArgument("dns_names", value);
    }

    /// <summary>
    /// Contains only valid RFC 2822 E-mail addresses.
    /// </summary>
    public TerraformList<string>? EmailAddresses
    {
        get => GetArgument<TerraformList<string>>("email_addresses");
        set => SetArgument("email_addresses", value);
    }

    /// <summary>
    /// Contains only valid 32-bit IPv4 addresses or RFC 4291 IPv6 addresses.
    /// </summary>
    public TerraformList<string>? IpAddresses
    {
        get => GetArgument<TerraformList<string>>("ip_addresses");
        set => SetArgument("ip_addresses", value);
    }

    /// <summary>
    /// Contains only valid RFC 3986 URIs.
    /// </summary>
    public TerraformList<string>? Uris
    {
        get => GetArgument<TerraformList<string>>("uris");
        set => SetArgument("uris", value);
    }

}

/// <summary>
/// Block type for subject_key_id in GooglePrivatecaCertificateConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockSubjectKeyIdBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "subject_key_id";

    /// <summary>
    /// The value of the KeyId in lowercase hexadecimal.
    /// </summary>
    public TerraformValue<string>? KeyId
    {
        get => GetArgument<TerraformValue<string>>("key_id");
        set => SetArgument("key_id", value);
    }

}

/// <summary>
/// Block type for x509_config in GooglePrivatecaCertificateConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockX509ConfigBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "x509_config";

    /// <summary>
    /// Describes Online Certificate Status Protocol (OCSP) endpoint addresses that appear in the
    /// &amp;quot;Authority Information Access&amp;quot; extension in the certificate.
    /// </summary>
    public TerraformList<string>? AiaOcspServers
    {
        get => GetArgument<TerraformList<string>>("aia_ocsp_servers");
        set => SetArgument("aia_ocsp_servers", value);
    }

    /// <summary>
    /// AdditionalExtensions block (nesting mode: list).
    /// </summary>
    public TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockAdditionalExtensionsBlock>? AdditionalExtensions
    {
        get => GetArgument<TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockAdditionalExtensionsBlock>>("additional_extensions");
        set => SetArgument("additional_extensions", value);
    }

    /// <summary>
    /// CaOptions block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 CaOptions block(s) allowed")]
    public TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockCaOptionsBlock>? CaOptions
    {
        get => GetArgument<TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockCaOptionsBlock>>("ca_options");
        set => SetArgument("ca_options", value);
    }

    /// <summary>
    /// KeyUsage block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "KeyUsage is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 KeyUsage block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 KeyUsage block(s) allowed")]
    public required TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlock> KeyUsage
    {
        get => GetRequiredArgument<TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlock>>("key_usage");
        set => SetArgument("key_usage", value);
    }

    /// <summary>
    /// NameConstraints block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 NameConstraints block(s) allowed")]
    public TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockNameConstraintsBlock>? NameConstraints
    {
        get => GetArgument<TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockNameConstraintsBlock>>("name_constraints");
        set => SetArgument("name_constraints", value);
    }

    /// <summary>
    /// PolicyIds block (nesting mode: list).
    /// </summary>
    public TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockPolicyIdsBlock>? PolicyIds
    {
        get => GetArgument<TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockPolicyIdsBlock>>("policy_ids");
        set => SetArgument("policy_ids", value);
    }

}

/// <summary>
/// Block type for additional_extensions in GooglePrivatecaCertificateConfigBlockX509ConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockX509ConfigBlockAdditionalExtensionsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "additional_extensions";

    /// <summary>
    /// Indicates whether or not this extension is critical (i.e., if the client does not know how to
    /// handle this extension, the client should consider this to be an error).
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Critical is required")]
    public required TerraformValue<bool> Critical
    {
        get => GetRequiredArgument<TerraformValue<bool>>("critical");
        set => SetArgument("critical", value);
    }

    /// <summary>
    /// The value of this X.509 extension. A base64-encoded string.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Value is required")]
    public required TerraformValue<string> Value
    {
        get => GetRequiredArgument<TerraformValue<string>>("value");
        set => SetArgument("value", value);
    }

    /// <summary>
    /// ObjectId block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ObjectId is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 ObjectId block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ObjectId block(s) allowed")]
    public required TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockAdditionalExtensionsBlockObjectIdBlock> ObjectId
    {
        get => GetRequiredArgument<TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockAdditionalExtensionsBlockObjectIdBlock>>("object_id");
        set => SetArgument("object_id", value);
    }

}

/// <summary>
/// Block type for object_id in GooglePrivatecaCertificateConfigBlockX509ConfigBlockAdditionalExtensionsBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockX509ConfigBlockAdditionalExtensionsBlockObjectIdBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "object_id";

    /// <summary>
    /// An ObjectId specifies an object identifier (OID). These provide context and describe types in ASN.1 messages.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ObjectIdPath is required")]
    public TerraformList<double>? ObjectIdPath
    {
        get => GetArgument<TerraformList<double>>("object_id_path");
        set => SetArgument("object_id_path", value);
    }

}

/// <summary>
/// Block type for ca_options in GooglePrivatecaCertificateConfigBlockX509ConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockX509ConfigBlockCaOptionsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "ca_options";

    /// <summary>
    /// When true, the &amp;quot;CA&amp;quot; in Basic Constraints extension will be set to true.
    /// </summary>
    public TerraformValue<bool>? IsCa
    {
        get => GetArgument<TerraformValue<bool>>("is_ca");
        set => SetArgument("is_ca", value);
    }

    /// <summary>
    /// Refers to the &amp;quot;path length constraint&amp;quot; in Basic Constraints extension. For a CA certificate, this value describes the depth of
    /// subordinate CA certificates that are allowed. If this value is less than 0, the request will fail.
    /// </summary>
    public TerraformValue<double>? MaxIssuerPathLength
    {
        get => GetArgument<TerraformValue<double>>("max_issuer_path_length");
        set => SetArgument("max_issuer_path_length", value);
    }

    /// <summary>
    /// When true, the &amp;quot;CA&amp;quot; in Basic Constraints extension will be set to false.
    /// If both &#39;is_ca&#39; and &#39;non_ca&#39; are unset, the extension will be omitted from the CA certificate.
    /// </summary>
    public TerraformValue<bool>? NonCa
    {
        get => GetArgument<TerraformValue<bool>>("non_ca");
        set => SetArgument("non_ca", value);
    }

    /// <summary>
    /// When true, the &amp;quot;path length constraint&amp;quot; in Basic Constraints extension will be set to 0.
    /// if both &#39;max_issuer_path_length&#39; and &#39;zero_max_issuer_path_length&#39; are unset,
    /// the max path length will be omitted from the CA certificate.
    /// </summary>
    public TerraformValue<bool>? ZeroMaxIssuerPathLength
    {
        get => GetArgument<TerraformValue<bool>>("zero_max_issuer_path_length");
        set => SetArgument("zero_max_issuer_path_length", value);
    }

}

/// <summary>
/// Block type for key_usage in GooglePrivatecaCertificateConfigBlockX509ConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "key_usage";

    /// <summary>
    /// BaseKeyUsage block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "BaseKeyUsage is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 BaseKeyUsage block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 BaseKeyUsage block(s) allowed")]
    public required TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlockBaseKeyUsageBlock> BaseKeyUsage
    {
        get => GetRequiredArgument<TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlockBaseKeyUsageBlock>>("base_key_usage");
        set => SetArgument("base_key_usage", value);
    }

    /// <summary>
    /// ExtendedKeyUsage block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ExtendedKeyUsage is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 ExtendedKeyUsage block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ExtendedKeyUsage block(s) allowed")]
    public required TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlockExtendedKeyUsageBlock> ExtendedKeyUsage
    {
        get => GetRequiredArgument<TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlockExtendedKeyUsageBlock>>("extended_key_usage");
        set => SetArgument("extended_key_usage", value);
    }

    /// <summary>
    /// UnknownExtendedKeyUsages block (nesting mode: list).
    /// </summary>
    public TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlockUnknownExtendedKeyUsagesBlock>? UnknownExtendedKeyUsages
    {
        get => GetArgument<TerraformList<GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlockUnknownExtendedKeyUsagesBlock>>("unknown_extended_key_usages");
        set => SetArgument("unknown_extended_key_usages", value);
    }

}

/// <summary>
/// Block type for base_key_usage in GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlockBaseKeyUsageBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "base_key_usage";

    /// <summary>
    /// The key may be used to sign certificates.
    /// </summary>
    public TerraformValue<bool>? CertSign
    {
        get => GetArgument<TerraformValue<bool>>("cert_sign");
        set => SetArgument("cert_sign", value);
    }

    /// <summary>
    /// The key may be used for cryptographic commitments. Note that this may also be referred to as &amp;quot;non-repudiation&amp;quot;.
    /// </summary>
    public TerraformValue<bool>? ContentCommitment
    {
        get => GetArgument<TerraformValue<bool>>("content_commitment");
        set => SetArgument("content_commitment", value);
    }

    /// <summary>
    /// The key may be used sign certificate revocation lists.
    /// </summary>
    public TerraformValue<bool>? CrlSign
    {
        get => GetArgument<TerraformValue<bool>>("crl_sign");
        set => SetArgument("crl_sign", value);
    }

    /// <summary>
    /// The key may be used to encipher data.
    /// </summary>
    public TerraformValue<bool>? DataEncipherment
    {
        get => GetArgument<TerraformValue<bool>>("data_encipherment");
        set => SetArgument("data_encipherment", value);
    }

    /// <summary>
    /// The key may be used to decipher only.
    /// </summary>
    public TerraformValue<bool>? DecipherOnly
    {
        get => GetArgument<TerraformValue<bool>>("decipher_only");
        set => SetArgument("decipher_only", value);
    }

    /// <summary>
    /// The key may be used for digital signatures.
    /// </summary>
    public TerraformValue<bool>? DigitalSignature
    {
        get => GetArgument<TerraformValue<bool>>("digital_signature");
        set => SetArgument("digital_signature", value);
    }

    /// <summary>
    /// The key may be used to encipher only.
    /// </summary>
    public TerraformValue<bool>? EncipherOnly
    {
        get => GetArgument<TerraformValue<bool>>("encipher_only");
        set => SetArgument("encipher_only", value);
    }

    /// <summary>
    /// The key may be used in a key agreement protocol.
    /// </summary>
    public TerraformValue<bool>? KeyAgreement
    {
        get => GetArgument<TerraformValue<bool>>("key_agreement");
        set => SetArgument("key_agreement", value);
    }

    /// <summary>
    /// The key may be used to encipher other keys.
    /// </summary>
    public TerraformValue<bool>? KeyEncipherment
    {
        get => GetArgument<TerraformValue<bool>>("key_encipherment");
        set => SetArgument("key_encipherment", value);
    }

}

/// <summary>
/// Block type for extended_key_usage in GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlockExtendedKeyUsageBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "extended_key_usage";

    /// <summary>
    /// Corresponds to OID 1.3.6.1.5.5.7.3.2. Officially described as &amp;quot;TLS WWW client authentication&amp;quot;, though regularly used for non-WWW TLS.
    /// </summary>
    public TerraformValue<bool>? ClientAuth
    {
        get => GetArgument<TerraformValue<bool>>("client_auth");
        set => SetArgument("client_auth", value);
    }

    /// <summary>
    /// Corresponds to OID 1.3.6.1.5.5.7.3.3. Officially described as &amp;quot;Signing of downloadable executable code client authentication&amp;quot;.
    /// </summary>
    public TerraformValue<bool>? CodeSigning
    {
        get => GetArgument<TerraformValue<bool>>("code_signing");
        set => SetArgument("code_signing", value);
    }

    /// <summary>
    /// Corresponds to OID 1.3.6.1.5.5.7.3.4. Officially described as &amp;quot;Email protection&amp;quot;.
    /// </summary>
    public TerraformValue<bool>? EmailProtection
    {
        get => GetArgument<TerraformValue<bool>>("email_protection");
        set => SetArgument("email_protection", value);
    }

    /// <summary>
    /// Corresponds to OID 1.3.6.1.5.5.7.3.9. Officially described as &amp;quot;Signing OCSP responses&amp;quot;.
    /// </summary>
    public TerraformValue<bool>? OcspSigning
    {
        get => GetArgument<TerraformValue<bool>>("ocsp_signing");
        set => SetArgument("ocsp_signing", value);
    }

    /// <summary>
    /// Corresponds to OID 1.3.6.1.5.5.7.3.1. Officially described as &amp;quot;TLS WWW server authentication&amp;quot;, though regularly used for non-WWW TLS.
    /// </summary>
    public TerraformValue<bool>? ServerAuth
    {
        get => GetArgument<TerraformValue<bool>>("server_auth");
        set => SetArgument("server_auth", value);
    }

    /// <summary>
    /// Corresponds to OID 1.3.6.1.5.5.7.3.8. Officially described as &amp;quot;Binding the hash of an object to a time&amp;quot;.
    /// </summary>
    public TerraformValue<bool>? TimeStamping
    {
        get => GetArgument<TerraformValue<bool>>("time_stamping");
        set => SetArgument("time_stamping", value);
    }

}

/// <summary>
/// Block type for unknown_extended_key_usages in GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockX509ConfigBlockKeyUsageBlockUnknownExtendedKeyUsagesBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "unknown_extended_key_usages";

    /// <summary>
    /// An ObjectId specifies an object identifier (OID). These provide context and describe types in ASN.1 messages.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ObjectIdPath is required")]
    public TerraformList<double>? ObjectIdPath
    {
        get => GetArgument<TerraformList<double>>("object_id_path");
        set => SetArgument("object_id_path", value);
    }

}

/// <summary>
/// Block type for name_constraints in GooglePrivatecaCertificateConfigBlockX509ConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockX509ConfigBlockNameConstraintsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "name_constraints";

    /// <summary>
    /// Indicates whether or not the name constraints are marked critical.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Critical is required")]
    public required TerraformValue<bool> Critical
    {
        get => GetRequiredArgument<TerraformValue<bool>>("critical");
        set => SetArgument("critical", value);
    }

    /// <summary>
    /// Contains excluded DNS names. Any DNS name that can be
    /// constructed by simply adding zero or more labels to
    /// the left-hand side of the name satisfies the name constraint.
    /// For example, &#39;example.com&#39;, &#39;www.example.com&#39;, &#39;www.sub.example.com&#39;
    /// would satisfy &#39;example.com&#39; while &#39;example1.com&#39; does not.
    /// </summary>
    public TerraformList<string>? ExcludedDnsNames
    {
        get => GetArgument<TerraformList<string>>("excluded_dns_names");
        set => SetArgument("excluded_dns_names", value);
    }

    /// <summary>
    /// Contains the excluded email addresses. The value can be a particular
    /// email address, a hostname to indicate all email addresses on that host or
    /// a domain with a leading period (e.g. &#39;.example.com&#39;) to indicate
    /// all email addresses in that domain.
    /// </summary>
    public TerraformList<string>? ExcludedEmailAddresses
    {
        get => GetArgument<TerraformList<string>>("excluded_email_addresses");
        set => SetArgument("excluded_email_addresses", value);
    }

    /// <summary>
    /// Contains the excluded IP ranges. For IPv4 addresses, the ranges
    /// are expressed using CIDR notation as specified in RFC 4632.
    /// For IPv6 addresses, the ranges are expressed in similar encoding as IPv4
    /// addresses.
    /// </summary>
    public TerraformList<string>? ExcludedIpRanges
    {
        get => GetArgument<TerraformList<string>>("excluded_ip_ranges");
        set => SetArgument("excluded_ip_ranges", value);
    }

    /// <summary>
    /// Contains the excluded URIs that apply to the host part of the name.
    /// The value can be a hostname or a domain with a
    /// leading period (like &#39;.example.com&#39;)
    /// </summary>
    public TerraformList<string>? ExcludedUris
    {
        get => GetArgument<TerraformList<string>>("excluded_uris");
        set => SetArgument("excluded_uris", value);
    }

    /// <summary>
    /// Contains permitted DNS names. Any DNS name that can be
    /// constructed by simply adding zero or more labels to
    /// the left-hand side of the name satisfies the name constraint.
    /// For example, &#39;example.com&#39;, &#39;www.example.com&#39;, &#39;www.sub.example.com&#39;
    /// would satisfy &#39;example.com&#39; while &#39;example1.com&#39; does not.
    /// </summary>
    public TerraformList<string>? PermittedDnsNames
    {
        get => GetArgument<TerraformList<string>>("permitted_dns_names");
        set => SetArgument("permitted_dns_names", value);
    }

    /// <summary>
    /// Contains the permitted email addresses. The value can be a particular
    /// email address, a hostname to indicate all email addresses on that host or
    /// a domain with a leading period (e.g. &#39;.example.com&#39;) to indicate
    /// all email addresses in that domain.
    /// </summary>
    public TerraformList<string>? PermittedEmailAddresses
    {
        get => GetArgument<TerraformList<string>>("permitted_email_addresses");
        set => SetArgument("permitted_email_addresses", value);
    }

    /// <summary>
    /// Contains the permitted IP ranges. For IPv4 addresses, the ranges
    /// are expressed using CIDR notation as specified in RFC 4632.
    /// For IPv6 addresses, the ranges are expressed in similar encoding as IPv4
    /// addresses.
    /// </summary>
    public TerraformList<string>? PermittedIpRanges
    {
        get => GetArgument<TerraformList<string>>("permitted_ip_ranges");
        set => SetArgument("permitted_ip_ranges", value);
    }

    /// <summary>
    /// Contains the permitted URIs that apply to the host part of the name.
    /// The value can be a hostname or a domain with a
    /// leading period (like &#39;.example.com&#39;)
    /// </summary>
    public TerraformList<string>? PermittedUris
    {
        get => GetArgument<TerraformList<string>>("permitted_uris");
        set => SetArgument("permitted_uris", value);
    }

}

/// <summary>
/// Block type for policy_ids in GooglePrivatecaCertificateConfigBlockX509ConfigBlock.
/// Nesting mode: list
/// </summary>
public class GooglePrivatecaCertificateConfigBlockX509ConfigBlockPolicyIdsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "policy_ids";

    /// <summary>
    /// An ObjectId specifies an object identifier (OID). These provide context and describe types in ASN.1 messages.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ObjectIdPath is required")]
    public TerraformList<double>? ObjectIdPath
    {
        get => GetArgument<TerraformList<double>>("object_id_path");
        set => SetArgument("object_id_path", value);
    }

}


/// <summary>
/// Block type for timeouts in GooglePrivatecaCertificate.
/// Nesting mode: single
/// </summary>
public class GooglePrivatecaCertificateTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "timeouts";

    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformValue<string>? Create
    {
        get => GetArgument<TerraformValue<string>>("create");
        set => SetArgument("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformValue<string>? Delete
    {
        get => GetArgument<TerraformValue<string>>("delete");
        set => SetArgument("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformValue<string>? Update
    {
        get => GetArgument<TerraformValue<string>>("update");
        set => SetArgument("update", value);
    }

}


/// <summary>
/// Represents a google_privateca_certificate Terraform resource.
/// Manages a google_privateca_certificate resource.
/// </summary>
public partial class GooglePrivatecaCertificate(string name) : TerraformResource("google_privateca_certificate", name)
{
    /// <summary>
    /// The Certificate Authority ID that should issue the certificate. For example, to issue a Certificate from
    /// a Certificate Authority with resource name &#39;projects/my-project/locations/us-central1/caPools/my-pool/certificateAuthorities/my-ca&#39;,
    /// argument &#39;pool&#39; should be set to &#39;projects/my-project/locations/us-central1/caPools/my-pool&#39;, argument &#39;certificate_authority&#39;
    /// should be set to &#39;my-ca&#39;.
    /// </summary>
    public TerraformValue<string>? CertificateAuthority
    {
        get => GetArgument<TerraformValue<string>>("certificate_authority");
        set => SetArgument("certificate_authority", value);
    }

    /// <summary>
    /// The resource name for a CertificateTemplate used to issue this certificate,
    /// in the format &#39;projects/*/locations/*/certificateTemplates/*&#39;. If this is specified,
    /// the caller must have the necessary permission to use this template. If this is
    /// omitted, no template will be used. This template must be in the same location
    /// as the Certificate.
    /// </summary>
    public TerraformValue<string>? CertificateTemplate
    {
        get => GetArgument<TerraformValue<string>>("certificate_template");
        set => SetArgument("certificate_template", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformValue<string> Id
    {
        get => GetArgument<TerraformValue<string>>("id") ?? AsReference("id");
        set => SetArgument("id", value);
    }

    /// <summary>
    /// Labels with user-defined metadata to apply to this resource.
    /// 
    /// 
    /// **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
    /// Please refer to the field &#39;effective_labels&#39; for all of the labels present on the resource.
    /// </summary>
    public TerraformMap<string>? Labels
    {
        get => GetArgument<TerraformMap<string>>("labels");
        set => SetArgument("labels", value);
    }

    /// <summary>
    /// The desired lifetime of the CA certificate. Used to create the &amp;quot;notBeforeTime&amp;quot; and
    /// &amp;quot;notAfterTime&amp;quot; fields inside an X.509 certificate. A duration in seconds with up to nine
    /// fractional digits, terminated by &#39;s&#39;. Example: &amp;quot;3.5s&amp;quot;.
    /// </summary>
    public TerraformValue<string>? Lifetime
    {
        get => GetArgument<TerraformValue<string>>("lifetime");
        set => SetArgument("lifetime", value);
    }

    /// <summary>
    /// Location of the Certificate. A full list of valid locations can be found by
    /// running &#39;gcloud privateca locations list&#39;.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Location is required")]
    public required TerraformValue<string> Location
    {
        get => GetRequiredArgument<TerraformValue<string>>("location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// The name for this Certificate.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    public required TerraformValue<string> Name
    {
        get => GetRequiredArgument<TerraformValue<string>>("name");
        set => SetArgument("name", value);
    }

    /// <summary>
    /// Immutable. A pem-encoded X.509 certificate signing request (CSR).
    /// </summary>
    public TerraformValue<string>? PemCsr
    {
        get => GetArgument<TerraformValue<string>>("pem_csr");
        set => SetArgument("pem_csr", value);
    }

    /// <summary>
    /// The name of the CaPool this Certificate belongs to.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Pool is required")]
    public required TerraformValue<string> Pool
    {
        get => GetRequiredArgument<TerraformValue<string>>("pool");
        set => SetArgument("pool", value);
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public TerraformValue<string> Project
    {
        get => GetArgument<TerraformValue<string>>("project") ?? AsReference("project");
        set => SetArgument("project", value);
    }

    /// <summary>
    /// Output only. Details regarding the revocation of this Certificate. This Certificate is considered revoked if and only if this field is present.
    /// </summary>
    public TerraformList<TerraformMap<object>> CertificateDescription
        => AsReference("certificate_description");

    /// <summary>
    /// The time that this resource was created on the server.
    /// This is in RFC3339 text format.
    /// </summary>
    public TerraformValue<string> CreateTime
        => AsReference("create_time");

    /// <summary>
    /// All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.
    /// </summary>
    public TerraformMap<string> EffectiveLabels
        => AsReference("effective_labels");

    /// <summary>
    /// The resource name of the issuing CertificateAuthority in the format &#39;projects/*/locations/*/caPools/*/certificateAuthorities/*&#39;.
    /// </summary>
    public TerraformValue<string> IssuerCertificateAuthority
        => AsReference("issuer_certificate_authority");

    /// <summary>
    /// Output only. The pem-encoded, signed X.509 certificate.
    /// </summary>
    public TerraformValue<string> PemCertificate
        => AsReference("pem_certificate");

    /// <summary>
    /// The chain that may be used to verify the X.509 certificate. Expected to be in issuer-to-root order according to RFC 5246.
    /// </summary>
    public TerraformList<string> PemCertificateChain
        => AsReference("pem_certificate_chain");

    /// <summary>
    /// Output only. Details regarding the revocation of this Certificate. This Certificate is
    /// considered revoked if and only if this field is present.
    /// </summary>
    public TerraformList<TerraformMap<object>> RevocationDetails
        => AsReference("revocation_details");

    /// <summary>
    /// The combination of labels configured directly on the resource
    ///  and default labels configured on the provider.
    /// </summary>
    public TerraformMap<string> TerraformLabels
        => AsReference("terraform_labels");

    /// <summary>
    /// Output only. The time at which this CertificateAuthority was updated.
    /// This is in RFC3339 text format.
    /// </summary>
    public TerraformValue<string> UpdateTime
        => AsReference("update_time");

    /// <summary>
    /// Config block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 Config block(s) allowed")]
    public TerraformList<GooglePrivatecaCertificateConfigBlock>? Config
    {
        get => GetArgument<TerraformList<GooglePrivatecaCertificateConfigBlock>>("config");
        set => SetArgument("config", value);
    }

    /// <summary>
    /// Timeouts block (nesting mode: single).
    /// </summary>
    public GooglePrivatecaCertificateTimeoutsBlock? Timeouts
    {
        get => GetArgument<GooglePrivatecaCertificateTimeoutsBlock>("timeouts");
        set => SetArgument("timeouts", value);
    }

}
