using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for timeouts in GooglePublicCaExternalAccountKey.
/// Nesting mode: single
/// </summary>
public class GooglePublicCaExternalAccountKeyTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "timeouts";

    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformValue<string>? Create
    {
        get => GetArgument<TerraformValue<string>>("create");
        set => SetArgument("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformValue<string>? Delete
    {
        get => GetArgument<TerraformValue<string>>("delete");
        set => SetArgument("delete", value);
    }

}


/// <summary>
/// Represents a google_public_ca_external_account_key Terraform resource.
/// Manages a google_public_ca_external_account_key resource.
/// </summary>
public partial class GooglePublicCaExternalAccountKey(string name) : TerraformResource("google_public_ca_external_account_key", name)
{
    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformValue<string> Id
    {
        get => GetArgument<TerraformValue<string>>("id") ?? CreateReference("id");
        set => SetArgument("id", value);
    }

    /// <summary>
    /// Location for the externalAccountKey. Currently only &#39;global&#39; is supported.
    /// </summary>
    public TerraformValue<string>? Location
    {
        get => GetArgument<TerraformValue<string>>("location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public TerraformValue<string> Project
    {
        get => GetArgument<TerraformValue<string>>("project") ?? CreateReference("project");
        set => SetArgument("project", value);
    }

    /// <summary>
    /// Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService
    /// when the ExternalAccountKey is created.
    /// </summary>
    [Obsolete("This property is deprecated.")]
    public TerraformValue<string> B64MacKey
        => CreateReference("b64_mac_key");

    /// <summary>
    /// Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService
    /// when the ExternalAccountKey is created.&#39;
    /// </summary>
    public TerraformValue<string> B64urlMacKey
        => CreateReference("b64url_mac_key");

    /// <summary>
    /// It is generated by the PublicCertificateAuthorityService when the ExternalAccountKey is created.
    /// </summary>
    public TerraformValue<string> KeyId
        => CreateReference("key_id");

    /// <summary>
    /// Resource name. projects/{project}/locations/{location}/externalAccountKeys/{keyId}.
    /// </summary>
    public TerraformValue<string> Name
        => CreateReference("name");

    /// <summary>
    /// Timeouts block (nesting mode: single).
    /// </summary>
    public GooglePublicCaExternalAccountKeyTimeoutsBlock? Timeouts
    {
        get => GetArgument<GooglePublicCaExternalAccountKeyTimeoutsBlock>("timeouts");
        set => SetArgument("timeouts", value);
    }

}
