using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for log_config in .
/// Nesting mode: list
/// </summary>
public class GoogleNetworkServicesWasmPluginLogConfigBlock
{
    /// <summary>
    /// Optional. Specifies whether to enable logging for activity by this plugin.
    /// </summary>
    [TerraformPropertyName("enable")]
    // Optional argument - user may or may not set a value
    public TerraformValue<bool>? Enable { get; set; }

    /// <summary>
    /// Non-empty default. Specificies the lowest level of the plugin logs that are exported to Cloud Logging. This setting relates to the logs generated by using logging statements in your Wasm code.
    /// This field is can be set only if logging is enabled for the plugin.
    /// If the field is not provided when logging is enabled, it is set to INFO by default. Possible values: [&amp;quot;LOG_LEVEL_UNSPECIFIED&amp;quot;, &amp;quot;TRACE&amp;quot;, &amp;quot;DEBUG&amp;quot;, &amp;quot;INFO&amp;quot;, &amp;quot;WARN&amp;quot;, &amp;quot;ERROR&amp;quot;, &amp;quot;CRITICAL&amp;quot;]
    /// </summary>
    [TerraformPropertyName("min_log_level")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> MinLogLevel { get; set; } = default!;

    /// <summary>
    /// Non-empty default. Configures the sampling rate of activity logs, where 1.0 means all logged activity is reported and 0.0 means no activity is reported.
    /// A floating point value between 0.0 and 1.0 indicates that a percentage of log messages is stored.
    /// The default value when logging is enabled is 1.0. The value of the field must be between 0 and 1 (inclusive).
    /// This field can be specified only if logging is enabled for this plugin.
    /// </summary>
    [TerraformPropertyName("sample_rate")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<double> SampleRate { get; set; } = default!;

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleNetworkServicesWasmPluginTimeoutsBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    [TerraformPropertyName("create")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Create { get; set; }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    [TerraformPropertyName("delete")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Delete { get; set; }

    /// <summary>
    /// The update attribute.
    /// </summary>
    [TerraformPropertyName("update")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Update { get; set; }

}

/// <summary>
/// Block type for versions in .
/// Nesting mode: set
/// </summary>
public class GoogleNetworkServicesWasmPluginVersionsBlock
{

    /// <summary>
    /// Optional. A human-readable description of the resource.
    /// </summary>
    [TerraformPropertyName("description")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Description { get; set; }


    /// <summary>
    /// Optional. URI of the container image containing the plugin, stored in the Artifact Registry. When a new WasmPluginVersion resource is created, the digest of the container image is saved in the imageDigest field.
    /// When downloading an image, the digest value is used instead of an image tag.
    /// </summary>
    [TerraformPropertyName("image_uri")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? ImageUri { get; set; }

    /// <summary>
    /// Optional. Set of labels associated with the WasmPlugin resource.
    /// </summary>
    [TerraformPropertyName("labels")]
    // Optional argument - user may or may not set a value
    public TerraformMap<string>? Labels { get; set; }

    /// <summary>
    /// A base64-encoded string containing the configuration for the plugin. The configuration is provided to the plugin at runtime through the ON_CONFIGURE callback.
    /// When a new WasmPluginVersion resource is created, the digest of the contents is saved in the pluginConfigDigest field.
    /// Conflics with pluginConfigUri.
    /// </summary>
    [TerraformPropertyName("plugin_config_data")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? PluginConfigData { get; set; }


    /// <summary>
    /// URI of the plugin configuration stored in the Artifact Registry. The configuration is provided to the plugin at runtime through the ON_CONFIGURE callback.
    /// The container image must contain only a single file with the name plugin.config.
    /// When a new WasmPluginVersion resource is created, the digest of the container image is saved in the pluginConfigDigest field.
    /// Conflics with pluginConfigData.
    /// </summary>
    [TerraformPropertyName("plugin_config_uri")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? PluginConfigUri { get; set; }


    /// <summary>
    /// The version_name attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "VersionName is required")]
    [TerraformPropertyName("version_name")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> VersionName { get; set; }

}

/// <summary>
/// Manages a google_network_services_wasm_plugin resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public class GoogleNetworkServicesWasmPlugin : TerraformResource
{
    public GoogleNetworkServicesWasmPlugin(string name) : base("google_network_services_wasm_plugin", name)
    {
    }

    /// <summary>
    /// Optional. A human-readable description of the resource.
    /// </summary>
    [TerraformPropertyName("description")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Description { get; set; }

    /// <summary>
    /// The id attribute.
    /// </summary>
    [TerraformPropertyName("id")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Id { get; set; } = default!;

    /// <summary>
    /// Optional. Set of labels associated with the WasmPlugin resource.
    /// 
    /// **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
    /// Please refer to the field &#39;effective_labels&#39; for all of the labels present on the resource.
    /// </summary>
    [TerraformPropertyName("labels")]
    // Optional argument - user may or may not set a value
    public TerraformMap<string>? Labels { get; set; }

    /// <summary>
    /// The location of the traffic extension
    /// </summary>
    [TerraformPropertyName("location")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Location { get; set; }

    /// <summary>
    /// The ID of the WasmPluginVersion resource that is the currently serving one. The version referred to must be a child of this WasmPlugin resource and should be listed in the &amp;quot;versions&amp;quot; field.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "MainVersionId is required")]
    [TerraformPropertyName("main_version_id")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> MainVersionId { get; set; }

    /// <summary>
    /// Identifier. Name of the WasmPlugin resource.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    [TerraformPropertyName("name")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> Name { get; set; }

    /// <summary>
    /// The project attribute.
    /// </summary>
    [TerraformPropertyName("project")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Project { get; set; } = default!;

    /// <summary>
    /// Block for log_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 LogConfig block(s) allowed")]
    [TerraformPropertyName("log_config")]
    public TerraformList<TerraformBlock<GoogleNetworkServicesWasmPluginLogConfigBlock>>? LogConfig { get; set; }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    [TerraformPropertyName("timeouts")]
    public TerraformBlock<GoogleNetworkServicesWasmPluginTimeoutsBlock>? Timeouts { get; set; }

    /// <summary>
    /// Block for versions.
    /// Nesting mode: set
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Versions is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 Versions block(s) required")]
    [TerraformPropertyName("versions")]
    public TerraformSet<TerraformBlock<GoogleNetworkServicesWasmPluginVersionsBlock>>? Versions { get; set; }

    /// <summary>
    /// Output only. The timestamp when the resource was created.
    /// </summary>
    [TerraformPropertyName("create_time")]
    // Output-only attribute - read-only reference
    public TerraformValue<string> CreateTime => new TerraformReference(this, "create_time");

    /// <summary>
    /// All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.
    /// </summary>
    [TerraformPropertyName("effective_labels")]
    // Output-only attribute - read-only reference
    public TerraformMap<string> EffectiveLabels => new TerraformReference(this, "effective_labels");

    /// <summary>
    /// The combination of labels configured directly on the resource
    ///  and default labels configured on the provider.
    /// </summary>
    [TerraformPropertyName("terraform_labels")]
    // Output-only attribute - read-only reference
    public TerraformMap<string> TerraformLabels => new TerraformReference(this, "terraform_labels");

    /// <summary>
    /// Output only. The timestamp when the resource was updated.
    /// </summary>
    [TerraformPropertyName("update_time")]
    // Output-only attribute - read-only reference
    public TerraformValue<string> UpdateTime => new TerraformReference(this, "update_time");

    /// <summary>
    /// Output only. List of all extensions that use this WasmPlugin resource.
    /// </summary>
    [TerraformPropertyName("used_by")]
    // Output-only attribute - read-only reference
    public TerraformList<object> UsedBy => new TerraformReference(this, "used_by");

}
