using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for client in .
/// Nesting mode: list
/// </summary>
public class GoogleIdentityPlatformTenantClientBlock
{
}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleIdentityPlatformTenantTimeoutsBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    [TerraformPropertyName("create")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Create { get; set; }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    [TerraformPropertyName("delete")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Delete { get; set; }

    /// <summary>
    /// The update attribute.
    /// </summary>
    [TerraformPropertyName("update")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Update { get; set; }

}

/// <summary>
/// Manages a google_identity_platform_tenant resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public class GoogleIdentityPlatformTenant : TerraformResource
{
    public GoogleIdentityPlatformTenant(string name) : base("google_identity_platform_tenant", name)
    {
    }

    /// <summary>
    /// Whether to allow email/password user authentication.
    /// </summary>
    [TerraformPropertyName("allow_password_signup")]
    // Optional argument - user may or may not set a value
    public TerraformValue<bool>? AllowPasswordSignup { get; set; }

    /// <summary>
    /// Whether authentication is disabled for the tenant. If true, the users under
    /// the disabled tenant are not allowed to sign-in. Admins of the disabled tenant
    /// are not able to manage its users.
    /// </summary>
    [TerraformPropertyName("disable_auth")]
    // Optional argument - user may or may not set a value
    public TerraformValue<bool>? DisableAuth { get; set; }

    /// <summary>
    /// Human friendly display name of the tenant.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "DisplayName is required")]
    [TerraformPropertyName("display_name")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> DisplayName { get; set; }

    /// <summary>
    /// Whether to enable email link user authentication.
    /// </summary>
    [TerraformPropertyName("enable_email_link_signin")]
    // Optional argument - user may or may not set a value
    public TerraformValue<bool>? EnableEmailLinkSignin { get; set; }

    /// <summary>
    /// The id attribute.
    /// </summary>
    [TerraformPropertyName("id")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Id { get; set; } = default!;

    /// <summary>
    /// The project attribute.
    /// </summary>
    [TerraformPropertyName("project")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Project { get; set; } = default!;

    /// <summary>
    /// Block for client.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 Client block(s) allowed")]
    [TerraformPropertyName("client")]
    public TerraformList<TerraformBlock<GoogleIdentityPlatformTenantClientBlock>>? Client { get; set; }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    [TerraformPropertyName("timeouts")]
    public TerraformBlock<GoogleIdentityPlatformTenantTimeoutsBlock>? Timeouts { get; set; }

    /// <summary>
    /// The name of the tenant that is generated by the server
    /// </summary>
    [TerraformPropertyName("name")]
    // Output-only attribute - read-only reference
    public TerraformValue<string> Name => new TerraformReference(this, "name");

}
