using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for client in .
/// Nesting mode: list
/// </summary>
public class GoogleIdentityPlatformTenantClientBlock : TerraformBlock
{
}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleIdentityPlatformTenantTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformProperty<string>? Create
    {
        set => SetProperty("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformProperty<string>? Delete
    {
        set => SetProperty("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformProperty<string>? Update
    {
        set => SetProperty("update", value);
    }

}

/// <summary>
/// Manages a google_identity_platform_tenant resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public class GoogleIdentityPlatformTenant : TerraformResource
{
    public GoogleIdentityPlatformTenant(string name) : base("google_identity_platform_tenant", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        SetOutput("name");
        SetOutput("allow_password_signup");
        SetOutput("disable_auth");
        SetOutput("display_name");
        SetOutput("enable_email_link_signin");
        SetOutput("id");
        SetOutput("project");
    }

    /// <summary>
    /// Whether to allow email/password user authentication.
    /// </summary>
    public TerraformProperty<bool> AllowPasswordSignup
    {
        get => GetRequiredOutput<TerraformProperty<bool>>("allow_password_signup");
        set => SetProperty("allow_password_signup", value);
    }

    /// <summary>
    /// Whether authentication is disabled for the tenant. If true, the users under
    /// the disabled tenant are not allowed to sign-in. Admins of the disabled tenant
    /// are not able to manage its users.
    /// </summary>
    public TerraformProperty<bool> DisableAuth
    {
        get => GetRequiredOutput<TerraformProperty<bool>>("disable_auth");
        set => SetProperty("disable_auth", value);
    }

    /// <summary>
    /// Human friendly display name of the tenant.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "DisplayName is required")]
    public required TerraformProperty<string> DisplayName
    {
        get => GetRequiredOutput<TerraformProperty<string>>("display_name");
        set => SetProperty("display_name", value);
    }

    /// <summary>
    /// Whether to enable email link user authentication.
    /// </summary>
    public TerraformProperty<bool> EnableEmailLinkSignin
    {
        get => GetRequiredOutput<TerraformProperty<bool>>("enable_email_link_signin");
        set => SetProperty("enable_email_link_signin", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformProperty<string> Id
    {
        get => GetRequiredOutput<TerraformProperty<string>>("id");
        set => SetProperty("id", value);
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public TerraformProperty<string> Project
    {
        get => GetRequiredOutput<TerraformProperty<string>>("project");
        set => SetProperty("project", value);
    }

    /// <summary>
    /// Block for client.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 Client block(s) allowed")]
    public List<GoogleIdentityPlatformTenantClientBlock>? Client
    {
        set => SetProperty("client", value);
    }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    public GoogleIdentityPlatformTenantTimeoutsBlock? Timeouts
    {
        set => SetProperty("timeouts", value);
    }

    /// <summary>
    /// The name of the tenant that is generated by the server
    /// </summary>
    public TerraformExpression Name => this["name"];

}
