using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GooglePublicCaExternalAccountKeyTimeoutsBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    [TerraformPropertyName("create")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Create { get; set; }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    [TerraformPropertyName("delete")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Delete { get; set; }

}

/// <summary>
/// Manages a google_public_ca_external_account_key resource.
/// </summary>
public class GooglePublicCaExternalAccountKey : TerraformResource
{
    public GooglePublicCaExternalAccountKey(string name) : base("google_public_ca_external_account_key", name)
    {
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    [TerraformPropertyName("id")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Id { get; set; } = default!;

    /// <summary>
    /// Location for the externalAccountKey. Currently only &#39;global&#39; is supported.
    /// </summary>
    [TerraformPropertyName("location")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Location { get; set; }

    /// <summary>
    /// The project attribute.
    /// </summary>
    [TerraformPropertyName("project")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Project { get; set; } = default!;

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    [TerraformPropertyName("timeouts")]
    public TerraformBlock<GooglePublicCaExternalAccountKeyTimeoutsBlock>? Timeouts { get; set; }

    /// <summary>
    /// Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService
    /// when the ExternalAccountKey is created.
    /// </summary>
    [TerraformPropertyName("b64_mac_key")]
    // Output-only attribute - read-only reference
    public TerraformValue<string> B64MacKey => new TerraformReference(this, "b64_mac_key");

    /// <summary>
    /// Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService
    /// when the ExternalAccountKey is created.&#39;
    /// </summary>
    [TerraformPropertyName("b64url_mac_key")]
    // Output-only attribute - read-only reference
    public TerraformValue<string> B64urlMacKey => new TerraformReference(this, "b64url_mac_key");

    /// <summary>
    /// It is generated by the PublicCertificateAuthorityService when the ExternalAccountKey is created.
    /// </summary>
    [TerraformPropertyName("key_id")]
    // Output-only attribute - read-only reference
    public TerraformValue<string> KeyId => new TerraformReference(this, "key_id");

    /// <summary>
    /// Resource name. projects/{project}/locations/{location}/externalAccountKeys/{keyId}.
    /// </summary>
    [TerraformPropertyName("name")]
    // Output-only attribute - read-only reference
    public TerraformValue<string> Name => new TerraformReference(this, "name");

}
