using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public partial class GooglePublicCaExternalAccountKeyTimeoutsBlock : TerraformBlockBase
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    [TerraformProperty("create")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? Create { get; set; }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    [TerraformProperty("delete")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? Delete { get; set; }

}

/// <summary>
/// Manages a google_public_ca_external_account_key resource.
/// </summary>
public partial class GooglePublicCaExternalAccountKey : TerraformResource
{
    public GooglePublicCaExternalAccountKey(string name) : base("google_public_ca_external_account_key", name)
    {
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    [TerraformProperty("id")]
    // Optional+Computed - source generator will implement get/set
    public TerraformValue<string> Id { get; set; }

    /// <summary>
    /// Location for the externalAccountKey. Currently only &#39;global&#39; is supported.
    /// </summary>
    [TerraformProperty("location")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? Location { get; set; }

    /// <summary>
    /// The project attribute.
    /// </summary>
    [TerraformProperty("project")]
    // Optional+Computed - source generator will implement get/set
    public TerraformValue<string> Project { get; set; }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    [TerraformProperty("timeouts")]
    public TerraformBlock<GooglePublicCaExternalAccountKeyTimeoutsBlock>? Timeouts { get; set; }

    /// <summary>
    /// Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService
    /// when the ExternalAccountKey is created.
    /// </summary>
    [TerraformProperty("b64_mac_key")]
    // Output-only attribute - source generator will implement read-only get
    public TerraformValue<string> B64MacKey { get; }

    /// <summary>
    /// Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService
    /// when the ExternalAccountKey is created.&#39;
    /// </summary>
    [TerraformProperty("b64url_mac_key")]
    // Output-only attribute - source generator will implement read-only get
    public TerraformValue<string> B64urlMacKey { get; }

    /// <summary>
    /// It is generated by the PublicCertificateAuthorityService when the ExternalAccountKey is created.
    /// </summary>
    [TerraformProperty("key_id")]
    // Output-only attribute - source generator will implement read-only get
    public TerraformValue<string> KeyId { get; }

    /// <summary>
    /// Resource name. projects/{project}/locations/{location}/externalAccountKeys/{keyId}.
    /// </summary>
    [TerraformProperty("name")]
    // Output-only attribute - source generator will implement read-only get
    public TerraformValue<string> Name { get; }

}
