using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for log_config in GoogleNetworkServicesWasmPlugin.
/// Nesting mode: list
/// </summary>
public class GoogleNetworkServicesWasmPluginLogConfigBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "log_config";

    /// <summary>
    /// Optional. Specifies whether to enable logging for activity by this plugin.
    /// </summary>
    public TerraformValue<bool>? Enable
    {
        get => new TerraformReference<bool>(this, "enable");
        set => SetArgument("enable", value);
    }

    /// <summary>
    /// Non-empty default. Specificies the lowest level of the plugin logs that are exported to Cloud Logging. This setting relates to the logs generated by using logging statements in your Wasm code.
    /// This field is can be set only if logging is enabled for the plugin.
    /// If the field is not provided when logging is enabled, it is set to INFO by default. Possible values: [&amp;quot;LOG_LEVEL_UNSPECIFIED&amp;quot;, &amp;quot;TRACE&amp;quot;, &amp;quot;DEBUG&amp;quot;, &amp;quot;INFO&amp;quot;, &amp;quot;WARN&amp;quot;, &amp;quot;ERROR&amp;quot;, &amp;quot;CRITICAL&amp;quot;]
    /// </summary>
    public TerraformValue<string> MinLogLevel
    {
        get => new TerraformReference<string>(this, "min_log_level");
        set => SetArgument("min_log_level", value);
    }

    /// <summary>
    /// Non-empty default. Configures the sampling rate of activity logs, where 1.0 means all logged activity is reported and 0.0 means no activity is reported.
    /// A floating point value between 0.0 and 1.0 indicates that a percentage of log messages is stored.
    /// The default value when logging is enabled is 1.0. The value of the field must be between 0 and 1 (inclusive).
    /// This field can be specified only if logging is enabled for this plugin.
    /// </summary>
    public TerraformValue<double> SampleRate
    {
        get => new TerraformReference<double>(this, "sample_rate");
        set => SetArgument("sample_rate", value);
    }

}


/// <summary>
/// Block type for timeouts in GoogleNetworkServicesWasmPlugin.
/// Nesting mode: single
/// </summary>
public class GoogleNetworkServicesWasmPluginTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "timeouts";

    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformValue<string>? Create
    {
        get => new TerraformReference<string>(this, "create");
        set => SetArgument("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformValue<string>? Delete
    {
        get => new TerraformReference<string>(this, "delete");
        set => SetArgument("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformValue<string>? Update
    {
        get => new TerraformReference<string>(this, "update");
        set => SetArgument("update", value);
    }

}


/// <summary>
/// Block type for versions in GoogleNetworkServicesWasmPlugin.
/// Nesting mode: set
/// </summary>
public class GoogleNetworkServicesWasmPluginVersionsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "versions";

    /// <summary>
    /// Output only. The timestamp when the resource was created.
    /// </summary>
    public TerraformValue<string> CreateTime
    {
        get => new TerraformReference<string>(this, "create_time");
    }

    /// <summary>
    /// Optional. A human-readable description of the resource.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => new TerraformReference<string>(this, "description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// Output only. The resolved digest for the image specified in the image field. The digest is resolved during the creation of WasmPluginVersion resource.
    /// This field holds the digest value, regardless of whether a tag or digest was originally specified in the image field.
    /// </summary>
    public TerraformValue<string> ImageDigest
    {
        get => new TerraformReference<string>(this, "image_digest");
    }

    /// <summary>
    /// Optional. URI of the container image containing the plugin, stored in the Artifact Registry. When a new WasmPluginVersion resource is created, the digest of the container image is saved in the imageDigest field.
    /// When downloading an image, the digest value is used instead of an image tag.
    /// </summary>
    public TerraformValue<string>? ImageUri
    {
        get => new TerraformReference<string>(this, "image_uri");
        set => SetArgument("image_uri", value);
    }

    /// <summary>
    /// Optional. Set of labels associated with the WasmPlugin resource.
    /// </summary>
    public TerraformMap<string>? Labels
    {
        get => TerraformMap<string>.Lazy(ctx => new TerraformReference<TerraformMap<string>>(this, "labels").ResolveNodes(ctx));
        set => SetArgument("labels", value);
    }

    /// <summary>
    /// A base64-encoded string containing the configuration for the plugin. The configuration is provided to the plugin at runtime through the ON_CONFIGURE callback.
    /// When a new WasmPluginVersion resource is created, the digest of the contents is saved in the pluginConfigDigest field.
    /// Conflics with pluginConfigUri.
    /// </summary>
    public TerraformValue<string>? PluginConfigData
    {
        get => new TerraformReference<string>(this, "plugin_config_data");
        set => SetArgument("plugin_config_data", value);
    }

    /// <summary>
    /// Output only. This field holds the digest (usually checksum) value for the plugin configuration.
    /// The value is calculated based on the contents of pluginConfigData or the container image defined by the pluginConfigUri field.
    /// </summary>
    public TerraformValue<string> PluginConfigDigest
    {
        get => new TerraformReference<string>(this, "plugin_config_digest");
    }

    /// <summary>
    /// URI of the plugin configuration stored in the Artifact Registry. The configuration is provided to the plugin at runtime through the ON_CONFIGURE callback.
    /// The container image must contain only a single file with the name plugin.config.
    /// When a new WasmPluginVersion resource is created, the digest of the container image is saved in the pluginConfigDigest field.
    /// Conflics with pluginConfigData.
    /// </summary>
    public TerraformValue<string>? PluginConfigUri
    {
        get => new TerraformReference<string>(this, "plugin_config_uri");
        set => SetArgument("plugin_config_uri", value);
    }

    /// <summary>
    /// Output only. The timestamp when the resource was updated.
    /// </summary>
    public TerraformValue<string> UpdateTime
    {
        get => new TerraformReference<string>(this, "update_time");
    }

    /// <summary>
    /// The version_name attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "VersionName is required")]
    public required TerraformValue<string> VersionName
    {
        get => new TerraformReference<string>(this, "version_name");
        set => SetArgument("version_name", value);
    }

}


/// <summary>
/// Represents a google_network_services_wasm_plugin Terraform resource.
/// Manages a google_network_services_wasm_plugin resource.
/// </summary>
public partial class GoogleNetworkServicesWasmPlugin(string name) : TerraformResource("google_network_services_wasm_plugin", name)
{
    /// <summary>
    /// Optional. A human-readable description of the resource.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => new TerraformReference<string>(this, "description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformValue<string> Id
    {
        get => new TerraformReference<string>(this, "id");
        set => SetArgument("id", value);
    }

    /// <summary>
    /// Optional. Set of labels associated with the WasmPlugin resource.
    /// 
    /// **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
    /// Please refer to the field &#39;effective_labels&#39; for all of the labels present on the resource.
    /// </summary>
    public TerraformMap<string>? Labels
    {
        get => TerraformMap<string>.Lazy(ctx => new TerraformReference<TerraformMap<string>>(this, "labels").ResolveNodes(ctx));
        set => SetArgument("labels", value);
    }

    /// <summary>
    /// The location of the traffic extension
    /// </summary>
    public TerraformValue<string>? Location
    {
        get => new TerraformReference<string>(this, "location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// The ID of the WasmPluginVersion resource that is the currently serving one. The version referred to must be a child of this WasmPlugin resource and should be listed in the &amp;quot;versions&amp;quot; field.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "MainVersionId is required")]
    public required TerraformValue<string> MainVersionId
    {
        get => new TerraformReference<string>(this, "main_version_id");
        set => SetArgument("main_version_id", value);
    }

    /// <summary>
    /// Identifier. Name of the WasmPlugin resource.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    public required TerraformValue<string> Name
    {
        get => new TerraformReference<string>(this, "name");
        set => SetArgument("name", value);
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public TerraformValue<string> Project
    {
        get => new TerraformReference<string>(this, "project");
        set => SetArgument("project", value);
    }

    /// <summary>
    /// Output only. The timestamp when the resource was created.
    /// </summary>
    public TerraformValue<string> CreateTime
    {
        get => new TerraformReference<string>(this, "create_time");
    }

    /// <summary>
    /// All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.
    /// </summary>
    public TerraformMap<string> EffectiveLabels
    {
        get => TerraformMap<string>.Lazy(ctx => new TerraformReference<TerraformMap<string>>(this, "effective_labels").ResolveNodes(ctx));
    }

    /// <summary>
    /// The combination of labels configured directly on the resource
    ///  and default labels configured on the provider.
    /// </summary>
    public TerraformMap<string> TerraformLabels
    {
        get => TerraformMap<string>.Lazy(ctx => new TerraformReference<TerraformMap<string>>(this, "terraform_labels").ResolveNodes(ctx));
    }

    /// <summary>
    /// Output only. The timestamp when the resource was updated.
    /// </summary>
    public TerraformValue<string> UpdateTime
    {
        get => new TerraformReference<string>(this, "update_time");
    }

    /// <summary>
    /// Output only. List of all extensions that use this WasmPlugin resource.
    /// </summary>
    public TerraformList<TerraformMap<object>> UsedBy
    {
        get => TerraformList<TerraformMap<object>>.Lazy(ctx => new TerraformReference<TerraformList<TerraformMap<object>>>(this, "used_by").ResolveNodes(ctx));
    }

    /// <summary>
    /// LogConfig block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 LogConfig block(s) allowed")]
    public TerraformList<GoogleNetworkServicesWasmPluginLogConfigBlock>? LogConfig
    {
        get => GetArgument<TerraformList<GoogleNetworkServicesWasmPluginLogConfigBlock>>("log_config");
        set => SetArgument("log_config", value);
    }

    /// <summary>
    /// Timeouts block (nesting mode: single).
    /// </summary>
    public GoogleNetworkServicesWasmPluginTimeoutsBlock? Timeouts
    {
        get => GetArgument<GoogleNetworkServicesWasmPluginTimeoutsBlock>("timeouts");
        set => SetArgument("timeouts", value);
    }

    /// <summary>
    /// Versions block (nesting mode: set).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Versions is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 Versions block(s) required")]
    public required TerraformSet<GoogleNetworkServicesWasmPluginVersionsBlock> Versions
    {
        get => GetRequiredArgument<TerraformSet<GoogleNetworkServicesWasmPluginVersionsBlock>>("versions");
        set => SetArgument("versions", value);
    }

}
