using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for custom_config in GoogleSccManagementFolderSecurityHealthAnalyticsCustomModule.
/// Nesting mode: list
/// </summary>
public class GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "custom_config";

    /// <summary>
    /// Text that describes the vulnerability or misconfiguration that the custom
    /// module detects. This explanation is returned with each finding instance to
    /// help investigators understand the detected issue. The text must be enclosed in quotation marks.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => GetArgument<TerraformValue<string>>("description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// An explanation of the recommended steps that security teams can take to resolve
    /// the detected issue. This explanation is returned with each finding generated by
    /// this module in the nextSteps property of the finding JSON.
    /// </summary>
    public TerraformValue<string>? Recommendation
    {
        get => GetArgument<TerraformValue<string>>("recommendation");
        set => SetArgument("recommendation", value);
    }

    /// <summary>
    /// The severity to assign to findings generated by the module. Possible values: [&amp;quot;CRITICAL&amp;quot;, &amp;quot;HIGH&amp;quot;, &amp;quot;MEDIUM&amp;quot;, &amp;quot;LOW&amp;quot;]
    /// </summary>
    public TerraformValue<string>? Severity
    {
        get => GetArgument<TerraformValue<string>>("severity");
        set => SetArgument("severity", value);
    }

    /// <summary>
    /// CustomOutput block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 CustomOutput block(s) allowed")]
    public TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlock>? CustomOutput
    {
        get => GetArgument<TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlock>>("custom_output");
        set => SetArgument("custom_output", value);
    }

    /// <summary>
    /// Predicate block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 Predicate block(s) allowed")]
    public TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockPredicateBlock>? Predicate
    {
        get => GetArgument<TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockPredicateBlock>>("predicate");
        set => SetArgument("predicate", value);
    }

    /// <summary>
    /// ResourceSelector block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ResourceSelector block(s) allowed")]
    public TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockResourceSelectorBlock>? ResourceSelector
    {
        get => GetArgument<TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockResourceSelectorBlock>>("resource_selector");
        set => SetArgument("resource_selector", value);
    }

}

/// <summary>
/// Block type for custom_output in GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "custom_output";

    /// <summary>
    /// Properties block (nesting mode: list).
    /// </summary>
    public TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock>? Properties
    {
        get => GetArgument<TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock>>("properties");
        set => SetArgument("properties", value);
    }

}

/// <summary>
/// Block type for properties in GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "properties";

    /// <summary>
    /// Name of the property for the custom output.
    /// </summary>
    public TerraformValue<string>? Name
    {
        get => GetArgument<TerraformValue<string>>("name");
        set => SetArgument("name", value);
    }

    /// <summary>
    /// ValueExpression block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ValueExpression block(s) allowed")]
    public TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlockValueExpressionBlock>? ValueExpression
    {
        get => GetArgument<TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlockValueExpressionBlock>>("value_expression");
        set => SetArgument("value_expression", value);
    }

}

/// <summary>
/// Block type for value_expression in GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlockValueExpressionBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "value_expression";

    /// <summary>
    /// Description of the expression. This is a longer text which describes the
    /// expression, e.g. when hovered over it in a UI.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => GetArgument<TerraformValue<string>>("description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// Textual representation of an expression in Common Expression Language syntax.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Expression is required")]
    public required TerraformValue<string> Expression
    {
        get => GetArgument<TerraformValue<string>>("expression");
        set => SetArgument("expression", value);
    }

    /// <summary>
    /// String indicating the location of the expression for error reporting, e.g. a
    /// file name and a position in the file.
    /// </summary>
    public TerraformValue<string>? Location
    {
        get => GetArgument<TerraformValue<string>>("location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// Title for the expression, i.e. a short string describing its purpose. This can
    /// be used e.g. in UIs which allow to enter the expression.
    /// </summary>
    public TerraformValue<string>? Title
    {
        get => GetArgument<TerraformValue<string>>("title");
        set => SetArgument("title", value);
    }

}

/// <summary>
/// Block type for predicate in GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockPredicateBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "predicate";

    /// <summary>
    /// Description of the expression. This is a longer text which describes the
    /// expression, e.g. when hovered over it in a UI.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => GetArgument<TerraformValue<string>>("description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// Textual representation of an expression in Common Expression Language syntax.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Expression is required")]
    public required TerraformValue<string> Expression
    {
        get => GetArgument<TerraformValue<string>>("expression");
        set => SetArgument("expression", value);
    }

    /// <summary>
    /// String indicating the location of the expression for error reporting, e.g. a
    /// file name and a position in the file.
    /// </summary>
    public TerraformValue<string>? Location
    {
        get => GetArgument<TerraformValue<string>>("location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// Title for the expression, i.e. a short string describing its purpose. This can
    /// be used e.g. in UIs which allow to enter the expression.
    /// </summary>
    public TerraformValue<string>? Title
    {
        get => GetArgument<TerraformValue<string>>("title");
        set => SetArgument("title", value);
    }

}

/// <summary>
/// Block type for resource_selector in GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlockResourceSelectorBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "resource_selector";

    /// <summary>
    /// The resource types to run the detector on.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ResourceTypes is required")]
    public TerraformList<string>? ResourceTypes
    {
        get => GetArgument<TerraformList<string>>("resource_types");
        set => SetArgument("resource_types", value);
    }

}


/// <summary>
/// Block type for timeouts in GoogleSccManagementFolderSecurityHealthAnalyticsCustomModule.
/// Nesting mode: single
/// </summary>
public class GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "timeouts";

    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformValue<string>? Create
    {
        get => GetArgument<TerraformValue<string>>("create");
        set => SetArgument("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformValue<string>? Delete
    {
        get => GetArgument<TerraformValue<string>>("delete");
        set => SetArgument("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformValue<string>? Update
    {
        get => GetArgument<TerraformValue<string>>("update");
        set => SetArgument("update", value);
    }

}


/// <summary>
/// Represents a google_scc_management_folder_security_health_analytics_custom_module Terraform resource.
/// Manages a google_scc_management_folder_security_health_analytics_custom_module resource.
/// </summary>
public partial class GoogleSccManagementFolderSecurityHealthAnalyticsCustomModule(string name) : TerraformResource("google_scc_management_folder_security_health_analytics_custom_module", name)
{
    /// <summary>
    /// The display name of the Security Health Analytics custom module. This
    /// display name becomes the finding category for all findings that are
    /// returned by this custom module. The display name must be between 1 and
    /// 128 characters, start with a lowercase letter, and contain alphanumeric
    /// characters or underscores only.
    /// </summary>
    public TerraformValue<string>? DisplayName
    {
        get => GetArgument<TerraformValue<string>>("display_name");
        set => SetArgument("display_name", value);
    }

    /// <summary>
    /// The enablement state of the custom module. Possible values: [&amp;quot;ENABLED&amp;quot;, &amp;quot;DISABLED&amp;quot;]
    /// </summary>
    public TerraformValue<string>? EnablementState
    {
        get => GetArgument<TerraformValue<string>>("enablement_state");
        set => SetArgument("enablement_state", value);
    }

    /// <summary>
    /// Numerical ID of the parent folder.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Folder is required")]
    public required TerraformValue<string> Folder
    {
        get => GetArgument<TerraformValue<string>>("folder");
        set => SetArgument("folder", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformValue<string>? Id
    {
        get => GetArgument<TerraformValue<string>>("id");
        set => SetArgument("id", value);
    }

    /// <summary>
    /// Location ID of the parent organization. If not provided, &#39;global&#39; will be used as the default location.
    /// </summary>
    public TerraformValue<string>? Location
    {
        get => GetArgument<TerraformValue<string>>("location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// If empty, indicates that the custom module was created in the organization, folder,
    /// or project in which you are viewing the custom module. Otherwise, ancestor_module
    /// specifies the organization or folder from which the custom module is inherited.
    /// </summary>
    public TerraformValue<string> AncestorModule
        => AsReference("ancestor_module");

    /// <summary>
    /// The editor that last updated the custom module.
    /// </summary>
    public TerraformValue<string> LastEditor
        => AsReference("last_editor");

    /// <summary>
    /// The resource name of the custom module. Its format is &amp;quot;folders/{folder}/locations/{location}/securityHealthAnalyticsCustomModules/{securityHealthAnalyticsCustomModule}&amp;quot;.
    /// The id {securityHealthAnalyticsCustomModule} is server-generated and is not user settable. It will be a numeric id containing 1-20 digits.
    /// </summary>
    public TerraformValue<string> Name
        => AsReference("name");

    /// <summary>
    /// The time at which the custom module was last updated.
    /// 
    /// A timestamp in RFC3339 UTC &amp;quot;Zulu&amp;quot; format, with nanosecond resolution and
    /// up to nine fractional digits. Examples: &amp;quot;2014-10-02T15:01:23Z&amp;quot; and &amp;quot;2014-10-02T15:01:23.045123456Z&amp;quot;.
    /// </summary>
    public TerraformValue<string> UpdateTime
        => AsReference("update_time");

    /// <summary>
    /// CustomConfig block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 CustomConfig block(s) allowed")]
    public TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlock>? CustomConfig
    {
        get => GetArgument<TerraformList<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleCustomConfigBlock>>("custom_config");
        set => SetArgument("custom_config", value);
    }

    /// <summary>
    /// Timeouts block (nesting mode: single).
    /// </summary>
    public GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleTimeoutsBlock? Timeouts
    {
        get => GetArgument<GoogleSccManagementFolderSecurityHealthAnalyticsCustomModuleTimeoutsBlock>("timeouts");
        set => SetArgument("timeouts", value);
    }

}
