using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for custom_config in GoogleSccFolderCustomModule.
/// Nesting mode: list
/// </summary>
public class GoogleSccFolderCustomModuleCustomConfigBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "custom_config";

    /// <summary>
    /// Text that describes the vulnerability or misconfiguration that the custom
    /// module detects. This explanation is returned with each finding instance to
    /// help investigators understand the detected issue. The text must be enclosed in quotation marks.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => new TerraformReference<string>(this, "description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// An explanation of the recommended steps that security teams can take to resolve
    /// the detected issue. This explanation is returned with each finding generated by
    /// this module in the nextSteps property of the finding JSON.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Recommendation is required")]
    public required TerraformValue<string> Recommendation
    {
        get => new TerraformReference<string>(this, "recommendation");
        set => SetArgument("recommendation", value);
    }

    /// <summary>
    /// The severity to assign to findings generated by the module. Possible values: [&amp;quot;CRITICAL&amp;quot;, &amp;quot;HIGH&amp;quot;, &amp;quot;MEDIUM&amp;quot;, &amp;quot;LOW&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Severity is required")]
    public required TerraformValue<string> Severity
    {
        get => new TerraformReference<string>(this, "severity");
        set => SetArgument("severity", value);
    }

    /// <summary>
    /// CustomOutput block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 CustomOutput block(s) allowed")]
    public TerraformList<GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlock>? CustomOutput
    {
        get => GetArgument<TerraformList<GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlock>>("custom_output");
        set => SetArgument("custom_output", value);
    }

    /// <summary>
    /// Predicate block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Predicate is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 Predicate block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 Predicate block(s) allowed")]
    public required TerraformList<GoogleSccFolderCustomModuleCustomConfigBlockPredicateBlock> Predicate
    {
        get => GetRequiredArgument<TerraformList<GoogleSccFolderCustomModuleCustomConfigBlockPredicateBlock>>("predicate");
        set => SetArgument("predicate", value);
    }

    /// <summary>
    /// ResourceSelector block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ResourceSelector is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 ResourceSelector block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ResourceSelector block(s) allowed")]
    public required TerraformList<GoogleSccFolderCustomModuleCustomConfigBlockResourceSelectorBlock> ResourceSelector
    {
        get => GetRequiredArgument<TerraformList<GoogleSccFolderCustomModuleCustomConfigBlockResourceSelectorBlock>>("resource_selector");
        set => SetArgument("resource_selector", value);
    }

}

/// <summary>
/// Block type for custom_output in GoogleSccFolderCustomModuleCustomConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "custom_output";

    /// <summary>
    /// Properties block (nesting mode: list).
    /// </summary>
    public TerraformList<GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock>? Properties
    {
        get => GetArgument<TerraformList<GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock>>("properties");
        set => SetArgument("properties", value);
    }

}

/// <summary>
/// Block type for properties in GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "properties";

    /// <summary>
    /// Name of the property for the custom output.
    /// </summary>
    public TerraformValue<string>? Name
    {
        get => new TerraformReference<string>(this, "name");
        set => SetArgument("name", value);
    }

    /// <summary>
    /// ValueExpression block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ValueExpression block(s) allowed")]
    public TerraformList<GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlockValueExpressionBlock>? ValueExpression
    {
        get => GetArgument<TerraformList<GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlockValueExpressionBlock>>("value_expression");
        set => SetArgument("value_expression", value);
    }

}

/// <summary>
/// Block type for value_expression in GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccFolderCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlockValueExpressionBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "value_expression";

    /// <summary>
    /// Description of the expression. This is a longer text which describes the
    /// expression, e.g. when hovered over it in a UI.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => new TerraformReference<string>(this, "description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// Textual representation of an expression in Common Expression Language syntax.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Expression is required")]
    public required TerraformValue<string> Expression
    {
        get => new TerraformReference<string>(this, "expression");
        set => SetArgument("expression", value);
    }

    /// <summary>
    /// String indicating the location of the expression for error reporting, e.g. a
    /// file name and a position in the file.
    /// </summary>
    public TerraformValue<string>? Location
    {
        get => new TerraformReference<string>(this, "location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// Title for the expression, i.e. a short string describing its purpose. This can
    /// be used e.g. in UIs which allow to enter the expression.
    /// </summary>
    public TerraformValue<string>? Title
    {
        get => new TerraformReference<string>(this, "title");
        set => SetArgument("title", value);
    }

}

/// <summary>
/// Block type for predicate in GoogleSccFolderCustomModuleCustomConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccFolderCustomModuleCustomConfigBlockPredicateBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "predicate";

    /// <summary>
    /// Description of the expression. This is a longer text which describes the
    /// expression, e.g. when hovered over it in a UI.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => new TerraformReference<string>(this, "description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// Textual representation of an expression in Common Expression Language syntax.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Expression is required")]
    public required TerraformValue<string> Expression
    {
        get => new TerraformReference<string>(this, "expression");
        set => SetArgument("expression", value);
    }

    /// <summary>
    /// String indicating the location of the expression for error reporting, e.g. a
    /// file name and a position in the file.
    /// </summary>
    public TerraformValue<string>? Location
    {
        get => new TerraformReference<string>(this, "location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// Title for the expression, i.e. a short string describing its purpose. This can
    /// be used e.g. in UIs which allow to enter the expression.
    /// </summary>
    public TerraformValue<string>? Title
    {
        get => new TerraformReference<string>(this, "title");
        set => SetArgument("title", value);
    }

}

/// <summary>
/// Block type for resource_selector in GoogleSccFolderCustomModuleCustomConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccFolderCustomModuleCustomConfigBlockResourceSelectorBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "resource_selector";

    /// <summary>
    /// The resource types to run the detector on.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ResourceTypes is required")]
    public TerraformList<string>? ResourceTypes
    {
        get => TerraformList<string>.Lazy(ctx => new TerraformReference<TerraformList<string>>(this, "resource_types").ResolveNodes(ctx));
        set => SetArgument("resource_types", value);
    }

}


/// <summary>
/// Block type for timeouts in GoogleSccFolderCustomModule.
/// Nesting mode: single
/// </summary>
public class GoogleSccFolderCustomModuleTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "timeouts";

    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformValue<string>? Create
    {
        get => new TerraformReference<string>(this, "create");
        set => SetArgument("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformValue<string>? Delete
    {
        get => new TerraformReference<string>(this, "delete");
        set => SetArgument("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformValue<string>? Update
    {
        get => new TerraformReference<string>(this, "update");
        set => SetArgument("update", value);
    }

}


/// <summary>
/// Represents a google_scc_folder_custom_module Terraform resource.
/// Manages a google_scc_folder_custom_module resource.
/// </summary>
public partial class GoogleSccFolderCustomModule(string name) : TerraformResource("google_scc_folder_custom_module", name)
{
    /// <summary>
    /// The display name of the Security Health Analytics custom module. This
    /// display name becomes the finding category for all findings that are
    /// returned by this custom module. The display name must be between 1 and
    /// 128 characters, start with a lowercase letter, and contain alphanumeric
    /// characters or underscores only.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "DisplayName is required")]
    public required TerraformValue<string> DisplayName
    {
        get => new TerraformReference<string>(this, "display_name");
        set => SetArgument("display_name", value);
    }

    /// <summary>
    /// The enablement state of the custom module. Possible values: [&amp;quot;ENABLED&amp;quot;, &amp;quot;DISABLED&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "EnablementState is required")]
    public required TerraformValue<string> EnablementState
    {
        get => new TerraformReference<string>(this, "enablement_state");
        set => SetArgument("enablement_state", value);
    }

    /// <summary>
    /// Numerical ID of the parent folder.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Folder is required")]
    public required TerraformValue<string> Folder
    {
        get => new TerraformReference<string>(this, "folder");
        set => SetArgument("folder", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformValue<string> Id
    {
        get => new TerraformReference<string>(this, "id");
        set => SetArgument("id", value);
    }

    /// <summary>
    /// If empty, indicates that the custom module was created in the organization, folder,
    /// or project in which you are viewing the custom module. Otherwise, ancestor_module
    /// specifies the organization or folder from which the custom module is inherited.
    /// </summary>
    public TerraformValue<string> AncestorModule
    {
        get => new TerraformReference<string>(this, "ancestor_module");
    }

    /// <summary>
    /// The editor that last updated the custom module.
    /// </summary>
    public TerraformValue<string> LastEditor
    {
        get => new TerraformReference<string>(this, "last_editor");
    }

    /// <summary>
    /// The resource name of the custom module. Its format is &amp;quot;folders/{folder_id}/securityHealthAnalyticsSettings/customModules/{customModule}&amp;quot;.
    /// The id {customModule} is server-generated and is not user settable. It will be a numeric id containing 1-20 digits.
    /// </summary>
    public TerraformValue<string> Name
    {
        get => new TerraformReference<string>(this, "name");
    }

    /// <summary>
    /// The time at which the custom module was last updated.
    /// 
    /// A timestamp in RFC3339 UTC &amp;quot;Zulu&amp;quot; format, with nanosecond resolution and
    /// up to nine fractional digits. Examples: &amp;quot;2014-10-02T15:01:23Z&amp;quot; and &amp;quot;2014-10-02T15:01:23.045123456Z&amp;quot;.
    /// </summary>
    public TerraformValue<string> UpdateTime
    {
        get => new TerraformReference<string>(this, "update_time");
    }

    /// <summary>
    /// CustomConfig block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "CustomConfig is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 CustomConfig block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 CustomConfig block(s) allowed")]
    public required TerraformList<GoogleSccFolderCustomModuleCustomConfigBlock> CustomConfig
    {
        get => GetRequiredArgument<TerraformList<GoogleSccFolderCustomModuleCustomConfigBlock>>("custom_config");
        set => SetArgument("custom_config", value);
    }

    /// <summary>
    /// Timeouts block (nesting mode: single).
    /// </summary>
    public GoogleSccFolderCustomModuleTimeoutsBlock? Timeouts
    {
        get => GetArgument<GoogleSccFolderCustomModuleTimeoutsBlock>("timeouts");
        set => SetArgument("timeouts", value);
    }

}
