using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for custom_config in GoogleSccProjectCustomModule.
/// Nesting mode: list
/// </summary>
public class GoogleSccProjectCustomModuleCustomConfigBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "custom_config";

    /// <summary>
    /// Text that describes the vulnerability or misconfiguration that the custom
    /// module detects. This explanation is returned with each finding instance to
    /// help investigators understand the detected issue. The text must be enclosed in quotation marks.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => GetArgument<TerraformValue<string>>("description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// An explanation of the recommended steps that security teams can take to resolve
    /// the detected issue. This explanation is returned with each finding generated by
    /// this module in the nextSteps property of the finding JSON.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Recommendation is required")]
    public required TerraformValue<string> Recommendation
    {
        get => GetRequiredArgument<TerraformValue<string>>("recommendation");
        set => SetArgument("recommendation", value);
    }

    /// <summary>
    /// The severity to assign to findings generated by the module. Possible values: [&amp;quot;CRITICAL&amp;quot;, &amp;quot;HIGH&amp;quot;, &amp;quot;MEDIUM&amp;quot;, &amp;quot;LOW&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Severity is required")]
    public required TerraformValue<string> Severity
    {
        get => GetRequiredArgument<TerraformValue<string>>("severity");
        set => SetArgument("severity", value);
    }

    /// <summary>
    /// CustomOutput block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 CustomOutput block(s) allowed")]
    public TerraformList<GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlock>? CustomOutput
    {
        get => GetArgument<TerraformList<GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlock>>("custom_output");
        set => SetArgument("custom_output", value);
    }

    /// <summary>
    /// Predicate block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Predicate is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 Predicate block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 Predicate block(s) allowed")]
    public required TerraformList<GoogleSccProjectCustomModuleCustomConfigBlockPredicateBlock> Predicate
    {
        get => GetRequiredArgument<TerraformList<GoogleSccProjectCustomModuleCustomConfigBlockPredicateBlock>>("predicate");
        set => SetArgument("predicate", value);
    }

    /// <summary>
    /// ResourceSelector block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ResourceSelector is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 ResourceSelector block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ResourceSelector block(s) allowed")]
    public required TerraformList<GoogleSccProjectCustomModuleCustomConfigBlockResourceSelectorBlock> ResourceSelector
    {
        get => GetRequiredArgument<TerraformList<GoogleSccProjectCustomModuleCustomConfigBlockResourceSelectorBlock>>("resource_selector");
        set => SetArgument("resource_selector", value);
    }

}

/// <summary>
/// Block type for custom_output in GoogleSccProjectCustomModuleCustomConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "custom_output";

    /// <summary>
    /// Properties block (nesting mode: list).
    /// </summary>
    public TerraformList<GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock>? Properties
    {
        get => GetArgument<TerraformList<GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock>>("properties");
        set => SetArgument("properties", value);
    }

}

/// <summary>
/// Block type for properties in GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "properties";

    /// <summary>
    /// Name of the property for the custom output.
    /// </summary>
    public TerraformValue<string>? Name
    {
        get => GetArgument<TerraformValue<string>>("name");
        set => SetArgument("name", value);
    }

    /// <summary>
    /// ValueExpression block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ValueExpression block(s) allowed")]
    public TerraformList<GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlockValueExpressionBlock>? ValueExpression
    {
        get => GetArgument<TerraformList<GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlockValueExpressionBlock>>("value_expression");
        set => SetArgument("value_expression", value);
    }

}

/// <summary>
/// Block type for value_expression in GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccProjectCustomModuleCustomConfigBlockCustomOutputBlockPropertiesBlockValueExpressionBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "value_expression";

    /// <summary>
    /// Description of the expression. This is a longer text which describes the
    /// expression, e.g. when hovered over it in a UI.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => GetArgument<TerraformValue<string>>("description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// Textual representation of an expression in Common Expression Language syntax.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Expression is required")]
    public required TerraformValue<string> Expression
    {
        get => GetRequiredArgument<TerraformValue<string>>("expression");
        set => SetArgument("expression", value);
    }

    /// <summary>
    /// String indicating the location of the expression for error reporting, e.g. a
    /// file name and a position in the file.
    /// </summary>
    public TerraformValue<string>? Location
    {
        get => GetArgument<TerraformValue<string>>("location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// Title for the expression, i.e. a short string describing its purpose. This can
    /// be used e.g. in UIs which allow to enter the expression.
    /// </summary>
    public TerraformValue<string>? Title
    {
        get => GetArgument<TerraformValue<string>>("title");
        set => SetArgument("title", value);
    }

}

/// <summary>
/// Block type for predicate in GoogleSccProjectCustomModuleCustomConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccProjectCustomModuleCustomConfigBlockPredicateBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "predicate";

    /// <summary>
    /// Description of the expression. This is a longer text which describes the
    /// expression, e.g. when hovered over it in a UI.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => GetArgument<TerraformValue<string>>("description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// Textual representation of an expression in Common Expression Language syntax.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Expression is required")]
    public required TerraformValue<string> Expression
    {
        get => GetRequiredArgument<TerraformValue<string>>("expression");
        set => SetArgument("expression", value);
    }

    /// <summary>
    /// String indicating the location of the expression for error reporting, e.g. a
    /// file name and a position in the file.
    /// </summary>
    public TerraformValue<string>? Location
    {
        get => GetArgument<TerraformValue<string>>("location");
        set => SetArgument("location", value);
    }

    /// <summary>
    /// Title for the expression, i.e. a short string describing its purpose. This can
    /// be used e.g. in UIs which allow to enter the expression.
    /// </summary>
    public TerraformValue<string>? Title
    {
        get => GetArgument<TerraformValue<string>>("title");
        set => SetArgument("title", value);
    }

}

/// <summary>
/// Block type for resource_selector in GoogleSccProjectCustomModuleCustomConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleSccProjectCustomModuleCustomConfigBlockResourceSelectorBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "resource_selector";

    /// <summary>
    /// The resource types to run the detector on.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ResourceTypes is required")]
    public TerraformList<string>? ResourceTypes
    {
        get => GetArgument<TerraformList<string>>("resource_types");
        set => SetArgument("resource_types", value);
    }

}


/// <summary>
/// Block type for timeouts in GoogleSccProjectCustomModule.
/// Nesting mode: single
/// </summary>
public class GoogleSccProjectCustomModuleTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "timeouts";

    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformValue<string>? Create
    {
        get => GetArgument<TerraformValue<string>>("create");
        set => SetArgument("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformValue<string>? Delete
    {
        get => GetArgument<TerraformValue<string>>("delete");
        set => SetArgument("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformValue<string>? Update
    {
        get => GetArgument<TerraformValue<string>>("update");
        set => SetArgument("update", value);
    }

}


/// <summary>
/// Represents a google_scc_project_custom_module Terraform resource.
/// Manages a google_scc_project_custom_module resource.
/// </summary>
public partial class GoogleSccProjectCustomModule(string name) : TerraformResource("google_scc_project_custom_module", name)
{
    /// <summary>
    /// The display name of the Security Health Analytics custom module. This
    /// display name becomes the finding category for all findings that are
    /// returned by this custom module. The display name must be between 1 and
    /// 128 characters, start with a lowercase letter, and contain alphanumeric
    /// characters or underscores only.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "DisplayName is required")]
    public required TerraformValue<string> DisplayName
    {
        get => GetRequiredArgument<TerraformValue<string>>("display_name");
        set => SetArgument("display_name", value);
    }

    /// <summary>
    /// The enablement state of the custom module. Possible values: [&amp;quot;ENABLED&amp;quot;, &amp;quot;DISABLED&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "EnablementState is required")]
    public required TerraformValue<string> EnablementState
    {
        get => GetRequiredArgument<TerraformValue<string>>("enablement_state");
        set => SetArgument("enablement_state", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformValue<string> Id
    {
        get => GetArgument<TerraformValue<string>>("id") ?? CreateReference("id");
        set => SetArgument("id", value);
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public TerraformValue<string> Project
    {
        get => GetArgument<TerraformValue<string>>("project") ?? CreateReference("project");
        set => SetArgument("project", value);
    }

    /// <summary>
    /// If empty, indicates that the custom module was created in the organization,folder,
    /// or project in which you are viewing the custom module. Otherwise, ancestor_module
    /// specifies the organization or folder from which the custom module is inherited.
    /// </summary>
    public TerraformValue<string> AncestorModule
        => CreateReference("ancestor_module");

    /// <summary>
    /// The editor that last updated the custom module.
    /// </summary>
    public TerraformValue<string> LastEditor
        => CreateReference("last_editor");

    /// <summary>
    /// The resource name of the custom module. Its format is &amp;quot;projects/{project}/securityHealthAnalyticsSettings/customModules/{customModule}&amp;quot;.
    /// The id {customModule} is server-generated and is not user settable. It will be a numeric id containing 1-20 digits.
    /// </summary>
    public TerraformValue<string> Name
        => CreateReference("name");

    /// <summary>
    /// The time at which the custom module was last updated.
    /// 
    /// A timestamp in RFC3339 UTC &amp;quot;Zulu&amp;quot; format, with nanosecond resolution and
    /// up to nine fractional digits. Examples: &amp;quot;2014-10-02T15:01:23Z&amp;quot; and &amp;quot;2014-10-02T15:01:23.045123456Z&amp;quot;.
    /// </summary>
    public TerraformValue<string> UpdateTime
        => CreateReference("update_time");

    /// <summary>
    /// CustomConfig block (nesting mode: list).
    /// This block is required.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "CustomConfig is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 CustomConfig block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 CustomConfig block(s) allowed")]
    public required TerraformList<GoogleSccProjectCustomModuleCustomConfigBlock> CustomConfig
    {
        get => GetRequiredArgument<TerraformList<GoogleSccProjectCustomModuleCustomConfigBlock>>("custom_config");
        set => SetArgument("custom_config", value);
    }

    /// <summary>
    /// Timeouts block (nesting mode: single).
    /// </summary>
    public GoogleSccProjectCustomModuleTimeoutsBlock? Timeouts
    {
        get => GetArgument<GoogleSccProjectCustomModuleTimeoutsBlock>("timeouts");
        set => SetArgument("timeouts", value);
    }

}
