using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for log_config in .
/// Nesting mode: list
/// </summary>
public partial class GoogleNetworkServicesWasmPluginLogConfigBlock : TerraformBlockBase
{
    /// <summary>
    /// Optional. Specifies whether to enable logging for activity by this plugin.
    /// </summary>
    [TerraformProperty("enable")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<bool>? Enable { get; set; }

    /// <summary>
    /// Non-empty default. Specificies the lowest level of the plugin logs that are exported to Cloud Logging. This setting relates to the logs generated by using logging statements in your Wasm code.
    /// This field is can be set only if logging is enabled for the plugin.
    /// If the field is not provided when logging is enabled, it is set to INFO by default. Possible values: [&amp;quot;LOG_LEVEL_UNSPECIFIED&amp;quot;, &amp;quot;TRACE&amp;quot;, &amp;quot;DEBUG&amp;quot;, &amp;quot;INFO&amp;quot;, &amp;quot;WARN&amp;quot;, &amp;quot;ERROR&amp;quot;, &amp;quot;CRITICAL&amp;quot;]
    /// </summary>
    [TerraformProperty("min_log_level")]
    // Optional+Computed - source generator will implement get/set
    public TerraformValue<string> MinLogLevel { get; set; }

    /// <summary>
    /// Non-empty default. Configures the sampling rate of activity logs, where 1.0 means all logged activity is reported and 0.0 means no activity is reported.
    /// A floating point value between 0.0 and 1.0 indicates that a percentage of log messages is stored.
    /// The default value when logging is enabled is 1.0. The value of the field must be between 0 and 1 (inclusive).
    /// This field can be specified only if logging is enabled for this plugin.
    /// </summary>
    [TerraformProperty("sample_rate")]
    // Optional+Computed - source generator will implement get/set
    public TerraformValue<double> SampleRate { get; set; }

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public partial class GoogleNetworkServicesWasmPluginTimeoutsBlock : TerraformBlockBase
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    [TerraformProperty("create")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? Create { get; set; }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    [TerraformProperty("delete")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? Delete { get; set; }

    /// <summary>
    /// The update attribute.
    /// </summary>
    [TerraformProperty("update")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? Update { get; set; }

}

/// <summary>
/// Block type for versions in .
/// Nesting mode: set
/// </summary>
public partial class GoogleNetworkServicesWasmPluginVersionsBlock : TerraformBlockBase
{

    /// <summary>
    /// Optional. A human-readable description of the resource.
    /// </summary>
    [TerraformProperty("description")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? Description { get; set; }


    /// <summary>
    /// Optional. URI of the container image containing the plugin, stored in the Artifact Registry. When a new WasmPluginVersion resource is created, the digest of the container image is saved in the imageDigest field.
    /// When downloading an image, the digest value is used instead of an image tag.
    /// </summary>
    [TerraformProperty("image_uri")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? ImageUri { get; set; }

    /// <summary>
    /// Optional. Set of labels associated with the WasmPlugin resource.
    /// </summary>
    [TerraformProperty("labels")]
    // Optional argument - source generator will implement get/set
    public TerraformMap<string>? Labels { get; set; }

    /// <summary>
    /// A base64-encoded string containing the configuration for the plugin. The configuration is provided to the plugin at runtime through the ON_CONFIGURE callback.
    /// When a new WasmPluginVersion resource is created, the digest of the contents is saved in the pluginConfigDigest field.
    /// Conflics with pluginConfigUri.
    /// </summary>
    [TerraformProperty("plugin_config_data")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? PluginConfigData { get; set; }


    /// <summary>
    /// URI of the plugin configuration stored in the Artifact Registry. The configuration is provided to the plugin at runtime through the ON_CONFIGURE callback.
    /// The container image must contain only a single file with the name plugin.config.
    /// When a new WasmPluginVersion resource is created, the digest of the container image is saved in the pluginConfigDigest field.
    /// Conflics with pluginConfigData.
    /// </summary>
    [TerraformProperty("plugin_config_uri")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? PluginConfigUri { get; set; }


    /// <summary>
    /// The version_name attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "VersionName is required")]
    [TerraformProperty("version_name")]
    // Required argument - source generator will implement get/set
    public required TerraformValue<string> VersionName { get; set; }

}

/// <summary>
/// Manages a google_network_services_wasm_plugin resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public partial class GoogleNetworkServicesWasmPlugin : TerraformResource
{
    public GoogleNetworkServicesWasmPlugin(string name) : base("google_network_services_wasm_plugin", name)
    {
    }

    /// <summary>
    /// Optional. A human-readable description of the resource.
    /// </summary>
    [TerraformProperty("description")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? Description { get; set; }

    /// <summary>
    /// The id attribute.
    /// </summary>
    [TerraformProperty("id")]
    // Optional+Computed - source generator will implement get/set
    public TerraformValue<string> Id { get; set; }

    /// <summary>
    /// Optional. Set of labels associated with the WasmPlugin resource.
    /// 
    /// **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
    /// Please refer to the field &#39;effective_labels&#39; for all of the labels present on the resource.
    /// </summary>
    [TerraformProperty("labels")]
    // Optional argument - source generator will implement get/set
    public TerraformMap<string>? Labels { get; set; }

    /// <summary>
    /// The location of the traffic extension
    /// </summary>
    [TerraformProperty("location")]
    // Optional argument - source generator will implement get/set
    public TerraformValue<string>? Location { get; set; }

    /// <summary>
    /// The ID of the WasmPluginVersion resource that is the currently serving one. The version referred to must be a child of this WasmPlugin resource and should be listed in the &amp;quot;versions&amp;quot; field.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "MainVersionId is required")]
    [TerraformProperty("main_version_id")]
    // Required argument - source generator will implement get/set
    public required TerraformValue<string> MainVersionId { get; set; }

    /// <summary>
    /// Identifier. Name of the WasmPlugin resource.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    [TerraformProperty("name")]
    // Required argument - source generator will implement get/set
    public required TerraformValue<string> Name { get; set; }

    /// <summary>
    /// The project attribute.
    /// </summary>
    [TerraformProperty("project")]
    // Optional+Computed - source generator will implement get/set
    public TerraformValue<string> Project { get; set; }

    /// <summary>
    /// Block for log_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 LogConfig block(s) allowed")]
    [TerraformProperty("log_config")]
    public TerraformList<TerraformBlock<GoogleNetworkServicesWasmPluginLogConfigBlock>>? LogConfig { get; set; }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    [TerraformProperty("timeouts")]
    public TerraformBlock<GoogleNetworkServicesWasmPluginTimeoutsBlock>? Timeouts { get; set; }

    /// <summary>
    /// Block for versions.
    /// Nesting mode: set
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Versions is required")]
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 Versions block(s) required")]
    [TerraformProperty("versions")]
    public TerraformSet<TerraformBlock<GoogleNetworkServicesWasmPluginVersionsBlock>>? Versions { get; set; }

    /// <summary>
    /// Output only. The timestamp when the resource was created.
    /// </summary>
    [TerraformProperty("create_time")]
    // Output-only attribute - source generator will implement read-only get
    public TerraformValue<string> CreateTime { get; }

    /// <summary>
    /// All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.
    /// </summary>
    [TerraformProperty("effective_labels")]
    // Output-only attribute - source generator will implement read-only get
    public TerraformMap<string> EffectiveLabels { get; }

    /// <summary>
    /// The combination of labels configured directly on the resource
    ///  and default labels configured on the provider.
    /// </summary>
    [TerraformProperty("terraform_labels")]
    // Output-only attribute - source generator will implement read-only get
    public TerraformMap<string> TerraformLabels { get; }

    /// <summary>
    /// Output only. The timestamp when the resource was updated.
    /// </summary>
    [TerraformProperty("update_time")]
    // Output-only attribute - source generator will implement read-only get
    public TerraformValue<string> UpdateTime { get; }

    /// <summary>
    /// Output only. List of all extensions that use this WasmPlugin resource.
    /// </summary>
    [TerraformProperty("used_by")]
    // Output-only attribute - source generator will implement read-only get
    public TerraformList<object> UsedBy { get; }

}
