using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for approval_config in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerApprovalConfigBlock() : TerraformBlock("approval_config")
{
    /// <summary>
    /// Whether or not approval is needed. If this is set on a build, it will become pending when run,
    /// and will need to be explicitly approved to start.
    /// </summary>
    [TerraformProperty("approval_required")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<bool>? ApprovalRequired { get; set; }

}

/// <summary>
/// Block type for bitbucket_server_trigger_config in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerBitbucketServerTriggerConfigBlock() : TerraformBlock("bitbucket_server_trigger_config")
{
    /// <summary>
    /// The Bitbucket server config resource that this trigger config maps to.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "BitbucketServerConfigResource is required")]
    [TerraformProperty("bitbucket_server_config_resource")]
    // Required argument - source generator will implement get/set
    public required partial TerraformValue<string> BitbucketServerConfigResource { get; set; }

    /// <summary>
    /// Key of the project that the repo is in. For example: The key for https://mybitbucket.server/projects/TEST/repos/test-repo is &amp;quot;TEST&amp;quot;.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ProjectKey is required")]
    [TerraformProperty("project_key")]
    // Required argument - source generator will implement get/set
    public required partial TerraformValue<string> ProjectKey { get; set; }

    /// <summary>
    /// Slug of the repository. A repository slug is a URL-friendly version of a repository name, automatically generated by Bitbucket for use in the URL.
    /// For example, if the repository name is &#39;test repo&#39;, in the URL it would become &#39;test-repo&#39; as in https://mybitbucket.server/projects/TEST/repos/test-repo.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "RepoSlug is required")]
    [TerraformProperty("repo_slug")]
    // Required argument - source generator will implement get/set
    public required partial TerraformValue<string> RepoSlug { get; set; }

}

/// <summary>
/// Block type for build in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerBuildBlock() : TerraformBlock("build")
{
    /// <summary>
    /// A list of images to be pushed upon the successful completion of all build steps.
    /// The images are pushed using the builder service account&#39;s credentials.
    /// The digests of the pushed images will be stored in the Build resource&#39;s results field.
    /// If any of the images fail to be pushed, the build status is marked FAILURE.
    /// </summary>
    [TerraformProperty("images")]
    // Optional argument - source generator will implement get/set
    public partial TerraformList<string>? Images { get; set; }

    /// <summary>
    /// Google Cloud Storage bucket where logs should be written.
    /// Logs file names will be of the format ${logsBucket}/log-${build_id}.txt.
    /// </summary>
    [TerraformProperty("logs_bucket")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? LogsBucket { get; set; }

    /// <summary>
    /// TTL in queue for this build. If provided and the build is enqueued longer than this value,
    /// the build will expire and the build status will be EXPIRED.
    /// The TTL starts ticking from createTime.
    /// A duration in seconds with up to nine fractional digits, terminated by &#39;s&#39;. Example: &amp;quot;3.5s&amp;quot;.
    /// </summary>
    [TerraformProperty("queue_ttl")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? QueueTtl { get; set; }

    /// <summary>
    /// Substitutions data for Build resource.
    /// </summary>
    [TerraformProperty("substitutions")]
    // Optional argument - source generator will implement get/set
    public partial TerraformMap<string>? Substitutions { get; set; }

    /// <summary>
    /// Tags for annotation of a Build. These are not docker tags.
    /// </summary>
    [TerraformProperty("tags")]
    // Optional argument - source generator will implement get/set
    public partial TerraformList<string>? Tags { get; set; }

    /// <summary>
    /// Amount of time that this build should be allowed to run, to second granularity.
    /// If this amount of time elapses, work on the build will cease and the build status will be TIMEOUT.
    /// This timeout must be equal to or greater than the sum of the timeouts for build steps within the build.
    /// The expected format is the number of seconds followed by s.
    /// Default time is ten minutes (600s).
    /// </summary>
    [TerraformProperty("timeout")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Timeout { get; set; }

}

/// <summary>
/// Block type for developer_connect_event_config in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerDeveloperConnectEventConfigBlock() : TerraformBlock("developer_connect_event_config")
{
    /// <summary>
    /// The Developer Connect Git repository link, formatted as &#39;projects/*/locations/*/connections/*/gitRepositoryLink/*&#39;.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "GitRepositoryLink is required")]
    [TerraformProperty("git_repository_link")]
    // Required argument - source generator will implement get/set
    public required partial TerraformValue<string> GitRepositoryLink { get; set; }


}

/// <summary>
/// Block type for git_file_source in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerGitFileSourceBlock() : TerraformBlock("git_file_source")
{
    /// <summary>
    /// The full resource name of the bitbucket server config.
    /// Format: projects/{project}/locations/{location}/bitbucketServerConfigs/{id}.
    /// </summary>
    [TerraformProperty("bitbucket_server_config")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? BitbucketServerConfig { get; set; }

    /// <summary>
    /// The full resource name of the github enterprise config.
    /// Format: projects/{project}/locations/{location}/githubEnterpriseConfigs/{id}. projects/{project}/githubEnterpriseConfigs/{id}.
    /// </summary>
    [TerraformProperty("github_enterprise_config")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? GithubEnterpriseConfig { get; set; }

    /// <summary>
    /// The path of the file, with the repo root as the root of the path.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Path is required")]
    [TerraformProperty("path")]
    // Required argument - source generator will implement get/set
    public required partial TerraformValue<string> Path { get; set; }

    /// <summary>
    /// The type of the repo, since it may not be explicit from the repo field (e.g from a URL).
    /// Values can be UNKNOWN, CLOUD_SOURCE_REPOSITORIES, GITHUB, BITBUCKET_SERVER Possible values: [&amp;quot;UNKNOWN&amp;quot;, &amp;quot;CLOUD_SOURCE_REPOSITORIES&amp;quot;, &amp;quot;GITHUB&amp;quot;, &amp;quot;BITBUCKET_SERVER&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "RepoType is required")]
    [TerraformProperty("repo_type")]
    // Required argument - source generator will implement get/set
    public required partial TerraformValue<string> RepoType { get; set; }

    /// <summary>
    /// The fully qualified resource name of the Repo API repository. The fully qualified resource name of the Repo API repository.
    /// If unspecified, the repo from which the trigger invocation originated is assumed to be the repo from which to read the specified path.
    /// </summary>
    [TerraformProperty("repository")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Repository { get; set; }

    /// <summary>
    /// The branch, tag, arbitrary ref, or SHA version of the repo to use when resolving the
    /// filename (optional). This field respects the same syntax/resolution as described here: https://git-scm.com/docs/gitrevisions
    /// If unspecified, the revision from which the trigger invocation originated is assumed to be the revision from which to read the specified path.
    /// </summary>
    [TerraformProperty("revision")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Revision { get; set; }

    /// <summary>
    /// The URI of the repo (optional). If unspecified, the repo from which the trigger
    /// invocation originated is assumed to be the repo from which to read the specified path.
    /// </summary>
    [TerraformProperty("uri")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Uri { get; set; }

}

/// <summary>
/// Block type for github in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerGithubBlock() : TerraformBlock("github")
{
    /// <summary>
    /// The resource name of the github enterprise config that should be applied to this installation.
    /// For example: &amp;quot;projects/{$projectId}/locations/{$locationId}/githubEnterpriseConfigs/{$configId}&amp;quot;
    /// </summary>
    [TerraformProperty("enterprise_config_resource_name")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? EnterpriseConfigResourceName { get; set; }

    /// <summary>
    /// Name of the repository. For example: The name for
    /// https://github.com/googlecloudplatform/cloud-builders is &amp;quot;cloud-builders&amp;quot;.
    /// </summary>
    [TerraformProperty("name")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Name { get; set; }

    /// <summary>
    /// Owner of the repository. For example: The owner for
    /// https://github.com/googlecloudplatform/cloud-builders is &amp;quot;googlecloudplatform&amp;quot;.
    /// </summary>
    [TerraformProperty("owner")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Owner { get; set; }

}

/// <summary>
/// Block type for pubsub_config in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerPubsubConfigBlock() : TerraformBlock("pubsub_config")
{
    /// <summary>
    /// Service account that will make the push request.
    /// </summary>
    [TerraformProperty("service_account_email")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? ServiceAccountEmail { get; set; }



    /// <summary>
    /// The name of the topic from which this subscription is receiving messages.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Topic is required")]
    [TerraformProperty("topic")]
    // Required argument - source generator will implement get/set
    public required partial TerraformValue<string> Topic { get; set; }

}

/// <summary>
/// Block type for repository_event_config in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerRepositoryEventConfigBlock() : TerraformBlock("repository_event_config")
{
    /// <summary>
    /// The resource name of the Repo API resource.
    /// </summary>
    [TerraformProperty("repository")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Repository { get; set; }

}

/// <summary>
/// Block type for source_to_build in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerSourceToBuildBlock() : TerraformBlock("source_to_build")
{
    /// <summary>
    /// The full resource name of the bitbucket server config.
    /// Format: projects/{project}/locations/{location}/bitbucketServerConfigs/{id}.
    /// </summary>
    [TerraformProperty("bitbucket_server_config")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? BitbucketServerConfig { get; set; }

    /// <summary>
    /// The full resource name of the github enterprise config.
    /// Format: projects/{project}/locations/{location}/githubEnterpriseConfigs/{id}. projects/{project}/githubEnterpriseConfigs/{id}.
    /// </summary>
    [TerraformProperty("github_enterprise_config")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? GithubEnterpriseConfig { get; set; }

    /// <summary>
    /// The branch or tag to use. Must start with &amp;quot;refs/&amp;quot; (required).
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Ref is required")]
    [TerraformProperty("ref")]
    // Required argument - source generator will implement get/set
    public required partial TerraformValue<string> Ref { get; set; }

    /// <summary>
    /// The type of the repo, since it may not be explicit from the repo field (e.g from a URL).
    /// Values can be UNKNOWN, CLOUD_SOURCE_REPOSITORIES, GITHUB, BITBUCKET_SERVER Possible values: [&amp;quot;UNKNOWN&amp;quot;, &amp;quot;CLOUD_SOURCE_REPOSITORIES&amp;quot;, &amp;quot;GITHUB&amp;quot;, &amp;quot;BITBUCKET_SERVER&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "RepoType is required")]
    [TerraformProperty("repo_type")]
    // Required argument - source generator will implement get/set
    public required partial TerraformValue<string> RepoType { get; set; }

    /// <summary>
    /// The qualified resource name of the Repo API repository.
    /// Either uri or repository can be specified and is required.
    /// </summary>
    [TerraformProperty("repository")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Repository { get; set; }

    /// <summary>
    /// The URI of the repo.
    /// </summary>
    [TerraformProperty("uri")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Uri { get; set; }

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public partial class GoogleCloudbuildTriggerTimeoutsBlock() : TerraformBlock("timeouts")
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    [TerraformProperty("create")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Create { get; set; }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    [TerraformProperty("delete")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Delete { get; set; }

    /// <summary>
    /// The update attribute.
    /// </summary>
    [TerraformProperty("update")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Update { get; set; }

}

/// <summary>
/// Block type for trigger_template in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerTriggerTemplateBlock() : TerraformBlock("trigger_template")
{
    /// <summary>
    /// Name of the branch to build. Exactly one a of branch name, tag, or commit SHA must be provided.
    /// This field is a regular expression.
    /// </summary>
    [TerraformProperty("branch_name")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? BranchName { get; set; }

    /// <summary>
    /// Explicit commit SHA to build. Exactly one of a branch name, tag, or commit SHA must be provided.
    /// </summary>
    [TerraformProperty("commit_sha")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? CommitSha { get; set; }

    /// <summary>
    /// Directory, relative to the source root, in which to run the build.
    /// 
    /// This must be a relative path. If a step&#39;s dir is specified and
    /// is an absolute path, this value is ignored for that step&#39;s
    /// execution.
    /// </summary>
    [TerraformProperty("dir")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Dir { get; set; }

    /// <summary>
    /// Only trigger a build if the revision regex does NOT match the revision regex.
    /// </summary>
    [TerraformProperty("invert_regex")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<bool>? InvertRegex { get; set; }

    /// <summary>
    /// ID of the project that owns the Cloud Source Repository. If
    /// omitted, the project ID requesting the build is assumed.
    /// </summary>
    [TerraformProperty("project_id")]
    // Optional+Computed - source generator will implement get/set
    public partial TerraformValue<string> ProjectId { get; set; }

    /// <summary>
    /// Name of the Cloud Source Repository. If omitted, the name &amp;quot;default&amp;quot; is assumed.
    /// </summary>
    [TerraformProperty("repo_name")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? RepoName { get; set; }

    /// <summary>
    /// Name of the tag to build. Exactly one of a branch name, tag, or commit SHA must be provided.
    /// This field is a regular expression.
    /// </summary>
    [TerraformProperty("tag_name")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? TagName { get; set; }

}

/// <summary>
/// Block type for webhook_config in .
/// Nesting mode: list
/// </summary>
public partial class GoogleCloudbuildTriggerWebhookConfigBlock() : TerraformBlock("webhook_config")
{
    /// <summary>
    /// Resource name for the secret required as a URL parameter.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Secret is required")]
    [TerraformProperty("secret")]
    // Required argument - source generator will implement get/set
    public required partial TerraformValue<string> Secret { get; set; }


}

/// <summary>
/// Manages a google_cloudbuild_trigger resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public partial class GoogleCloudbuildTrigger : TerraformResource
{
    public GoogleCloudbuildTrigger(string name) : base("google_cloudbuild_trigger", name)
    {
    }

    /// <summary>
    /// Human-readable description of the trigger.
    /// </summary>
    [TerraformProperty("description")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Description { get; set; }

    /// <summary>
    /// Whether the trigger is disabled or not. If true, the trigger will never result in a build.
    /// </summary>
    [TerraformProperty("disabled")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<bool>? Disabled { get; set; }

    /// <summary>
    /// Path, from the source root, to a file whose contents is used for the template.
    /// Either a filename or build template must be provided. Set this only when using trigger_template or github.
    /// When using Pub/Sub, Webhook or Manual set the file name using git_file_source instead.
    /// </summary>
    [TerraformProperty("filename")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Filename { get; set; }

    /// <summary>
    /// A Common Expression Language string. Used only with Pub/Sub and Webhook.
    /// </summary>
    [TerraformProperty("filter")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Filter { get; set; }

    /// <summary>
    /// The id attribute.
    /// </summary>
    [TerraformProperty("id")]
    // Optional+Computed - source generator will implement get/set
    public partial TerraformValue<string> Id { get; set; }

    /// <summary>
    /// ignoredFiles and includedFiles are file glob matches using https://golang.org/pkg/path/filepath/#Match
    /// extended with support for &#39;**&#39;.
    /// 
    /// If ignoredFiles and changed files are both empty, then they are not
    /// used to determine whether or not to trigger a build.
    /// 
    /// If ignoredFiles is not empty, then we ignore any files that match any
    /// of the ignored_file globs. If the change has no files that are outside
    /// of the ignoredFiles globs, then we do not trigger a build.
    /// </summary>
    [TerraformProperty("ignored_files")]
    // Optional argument - source generator will implement get/set
    public partial TerraformList<string>? IgnoredFiles { get; set; }

    /// <summary>
    /// Build logs will be sent back to GitHub as part of the checkrun
    /// result.  Values can be INCLUDE_BUILD_LOGS_UNSPECIFIED or
    /// INCLUDE_BUILD_LOGS_WITH_STATUS Possible values: [&amp;quot;INCLUDE_BUILD_LOGS_UNSPECIFIED&amp;quot;, &amp;quot;INCLUDE_BUILD_LOGS_WITH_STATUS&amp;quot;]
    /// </summary>
    [TerraformProperty("include_build_logs")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? IncludeBuildLogs { get; set; }

    /// <summary>
    /// ignoredFiles and includedFiles are file glob matches using https://golang.org/pkg/path/filepath/#Match
    /// extended with support for &#39;**&#39;.
    /// 
    /// If any of the files altered in the commit pass the ignoredFiles filter
    /// and includedFiles is empty, then as far as this filter is concerned, we
    /// should trigger the build.
    /// 
    /// If any of the files altered in the commit pass the ignoredFiles filter
    /// and includedFiles is not empty, then we make sure that at least one of
    /// those files matches a includedFiles glob. If not, then we do not trigger
    /// a build.
    /// </summary>
    [TerraformProperty("included_files")]
    // Optional argument - source generator will implement get/set
    public partial TerraformList<string>? IncludedFiles { get; set; }

    /// <summary>
    /// The [Cloud Build location](https://cloud.google.com/build/docs/locations) for the trigger.
    /// If not specified, &amp;quot;global&amp;quot; is used.
    /// </summary>
    [TerraformProperty("location")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? Location { get; set; }

    /// <summary>
    /// Name of the trigger. Must be unique within the project.
    /// </summary>
    [TerraformProperty("name")]
    // Optional+Computed - source generator will implement get/set
    public partial TerraformValue<string> Name { get; set; }

    /// <summary>
    /// The project attribute.
    /// </summary>
    [TerraformProperty("project")]
    // Optional+Computed - source generator will implement get/set
    public partial TerraformValue<string> Project { get; set; }

    /// <summary>
    /// The service account used for all user-controlled operations including
    /// triggers.patch, triggers.run, builds.create, and builds.cancel.
    /// 
    /// If no service account is set, then the standard Cloud Build service account
    /// ([PROJECT_NUM]@system.gserviceaccount.com) will be used instead.
    /// 
    /// Format: projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT_ID_OR_EMAIL}
    /// </summary>
    [TerraformProperty("service_account")]
    // Optional argument - source generator will implement get/set
    public partial TerraformValue<string>? ServiceAccount { get; set; }

    /// <summary>
    /// Substitutions data for Build resource.
    /// </summary>
    [TerraformProperty("substitutions")]
    // Optional argument - source generator will implement get/set
    public partial TerraformMap<string>? Substitutions { get; set; }

    /// <summary>
    /// Tags for annotation of a BuildTrigger
    /// </summary>
    [TerraformProperty("tags")]
    // Optional argument - source generator will implement get/set
    public partial TerraformList<string>? Tags { get; set; }

    /// <summary>
    /// Block for approval_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ApprovalConfig block(s) allowed")]
    [TerraformProperty("approval_config")]
    public TerraformList<GoogleCloudbuildTriggerApprovalConfigBlock> ApprovalConfig { get; set; } = new();

    /// <summary>
    /// Block for bitbucket_server_trigger_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 BitbucketServerTriggerConfig block(s) allowed")]
    [TerraformProperty("bitbucket_server_trigger_config")]
    public TerraformList<GoogleCloudbuildTriggerBitbucketServerTriggerConfigBlock> BitbucketServerTriggerConfig { get; set; } = new();

    /// <summary>
    /// Block for build.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 Build block(s) allowed")]
    [TerraformProperty("build")]
    public TerraformList<GoogleCloudbuildTriggerBuildBlock> Build { get; set; } = new();

    /// <summary>
    /// Block for developer_connect_event_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 DeveloperConnectEventConfig block(s) allowed")]
    [TerraformProperty("developer_connect_event_config")]
    public TerraformList<GoogleCloudbuildTriggerDeveloperConnectEventConfigBlock> DeveloperConnectEventConfig { get; set; } = new();

    /// <summary>
    /// Block for git_file_source.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 GitFileSource block(s) allowed")]
    [TerraformProperty("git_file_source")]
    public TerraformList<GoogleCloudbuildTriggerGitFileSourceBlock> GitFileSource { get; set; } = new();

    /// <summary>
    /// Block for github.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 Github block(s) allowed")]
    [TerraformProperty("github")]
    public TerraformList<GoogleCloudbuildTriggerGithubBlock> Github { get; set; } = new();

    /// <summary>
    /// Block for pubsub_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 PubsubConfig block(s) allowed")]
    [TerraformProperty("pubsub_config")]
    public TerraformList<GoogleCloudbuildTriggerPubsubConfigBlock> PubsubConfig { get; set; } = new();

    /// <summary>
    /// Block for repository_event_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 RepositoryEventConfig block(s) allowed")]
    [TerraformProperty("repository_event_config")]
    public TerraformList<GoogleCloudbuildTriggerRepositoryEventConfigBlock> RepositoryEventConfig { get; set; } = new();

    /// <summary>
    /// Block for source_to_build.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 SourceToBuild block(s) allowed")]
    [TerraformProperty("source_to_build")]
    public TerraformList<GoogleCloudbuildTriggerSourceToBuildBlock> SourceToBuild { get; set; } = new();

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    [TerraformProperty("timeouts")]
    public GoogleCloudbuildTriggerTimeoutsBlock Timeouts { get; set; } = new();

    /// <summary>
    /// Block for trigger_template.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 TriggerTemplate block(s) allowed")]
    [TerraformProperty("trigger_template")]
    public TerraformList<GoogleCloudbuildTriggerTriggerTemplateBlock> TriggerTemplate { get; set; } = new();

    /// <summary>
    /// Block for webhook_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 WebhookConfig block(s) allowed")]
    [TerraformProperty("webhook_config")]
    public TerraformList<GoogleCloudbuildTriggerWebhookConfigBlock> WebhookConfig { get; set; } = new();

    /// <summary>
    /// Time when the trigger was created.
    /// </summary>
    [TerraformProperty("create_time")]
    // Output-only attribute - source generator will implement read-only get
    public partial TerraformValue<string> CreateTime { get; }

    /// <summary>
    /// The unique identifier for the trigger.
    /// </summary>
    [TerraformProperty("trigger_id")]
    // Output-only attribute - source generator will implement read-only get
    public partial TerraformValue<string> TriggerId { get; }

}
