using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for monitoring_config in GoogleVertexAiFeaturestoreEntitytype.
/// Nesting mode: list
/// </summary>
public class GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "monitoring_config";

    /// <summary>
    /// CategoricalThresholdConfig block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 CategoricalThresholdConfig block(s) allowed")]
    public TerraformList<GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockCategoricalThresholdConfigBlock>? CategoricalThresholdConfig
    {
        get => GetArgument<TerraformList<GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockCategoricalThresholdConfigBlock>>("categorical_threshold_config");
        set => SetArgument("categorical_threshold_config", value);
    }

    /// <summary>
    /// ImportFeaturesAnalysis block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ImportFeaturesAnalysis block(s) allowed")]
    public TerraformList<GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockImportFeaturesAnalysisBlock>? ImportFeaturesAnalysis
    {
        get => GetArgument<TerraformList<GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockImportFeaturesAnalysisBlock>>("import_features_analysis");
        set => SetArgument("import_features_analysis", value);
    }

    /// <summary>
    /// NumericalThresholdConfig block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 NumericalThresholdConfig block(s) allowed")]
    public TerraformList<GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockNumericalThresholdConfigBlock>? NumericalThresholdConfig
    {
        get => GetArgument<TerraformList<GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockNumericalThresholdConfigBlock>>("numerical_threshold_config");
        set => SetArgument("numerical_threshold_config", value);
    }

    /// <summary>
    /// SnapshotAnalysis block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 SnapshotAnalysis block(s) allowed")]
    public TerraformList<GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockSnapshotAnalysisBlock>? SnapshotAnalysis
    {
        get => GetArgument<TerraformList<GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockSnapshotAnalysisBlock>>("snapshot_analysis");
        set => SetArgument("snapshot_analysis", value);
    }

}

/// <summary>
/// Block type for categorical_threshold_config in GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockCategoricalThresholdConfigBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "categorical_threshold_config";

    /// <summary>
    /// Specify a threshold value that can trigger the alert. For categorical feature, the distribution distance is calculated by L-inifinity norm. Each feature must have a non-zero threshold if they need to be monitored. Otherwise no alert will be triggered for that feature. The default value is 0.3.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Value is required")]
    public required TerraformValue<double> Value
    {
        get => new TerraformReference<double>(this, "value");
        set => SetArgument("value", value);
    }

}

/// <summary>
/// Block type for import_features_analysis in GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockImportFeaturesAnalysisBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "import_features_analysis";

    /// <summary>
    /// Defines the baseline to do anomaly detection for feature values imported by each [entityTypes.importFeatureValues][] operation. The value must be one of the values below:
    /// * LATEST_STATS: Choose the later one statistics generated by either most recent snapshot analysis or previous import features analysis. If non of them exists, skip anomaly detection and only generate a statistics.
    /// * MOST_RECENT_SNAPSHOT_STATS: Use the statistics generated by the most recent snapshot analysis if exists.
    /// * PREVIOUS_IMPORT_FEATURES_STATS: Use the statistics generated by the previous import features analysis if exists.
    /// </summary>
    public TerraformValue<string>? AnomalyDetectionBaseline
    {
        get => new TerraformReference<string>(this, "anomaly_detection_baseline");
        set => SetArgument("anomaly_detection_baseline", value);
    }

    /// <summary>
    /// Whether to enable / disable / inherite default hebavior for import features analysis. The value must be one of the values below:
    /// * DEFAULT: The default behavior of whether to enable the monitoring. EntityType-level config: disabled.
    /// * ENABLED: Explicitly enables import features analysis. EntityType-level config: by default enables import features analysis for all Features under it.
    /// * DISABLED: Explicitly disables import features analysis. EntityType-level config: by default disables import features analysis for all Features under it.
    /// </summary>
    public TerraformValue<string>? State
    {
        get => new TerraformReference<string>(this, "state");
        set => SetArgument("state", value);
    }

}

/// <summary>
/// Block type for numerical_threshold_config in GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockNumericalThresholdConfigBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "numerical_threshold_config";

    /// <summary>
    /// Specify a threshold value that can trigger the alert. For numerical feature, the distribution distance is calculated by Jensen–Shannon divergence. Each feature must have a non-zero threshold if they need to be monitored. Otherwise no alert will be triggered for that feature. The default value is 0.3.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Value is required")]
    public required TerraformValue<double> Value
    {
        get => new TerraformReference<double>(this, "value");
        set => SetArgument("value", value);
    }

}

/// <summary>
/// Block type for snapshot_analysis in GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlock.
/// Nesting mode: list
/// </summary>
public class GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlockSnapshotAnalysisBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "snapshot_analysis";

    /// <summary>
    /// The monitoring schedule for snapshot analysis. For EntityType-level config: unset / disabled = true indicates disabled by default for Features under it; otherwise by default enable snapshot analysis monitoring with monitoringInterval for Features under it.
    /// </summary>
    public TerraformValue<bool>? Disabled
    {
        get => new TerraformReference<bool>(this, "disabled");
        set => SetArgument("disabled", value);
    }

    /// <summary>
    /// Configuration of the snapshot analysis based monitoring pipeline running interval. The value indicates number of days. The default value is 1.
    /// If both FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval_days and [FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval][] are set when creating/updating EntityTypes/Features, FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval_days will be used.
    /// </summary>
    public TerraformValue<double>? MonitoringIntervalDays
    {
        get => new TerraformReference<double>(this, "monitoring_interval_days");
        set => SetArgument("monitoring_interval_days", value);
    }

    /// <summary>
    /// Customized export features time window for snapshot analysis. Unit is one day. The default value is 21 days. Minimum value is 1 day. Maximum value is 4000 days.
    /// </summary>
    public TerraformValue<double>? StalenessDays
    {
        get => new TerraformReference<double>(this, "staleness_days");
        set => SetArgument("staleness_days", value);
    }

}


/// <summary>
/// Block type for timeouts in GoogleVertexAiFeaturestoreEntitytype.
/// Nesting mode: single
/// </summary>
public class GoogleVertexAiFeaturestoreEntitytypeTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// Gets the block type.
    /// </summary>
    public override string BlockType => "timeouts";

    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformValue<string>? Create
    {
        get => new TerraformReference<string>(this, "create");
        set => SetArgument("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformValue<string>? Delete
    {
        get => new TerraformReference<string>(this, "delete");
        set => SetArgument("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformValue<string>? Update
    {
        get => new TerraformReference<string>(this, "update");
        set => SetArgument("update", value);
    }

}


/// <summary>
/// Represents a google_vertex_ai_featurestore_entitytype Terraform resource.
/// Manages a google_vertex_ai_featurestore_entitytype resource.
/// </summary>
public partial class GoogleVertexAiFeaturestoreEntitytype(string name) : TerraformResource("google_vertex_ai_featurestore_entitytype", name)
{
    /// <summary>
    /// Optional. Description of the EntityType.
    /// </summary>
    public TerraformValue<string>? Description
    {
        get => new TerraformReference<string>(this, "description");
        set => SetArgument("description", value);
    }

    /// <summary>
    /// The name of the Featurestore to use, in the format projects/{project}/locations/{location}/featurestores/{featurestore}.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Featurestore is required")]
    public required TerraformValue<string> Featurestore
    {
        get => new TerraformReference<string>(this, "featurestore");
        set => SetArgument("featurestore", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformValue<string> Id
    {
        get => new TerraformReference<string>(this, "id");
        set => SetArgument("id", value);
    }

    /// <summary>
    /// A set of key/value label pairs to assign to this EntityType.
    /// 
    /// 
    /// **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
    /// Please refer to the field &#39;effective_labels&#39; for all of the labels present on the resource.
    /// </summary>
    public TerraformMap<string>? Labels
    {
        get => TerraformMap<string>.Lazy(ctx => new TerraformReference<TerraformMap<string>>(this, "labels").ResolveNodes(ctx));
        set => SetArgument("labels", value);
    }

    /// <summary>
    /// The name of the EntityType. This value may be up to 60 characters, and valid characters are [a-z0-9_]. The first character cannot be a number.
    /// </summary>
    public TerraformValue<string>? Name
    {
        get => new TerraformReference<string>(this, "name");
        set => SetArgument("name", value);
    }

    /// <summary>
    /// The timestamp of when the featurestore was created in RFC3339 UTC &amp;quot;Zulu&amp;quot; format, with nanosecond resolution and up to nine fractional digits.
    /// </summary>
    public TerraformValue<string> CreateTime
    {
        get => new TerraformReference<string>(this, "create_time");
    }

    /// <summary>
    /// All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.
    /// </summary>
    public TerraformMap<string> EffectiveLabels
    {
        get => TerraformMap<string>.Lazy(ctx => new TerraformReference<TerraformMap<string>>(this, "effective_labels").ResolveNodes(ctx));
    }

    /// <summary>
    /// Used to perform consistent read-modify-write updates.
    /// </summary>
    public TerraformValue<string> Etag
    {
        get => new TerraformReference<string>(this, "etag");
    }

    /// <summary>
    /// The region of the EntityType.
    /// </summary>
    public TerraformValue<string> Region
    {
        get => new TerraformReference<string>(this, "region");
    }

    /// <summary>
    /// The combination of labels configured directly on the resource
    ///  and default labels configured on the provider.
    /// </summary>
    public TerraformMap<string> TerraformLabels
    {
        get => TerraformMap<string>.Lazy(ctx => new TerraformReference<TerraformMap<string>>(this, "terraform_labels").ResolveNodes(ctx));
    }

    /// <summary>
    /// The timestamp of when the featurestore was last updated in RFC3339 UTC &amp;quot;Zulu&amp;quot; format, with nanosecond resolution and up to nine fractional digits.
    /// </summary>
    public TerraformValue<string> UpdateTime
    {
        get => new TerraformReference<string>(this, "update_time");
    }

    /// <summary>
    /// MonitoringConfig block (nesting mode: list).
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 MonitoringConfig block(s) allowed")]
    public TerraformList<GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlock>? MonitoringConfig
    {
        get => GetArgument<TerraformList<GoogleVertexAiFeaturestoreEntitytypeMonitoringConfigBlock>>("monitoring_config");
        set => SetArgument("monitoring_config", value);
    }

    /// <summary>
    /// Timeouts block (nesting mode: single).
    /// </summary>
    public GoogleVertexAiFeaturestoreEntitytypeTimeoutsBlock? Timeouts
    {
        get => GetArgument<GoogleVertexAiFeaturestoreEntitytypeTimeoutsBlock>("timeouts");
        set => SetArgument("timeouts", value);
    }

}
