using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.AzureRM;

/// <summary>
/// Retrieves information about a azurerm_dashboard_grafana.
/// </summary>
public class AzurermDashboardGrafanaDataSource : TerraformDataSource
{
    public AzurermDashboardGrafanaDataSource(string name) : base("azurerm_dashboard_grafana", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("api_key_enabled");
        this.DeclareOutput("auto_generated_domain_name_label_scope");
        this.DeclareOutput("azure_monitor_workspace_integrations");
        this.DeclareOutput("deterministic_outbound_ip_enabled");
        this.DeclareOutput("endpoint");
        this.DeclareOutput("grafana_major_version");
        this.DeclareOutput("grafana_version");
        this.DeclareOutput("location");
        this.DeclareOutput("outbound_ips");
        this.DeclareOutput("public_network_access_enabled");
        this.DeclareOutput("sku");
        this.DeclareOutput("tags");
        this.DeclareOutput("zone_redundancy_enabled");
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public string? Id
    {
        get => GetProperty<TerraformLiteralProperty<string>>("id")?.Value;
        set => this.WithProperty("id", value == null ? null : new TerraformLiteralProperty<string>(value));
    }

    /// <summary>
    /// The name attribute.
    /// </summary>
    public string? Name
    {
        get => GetProperty<TerraformLiteralProperty<string>>("name")?.Value;
        set => this.WithProperty("name", value == null ? null : new TerraformLiteralProperty<string>(value));
    }

    /// <summary>
    /// The resource_group_name attribute.
    /// </summary>
    public string? ResourceGroupName
    {
        get => GetProperty<TerraformLiteralProperty<string>>("resource_group_name")?.Value;
        set => this.WithProperty("resource_group_name", value == null ? null : new TerraformLiteralProperty<string>(value));
    }

    /// <summary>
    /// The api_key_enabled attribute.
    /// </summary>
    public TerraformExpression ApiKeyEnabled => this["api_key_enabled"];

    /// <summary>
    /// The auto_generated_domain_name_label_scope attribute.
    /// </summary>
    public TerraformExpression AutoGeneratedDomainNameLabelScope => this["auto_generated_domain_name_label_scope"];

    /// <summary>
    /// The azure_monitor_workspace_integrations attribute.
    /// </summary>
    public TerraformExpression AzureMonitorWorkspaceIntegrations => this["azure_monitor_workspace_integrations"];

    /// <summary>
    /// The deterministic_outbound_ip_enabled attribute.
    /// </summary>
    public TerraformExpression DeterministicOutboundIpEnabled => this["deterministic_outbound_ip_enabled"];

    /// <summary>
    /// The endpoint attribute.
    /// </summary>
    public TerraformExpression Endpoint => this["endpoint"];

    /// <summary>
    /// The grafana_major_version attribute.
    /// </summary>
    public TerraformExpression GrafanaMajorVersion => this["grafana_major_version"];

    /// <summary>
    /// The grafana_version attribute.
    /// </summary>
    public TerraformExpression GrafanaVersion => this["grafana_version"];

    /// <summary>
    /// The location attribute.
    /// </summary>
    public TerraformExpression Location => this["location"];

    /// <summary>
    /// The outbound_ips attribute.
    /// </summary>
    public TerraformExpression OutboundIps => this["outbound_ips"];

    /// <summary>
    /// The public_network_access_enabled attribute.
    /// </summary>
    public TerraformExpression PublicNetworkAccessEnabled => this["public_network_access_enabled"];

    /// <summary>
    /// The sku attribute.
    /// </summary>
    public TerraformExpression Sku => this["sku"];

    /// <summary>
    /// The tags attribute.
    /// </summary>
    public TerraformExpression Tags => this["tags"];

    /// <summary>
    /// The zone_redundancy_enabled attribute.
    /// </summary>
    public TerraformExpression ZoneRedundancyEnabled => this["zone_redundancy_enabled"];

}
