using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Manages a google_identity_platform_tenant resource.
/// </summary>
public class GoogleIdentityPlatformTenant : TerraformResource
{
    public GoogleIdentityPlatformTenant(string name) : base("google_identity_platform_tenant", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("name");
    }

    /// <summary>
    /// Whether to allow email/password user authentication.
    /// </summary>
    public bool? AllowPasswordSignup
    {
        get => GetProperty<TerraformLiteralProperty<bool>>("allow_password_signup")?.Value;
        set => this.WithProperty("allow_password_signup", value == null ? null : new TerraformLiteralProperty<bool>(value.Value));
    }

    /// <summary>
    /// Whether authentication is disabled for the tenant. If true, the users under
    /// the disabled tenant are not allowed to sign-in. Admins of the disabled tenant
    /// are not able to manage its users.
    /// </summary>
    public bool? DisableAuth
    {
        get => GetProperty<TerraformLiteralProperty<bool>>("disable_auth")?.Value;
        set => this.WithProperty("disable_auth", value == null ? null : new TerraformLiteralProperty<bool>(value.Value));
    }

    /// <summary>
    /// Human friendly display name of the tenant.
    /// </summary>
    public string? DisplayName
    {
        get => GetProperty<TerraformLiteralProperty<string>>("display_name")?.Value;
        set => this.WithProperty("display_name", value == null ? null : new TerraformLiteralProperty<string>(value));
    }

    /// <summary>
    /// Whether to enable email link user authentication.
    /// </summary>
    public bool? EnableEmailLinkSignin
    {
        get => GetProperty<TerraformLiteralProperty<bool>>("enable_email_link_signin")?.Value;
        set => this.WithProperty("enable_email_link_signin", value == null ? null : new TerraformLiteralProperty<bool>(value.Value));
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public string? Id
    {
        get => GetProperty<TerraformLiteralProperty<string>>("id")?.Value;
        set => this.WithProperty("id", value == null ? null : new TerraformLiteralProperty<string>(value));
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public string? Project
    {
        get => GetProperty<TerraformLiteralProperty<string>>("project")?.Value;
        set => this.WithProperty("project", value == null ? null : new TerraformLiteralProperty<string>(value));
    }

    /// <summary>
    /// The name of the tenant that is generated by the server
    /// </summary>
    public TerraformExpression Name => this["name"];

}
