using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for log_config in .
/// Nesting mode: list
/// </summary>
public class GoogleNetworkServicesWasmPluginLogConfigBlock : TerraformBlock
{
    /// <summary>
    /// Optional. Specifies whether to enable logging for activity by this plugin.
    /// </summary>
    public TerraformProperty<bool>? Enable
    {
        get => GetProperty<TerraformProperty<bool>>("enable");
        set => WithProperty("enable", value);
    }

    /// <summary>
    /// Non-empty default. Specificies the lowest level of the plugin logs that are exported to Cloud Logging. This setting relates to the logs generated by using logging statements in your Wasm code.
    /// This field is can be set only if logging is enabled for the plugin.
    /// If the field is not provided when logging is enabled, it is set to INFO by default. Possible values: [&amp;quot;LOG_LEVEL_UNSPECIFIED&amp;quot;, &amp;quot;TRACE&amp;quot;, &amp;quot;DEBUG&amp;quot;, &amp;quot;INFO&amp;quot;, &amp;quot;WARN&amp;quot;, &amp;quot;ERROR&amp;quot;, &amp;quot;CRITICAL&amp;quot;]
    /// </summary>
    public TerraformProperty<string>? MinLogLevel
    {
        get => GetProperty<TerraformProperty<string>>("min_log_level");
        set => WithProperty("min_log_level", value);
    }

    /// <summary>
    /// Non-empty default. Configures the sampling rate of activity logs, where 1.0 means all logged activity is reported and 0.0 means no activity is reported.
    /// A floating point value between 0.0 and 1.0 indicates that a percentage of log messages is stored.
    /// The default value when logging is enabled is 1.0. The value of the field must be between 0 and 1 (inclusive).
    /// This field can be specified only if logging is enabled for this plugin.
    /// </summary>
    public TerraformProperty<double>? SampleRate
    {
        get => GetProperty<TerraformProperty<double>>("sample_rate");
        set => WithProperty("sample_rate", value);
    }

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleNetworkServicesWasmPluginTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformProperty<string>? Create
    {
        get => GetProperty<TerraformProperty<string>>("create");
        set => WithProperty("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformProperty<string>? Delete
    {
        get => GetProperty<TerraformProperty<string>>("delete");
        set => WithProperty("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformProperty<string>? Update
    {
        get => GetProperty<TerraformProperty<string>>("update");
        set => WithProperty("update", value);
    }

}

/// <summary>
/// Block type for versions in .
/// Nesting mode: set
/// </summary>
public class GoogleNetworkServicesWasmPluginVersionsBlock : TerraformBlock
{
    /// <summary>
    /// Output only. The timestamp when the resource was created.
    /// </summary>
    public TerraformProperty<string>? CreateTime
    {
        get => GetProperty<TerraformProperty<string>>("create_time");
        set => WithProperty("create_time", value);
    }

    /// <summary>
    /// Optional. A human-readable description of the resource.
    /// </summary>
    public TerraformProperty<string>? Description
    {
        get => GetProperty<TerraformProperty<string>>("description");
        set => WithProperty("description", value);
    }

    /// <summary>
    /// Output only. The resolved digest for the image specified in the image field. The digest is resolved during the creation of WasmPluginVersion resource.
    /// This field holds the digest value, regardless of whether a tag or digest was originally specified in the image field.
    /// </summary>
    public TerraformProperty<string>? ImageDigest
    {
        get => GetProperty<TerraformProperty<string>>("image_digest");
        set => WithProperty("image_digest", value);
    }

    /// <summary>
    /// Optional. URI of the container image containing the plugin, stored in the Artifact Registry. When a new WasmPluginVersion resource is created, the digest of the container image is saved in the imageDigest field.
    /// When downloading an image, the digest value is used instead of an image tag.
    /// </summary>
    public TerraformProperty<string>? ImageUri
    {
        get => GetProperty<TerraformProperty<string>>("image_uri");
        set => WithProperty("image_uri", value);
    }

    /// <summary>
    /// Optional. Set of labels associated with the WasmPlugin resource.
    /// </summary>
    public Dictionary<string, TerraformProperty<string>>? Labels
    {
        get => GetProperty<Dictionary<string, TerraformProperty<string>>>("labels");
        set => WithProperty("labels", value);
    }

    /// <summary>
    /// A base64-encoded string containing the configuration for the plugin. The configuration is provided to the plugin at runtime through the ON_CONFIGURE callback.
    /// When a new WasmPluginVersion resource is created, the digest of the contents is saved in the pluginConfigDigest field.
    /// Conflics with pluginConfigUri.
    /// </summary>
    public TerraformProperty<string>? PluginConfigData
    {
        get => GetProperty<TerraformProperty<string>>("plugin_config_data");
        set => WithProperty("plugin_config_data", value);
    }

    /// <summary>
    /// Output only. This field holds the digest (usually checksum) value for the plugin configuration.
    /// The value is calculated based on the contents of pluginConfigData or the container image defined by the pluginConfigUri field.
    /// </summary>
    public TerraformProperty<string>? PluginConfigDigest
    {
        get => GetProperty<TerraformProperty<string>>("plugin_config_digest");
        set => WithProperty("plugin_config_digest", value);
    }

    /// <summary>
    /// URI of the plugin configuration stored in the Artifact Registry. The configuration is provided to the plugin at runtime through the ON_CONFIGURE callback.
    /// The container image must contain only a single file with the name plugin.config.
    /// When a new WasmPluginVersion resource is created, the digest of the container image is saved in the pluginConfigDigest field.
    /// Conflics with pluginConfigData.
    /// </summary>
    public TerraformProperty<string>? PluginConfigUri
    {
        get => GetProperty<TerraformProperty<string>>("plugin_config_uri");
        set => WithProperty("plugin_config_uri", value);
    }

    /// <summary>
    /// Output only. The timestamp when the resource was updated.
    /// </summary>
    public TerraformProperty<string>? UpdateTime
    {
        get => GetProperty<TerraformProperty<string>>("update_time");
        set => WithProperty("update_time", value);
    }

    /// <summary>
    /// The version_name attribute.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "VersionName is required")]
    public required TerraformProperty<string> VersionName
    {
        get => GetProperty<TerraformProperty<string>>("version_name");
        set => WithProperty("version_name", value);
    }

}

/// <summary>
/// Manages a google_network_services_wasm_plugin resource.
/// </summary>
public class GoogleNetworkServicesWasmPlugin : TerraformResource
{
    public GoogleNetworkServicesWasmPlugin(string name) : base("google_network_services_wasm_plugin", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("create_time");
        this.DeclareOutput("effective_labels");
        this.DeclareOutput("terraform_labels");
        this.DeclareOutput("update_time");
        this.DeclareOutput("used_by");
    }

    /// <summary>
    /// Optional. A human-readable description of the resource.
    /// </summary>
    public TerraformProperty<string>? Description
    {
        get => GetProperty<TerraformProperty<string>>("description");
        set => this.WithProperty("description", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformProperty<string>? Id
    {
        get => GetProperty<TerraformProperty<string>>("id");
        set => this.WithProperty("id", value);
    }

    /// <summary>
    /// Optional. Set of labels associated with the WasmPlugin resource.
    /// 
    /// **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
    /// Please refer to the field &#39;effective_labels&#39; for all of the labels present on the resource.
    /// </summary>
    public Dictionary<string, TerraformProperty<string>>? Labels
    {
        get => GetProperty<Dictionary<string, TerraformProperty<string>>>("labels");
        set => this.WithProperty("labels", value);
    }

    /// <summary>
    /// The location of the traffic extension
    /// </summary>
    public TerraformProperty<string>? Location
    {
        get => GetProperty<TerraformProperty<string>>("location");
        set => this.WithProperty("location", value);
    }

    /// <summary>
    /// The ID of the WasmPluginVersion resource that is the currently serving one. The version referred to must be a child of this WasmPlugin resource and should be listed in the &amp;quot;versions&amp;quot; field.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "MainVersionId is required")]
    public required TerraformProperty<string> MainVersionId
    {
        get => GetProperty<TerraformProperty<string>>("main_version_id");
        set => this.WithProperty("main_version_id", value);
    }

    /// <summary>
    /// Identifier. Name of the WasmPlugin resource.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    public required TerraformProperty<string> Name
    {
        get => GetProperty<TerraformProperty<string>>("name");
        set => this.WithProperty("name", value);
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public TerraformProperty<string>? Project
    {
        get => GetProperty<TerraformProperty<string>>("project");
        set => this.WithProperty("project", value);
    }

    /// <summary>
    /// Block for log_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 LogConfig block(s) allowed")]
    public List<GoogleNetworkServicesWasmPluginLogConfigBlock>? LogConfig
    {
        get => GetProperty<List<GoogleNetworkServicesWasmPluginLogConfigBlock>>("log_config");
        set => this.WithProperty("log_config", value);
    }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    public GoogleNetworkServicesWasmPluginTimeoutsBlock? Timeouts
    {
        get => GetProperty<GoogleNetworkServicesWasmPluginTimeoutsBlock>("timeouts");
        set => this.WithProperty("timeouts", value);
    }

    /// <summary>
    /// Block for versions.
    /// Nesting mode: set
    /// </summary>
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 Versions block(s) required")]
    public HashSet<GoogleNetworkServicesWasmPluginVersionsBlock>? Versions
    {
        get => GetProperty<HashSet<GoogleNetworkServicesWasmPluginVersionsBlock>>("versions");
        set => this.WithProperty("versions", value);
    }

    /// <summary>
    /// Output only. The timestamp when the resource was created.
    /// </summary>
    public TerraformExpression CreateTime => this["create_time"];

    /// <summary>
    /// All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.
    /// </summary>
    public TerraformExpression EffectiveLabels => this["effective_labels"];

    /// <summary>
    /// The combination of labels configured directly on the resource
    ///  and default labels configured on the provider.
    /// </summary>
    public TerraformExpression TerraformLabels => this["terraform_labels"];

    /// <summary>
    /// Output only. The timestamp when the resource was updated.
    /// </summary>
    public TerraformExpression UpdateTime => this["update_time"];

    /// <summary>
    /// Output only. List of all extensions that use this WasmPlugin resource.
    /// </summary>
    public TerraformExpression UsedBy => this["used_by"];

}
