using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Manages a google_public_ca_external_account_key resource.
/// </summary>
public class GooglePublicCaExternalAccountKey : TerraformResource
{
    public GooglePublicCaExternalAccountKey(string name) : base("google_public_ca_external_account_key", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("b64_mac_key");
        this.DeclareOutput("b64url_mac_key");
        this.DeclareOutput("key_id");
        this.DeclareOutput("name");
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public string? Id
    {
        get => GetProperty<TerraformLiteralProperty<string>>("id")?.Value;
        set => this.WithProperty("id", value == null ? null : new TerraformLiteralProperty<string>(value));
    }

    /// <summary>
    /// Location for the externalAccountKey. Currently only &#39;global&#39; is supported.
    /// </summary>
    public string? Location
    {
        get => GetProperty<TerraformLiteralProperty<string>>("location")?.Value;
        set => this.WithProperty("location", value == null ? null : new TerraformLiteralProperty<string>(value));
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public string? Project
    {
        get => GetProperty<TerraformLiteralProperty<string>>("project")?.Value;
        set => this.WithProperty("project", value == null ? null : new TerraformLiteralProperty<string>(value));
    }

    /// <summary>
    /// Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService
    /// when the ExternalAccountKey is created.
    /// </summary>
    public TerraformExpression B64MacKey => this["b64_mac_key"];

    /// <summary>
    /// Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService
    /// when the ExternalAccountKey is created.&#39;
    /// </summary>
    public TerraformExpression B64urlMacKey => this["b64url_mac_key"];

    /// <summary>
    /// It is generated by the PublicCertificateAuthorityService when the ExternalAccountKey is created.
    /// </summary>
    public TerraformExpression KeyId => this["key_id"];

    /// <summary>
    /// Resource name. projects/{project}/locations/{location}/externalAccountKeys/{keyId}.
    /// </summary>
    public TerraformExpression Name => this["name"];

}
