using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for alert_strategy in .
/// Nesting mode: list
/// </summary>
public class GoogleMonitoringAlertPolicyAlertStrategyBlock : TerraformBlock
{
    /// <summary>
    /// If an alert policy that was active has no data for this long, any open incidents will close.
    /// </summary>
    public TerraformProperty<string>? AutoClose
    {
        get => GetProperty<TerraformProperty<string>>("auto_close");
        set => WithProperty("auto_close", value);
    }

    /// <summary>
    /// Control when notifications will be sent out. Possible values: [&amp;quot;NOTIFICATION_PROMPT_UNSPECIFIED&amp;quot;, &amp;quot;OPENED&amp;quot;, &amp;quot;CLOSED&amp;quot;]
    /// </summary>
    public List<TerraformProperty<string>>? NotificationPrompts
    {
        get => GetProperty<List<TerraformProperty<string>>>("notification_prompts");
        set => WithProperty("notification_prompts", value);
    }

}

/// <summary>
/// Block type for conditions in .
/// Nesting mode: list
/// </summary>
public class GoogleMonitoringAlertPolicyConditionsBlock : TerraformBlock
{
    /// <summary>
    /// A short name or phrase used to identify the
    /// condition in dashboards, notifications, and
    /// incidents. To avoid confusion, don&#39;t use the same
    /// display name for multiple conditions in the same
    /// policy.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "DisplayName is required")]
    public required TerraformProperty<string> DisplayName
    {
        get => GetProperty<TerraformProperty<string>>("display_name");
        set => WithProperty("display_name", value);
    }

    /// <summary>
    /// The unique resource name for this condition.
    /// Its syntax is:
    /// projects/[PROJECT_ID]/alertPolicies/[POLICY_ID]/conditions/[CONDITION_ID]
    /// [CONDITION_ID] is assigned by Stackdriver Monitoring when
    /// the condition is created as part of a new or updated alerting
    /// policy.
    /// </summary>
    public TerraformProperty<string>? Name
    {
        get => GetProperty<TerraformProperty<string>>("name");
        set => WithProperty("name", value);
    }

}

/// <summary>
/// Block type for documentation in .
/// Nesting mode: list
/// </summary>
public class GoogleMonitoringAlertPolicyDocumentationBlock : TerraformBlock
{
    /// <summary>
    /// The text of the documentation, interpreted according to mimeType.
    /// The content may not exceed 8,192 Unicode characters and may not
    /// exceed more than 10,240 bytes when encoded in UTF-8 format,
    /// whichever is smaller.
    /// </summary>
    public TerraformProperty<string>? Content
    {
        get => GetProperty<TerraformProperty<string>>("content");
        set => WithProperty("content", value);
    }

    /// <summary>
    /// The format of the content field. Presently, only the value
    /// &amp;quot;text/markdown&amp;quot; is supported.
    /// </summary>
    public TerraformProperty<string>? MimeType
    {
        get => GetProperty<TerraformProperty<string>>("mime_type");
        set => WithProperty("mime_type", value);
    }

    /// <summary>
    /// The subject line of the notification. The subject line may not
    /// exceed 10,240 bytes. In notifications generated by this policy the contents
    /// of the subject line after variable expansion will be truncated to 255 bytes
    /// or shorter at the latest UTF-8 character boundary.
    /// </summary>
    public TerraformProperty<string>? Subject
    {
        get => GetProperty<TerraformProperty<string>>("subject");
        set => WithProperty("subject", value);
    }

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleMonitoringAlertPolicyTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformProperty<string>? Create
    {
        get => GetProperty<TerraformProperty<string>>("create");
        set => WithProperty("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformProperty<string>? Delete
    {
        get => GetProperty<TerraformProperty<string>>("delete");
        set => WithProperty("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformProperty<string>? Update
    {
        get => GetProperty<TerraformProperty<string>>("update");
        set => WithProperty("update", value);
    }

}

/// <summary>
/// Manages a google_monitoring_alert_policy resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public class GoogleMonitoringAlertPolicy : TerraformResource
{
    public GoogleMonitoringAlertPolicy(string name) : base("google_monitoring_alert_policy", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("creation_record");
        this.DeclareOutput("name");
    }

    /// <summary>
    /// How to combine the results of multiple conditions to
    /// determine if an incident should be opened. Possible values: [&amp;quot;AND&amp;quot;, &amp;quot;OR&amp;quot;, &amp;quot;AND_WITH_MATCHING_RESOURCE&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Combiner is required")]
    public required TerraformProperty<string> Combiner
    {
        get => GetProperty<TerraformProperty<string>>("combiner");
        set => this.WithProperty("combiner", value);
    }

    /// <summary>
    /// A short name or phrase used to identify the policy in
    /// dashboards, notifications, and incidents. To avoid confusion, don&#39;t use
    /// the same display name for multiple policies in the same project. The
    /// name is limited to 512 Unicode characters.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "DisplayName is required")]
    public required TerraformProperty<string> DisplayName
    {
        get => GetProperty<TerraformProperty<string>>("display_name");
        set => this.WithProperty("display_name", value);
    }

    /// <summary>
    /// Whether or not the policy is enabled. The default is true.
    /// </summary>
    public TerraformProperty<bool>? Enabled
    {
        get => GetProperty<TerraformProperty<bool>>("enabled");
        set => this.WithProperty("enabled", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformProperty<string>? Id
    {
        get => GetProperty<TerraformProperty<string>>("id");
        set => this.WithProperty("id", value);
    }

    /// <summary>
    /// Identifies the notification channels to which notifications should be
    /// sent when incidents are opened or closed or when new violations occur
    /// on an already opened incident. Each element of this array corresponds
    /// to the name field in each of the NotificationChannel objects that are
    /// returned from the notificationChannels.list method. The syntax of the
    /// entries in this field is
    /// &#39;projects/[PROJECT_ID]/notificationChannels/[CHANNEL_ID]&#39;
    /// </summary>
    public List<TerraformProperty<string>>? NotificationChannels
    {
        get => GetProperty<List<TerraformProperty<string>>>("notification_channels");
        set => this.WithProperty("notification_channels", value);
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public TerraformProperty<string>? Project
    {
        get => GetProperty<TerraformProperty<string>>("project");
        set => this.WithProperty("project", value);
    }

    /// <summary>
    /// The severity of an alert policy indicates how important incidents generated
    /// by that policy are. The severity level will be displayed on the Incident
    /// detail page and in notifications. Possible values: [&amp;quot;CRITICAL&amp;quot;, &amp;quot;ERROR&amp;quot;, &amp;quot;WARNING&amp;quot;]
    /// </summary>
    public TerraformProperty<string>? Severity
    {
        get => GetProperty<TerraformProperty<string>>("severity");
        set => this.WithProperty("severity", value);
    }

    /// <summary>
    /// This field is intended to be used for organizing and identifying the AlertPolicy
    /// objects.The field can contain up to 64 entries. Each key and value is limited
    /// to 63 Unicode characters or 128 bytes, whichever is smaller. Labels and values
    /// can contain only lowercase letters, numerals, underscores, and dashes. Keys
    /// must begin with a letter.
    /// </summary>
    public Dictionary<string, TerraformProperty<string>>? UserLabels
    {
        get => GetProperty<Dictionary<string, TerraformProperty<string>>>("user_labels");
        set => this.WithProperty("user_labels", value);
    }

    /// <summary>
    /// Block for alert_strategy.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 AlertStrategy block(s) allowed")]
    public List<GoogleMonitoringAlertPolicyAlertStrategyBlock>? AlertStrategy
    {
        get => GetProperty<List<GoogleMonitoringAlertPolicyAlertStrategyBlock>>("alert_strategy");
        set => this.WithProperty("alert_strategy", value);
    }

    /// <summary>
    /// Block for conditions.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 Conditions block(s) required")]
    public List<GoogleMonitoringAlertPolicyConditionsBlock>? Conditions
    {
        get => GetProperty<List<GoogleMonitoringAlertPolicyConditionsBlock>>("conditions");
        set => this.WithProperty("conditions", value);
    }

    /// <summary>
    /// Block for documentation.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 Documentation block(s) allowed")]
    public List<GoogleMonitoringAlertPolicyDocumentationBlock>? Documentation
    {
        get => GetProperty<List<GoogleMonitoringAlertPolicyDocumentationBlock>>("documentation");
        set => this.WithProperty("documentation", value);
    }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    public GoogleMonitoringAlertPolicyTimeoutsBlock? Timeouts
    {
        get => GetProperty<GoogleMonitoringAlertPolicyTimeoutsBlock>("timeouts");
        set => this.WithProperty("timeouts", value);
    }

    /// <summary>
    /// A read-only record of the creation of the alerting policy.
    /// If provided in a call to create or update, this field will
    /// be ignored.
    /// </summary>
    public TerraformExpression CreationRecord => this["creation_record"];

    /// <summary>
    /// The unique resource name for this policy.
    /// Its syntax is: projects/[PROJECT_ID]/alertPolicies/[ALERT_POLICY_ID]
    /// </summary>
    public TerraformExpression Name => this["name"];

}
