using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for access_settings in .
/// Nesting mode: list
/// </summary>
public class GoogleIapSettingsAccessSettingsBlock : TerraformBlock
{
    /// <summary>
    /// Identity sources that IAP can use to authenticate the end user. Only one identity source
    /// can be configured. The possible values are:
    /// 
    /// * &#39;WORKFORCE_IDENTITY_FEDERATION&#39;: Use external identities set up on Google Cloud Workforce
    ///   				     Identity Federation. Possible values: [&amp;quot;WORKFORCE_IDENTITY_FEDERATION&amp;quot;]
    /// </summary>
    public List<TerraformProperty<string>>? IdentitySources
    {
        get => GetProperty<List<TerraformProperty<string>>>("identity_sources");
        set => WithProperty("identity_sources", value);
    }

}

/// <summary>
/// Block type for application_settings in .
/// Nesting mode: list
/// </summary>
public class GoogleIapSettingsApplicationSettingsBlock : TerraformBlock
{
    /// <summary>
    /// The Domain value to set for cookies generated by IAP. This value is not validated by the API,
    /// but will be ignored at runtime if invalid.
    /// </summary>
    public TerraformProperty<string>? CookieDomain
    {
        get => GetProperty<TerraformProperty<string>>("cookie_domain");
        set => WithProperty("cookie_domain", value);
    }

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleIapSettingsTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformProperty<string>? Create
    {
        get => GetProperty<TerraformProperty<string>>("create");
        set => WithProperty("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformProperty<string>? Delete
    {
        get => GetProperty<TerraformProperty<string>>("delete");
        set => WithProperty("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformProperty<string>? Update
    {
        get => GetProperty<TerraformProperty<string>>("update");
        set => WithProperty("update", value);
    }

}

/// <summary>
/// Manages a google_iap_settings resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public class GoogleIapSettings : TerraformResource
{
    public GoogleIapSettings(string name) : base("google_iap_settings", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformProperty<string>? Id
    {
        get => GetProperty<TerraformProperty<string>>("id");
        set => this.WithProperty("id", value);
    }

    /// <summary>
    /// The resource name of the IAP protected resource. Name can have below resources:
    /// * organizations/{organization_id}
    /// * folders/{folder_id}
    /// * projects/{project_id}
    /// * projects/{project_id}/iap_web
    /// * projects/{project_id}/iap_web/compute
    /// * projects/{project_id}/iap_web/compute-{region}
    /// * projects/{project_id}/iap_web/compute/services/{service_id}
    /// * projects/{project_id}/iap_web/compute-{region}/services/{service_id}
    /// * projects/{project_id}/iap_web/appengine-{app_id}
    /// * projects/{project_id}/iap_web/appengine-{app_id}/services/{service_id}
    /// * projects/{project_id}/iap_web/appengine-{app_id}/services/{service_id}/version/{version_id}
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    public required TerraformProperty<string> Name
    {
        get => GetProperty<TerraformProperty<string>>("name");
        set => this.WithProperty("name", value);
    }

    /// <summary>
    /// Block for access_settings.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 AccessSettings block(s) allowed")]
    public List<GoogleIapSettingsAccessSettingsBlock>? AccessSettings
    {
        get => GetProperty<List<GoogleIapSettingsAccessSettingsBlock>>("access_settings");
        set => this.WithProperty("access_settings", value);
    }

    /// <summary>
    /// Block for application_settings.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ApplicationSettings block(s) allowed")]
    public List<GoogleIapSettingsApplicationSettingsBlock>? ApplicationSettings
    {
        get => GetProperty<List<GoogleIapSettingsApplicationSettingsBlock>>("application_settings");
        set => this.WithProperty("application_settings", value);
    }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    public GoogleIapSettingsTimeoutsBlock? Timeouts
    {
        get => GetProperty<GoogleIapSettingsTimeoutsBlock>("timeouts");
        set => this.WithProperty("timeouts", value);
    }

}
