using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleEndpointsServiceTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformProperty<string>? Create
    {
        get => GetProperty<TerraformProperty<string>>("create");
        set => WithProperty("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformProperty<string>? Delete
    {
        get => GetProperty<TerraformProperty<string>>("delete");
        set => WithProperty("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformProperty<string>? Update
    {
        get => GetProperty<TerraformProperty<string>>("update");
        set => WithProperty("update", value);
    }

}

/// <summary>
/// Manages a google_endpoints_service resource.
/// </summary>
public class GoogleEndpointsService : TerraformResource
{
    public GoogleEndpointsService(string name) : base("google_endpoints_service", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("apis");
        this.DeclareOutput("config_id");
        this.DeclareOutput("dns_address");
        this.DeclareOutput("endpoints");
    }

    /// <summary>
    /// The full text of the Service Config YAML file (Example located here). If provided, must also provide protoc_output_base64. open_api config must not be provided.
    /// </summary>
    public TerraformProperty<string>? GrpcConfig
    {
        get => GetProperty<TerraformProperty<string>>("grpc_config");
        set => this.WithProperty("grpc_config", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformProperty<string>? Id
    {
        get => GetProperty<TerraformProperty<string>>("id");
        set => this.WithProperty("id", value);
    }

    /// <summary>
    /// The full text of the OpenAPI YAML configuration as described here. Either this, or both of grpc_config and protoc_output_base64 must be specified.
    /// </summary>
    public TerraformProperty<string>? OpenapiConfig
    {
        get => GetProperty<TerraformProperty<string>>("openapi_config");
        set => this.WithProperty("openapi_config", value);
    }

    /// <summary>
    /// The project ID that the service belongs to. If not provided, provider project is used.
    /// </summary>
    public TerraformProperty<string>? Project
    {
        get => GetProperty<TerraformProperty<string>>("project");
        set => this.WithProperty("project", value);
    }

    /// <summary>
    /// The full contents of the Service Descriptor File generated by protoc. This should be a compiled .pb file, base64-encoded.
    /// </summary>
    public TerraformProperty<string>? ProtocOutputBase64
    {
        get => GetProperty<TerraformProperty<string>>("protoc_output_base64");
        set => this.WithProperty("protoc_output_base64", value);
    }

    /// <summary>
    /// The name of the service. Usually of the form $apiname.endpoints.$projectid.cloud.goog.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "ServiceName is required")]
    public required TerraformProperty<string> ServiceName
    {
        get => GetRequiredProperty<TerraformProperty<string>>("service_name");
        set => this.WithProperty("service_name", value);
    }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    public GoogleEndpointsServiceTimeoutsBlock? Timeouts
    {
        get => GetProperty<GoogleEndpointsServiceTimeoutsBlock>("timeouts");
        set => this.WithProperty("timeouts", value);
    }

    /// <summary>
    /// A list of API objects.
    /// </summary>
    public TerraformExpression Apis => this["apis"];

    /// <summary>
    /// The autogenerated ID for the configuration that is rolled out as part of the creation of this resource. Must be provided to compute engine instances as a tag.
    /// </summary>
    public TerraformExpression ConfigId => this["config_id"];

    /// <summary>
    /// The address at which the service can be found - usually the same as the service name.
    /// </summary>
    public TerraformExpression DnsAddress => this["dns_address"];

    /// <summary>
    /// A list of Endpoint objects.
    /// </summary>
    public TerraformExpression Endpoints => this["endpoints"];

}
