using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Manages a google_identity_platform_tenant resource.
/// </summary>
public class GoogleIdentityPlatformTenant : TerraformResource
{
    public GoogleIdentityPlatformTenant(string name) : base("google_identity_platform_tenant", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("name");
    }

    /// <summary>
    /// Whether to allow email/password user authentication.
    /// </summary>
    public TerraformLiteralProperty<bool>? AllowPasswordSignup
    {
        get => GetProperty<TerraformLiteralProperty<bool>>("allow_password_signup");
        set => this.WithProperty("allow_password_signup", value);
    }

    /// <summary>
    /// Whether authentication is disabled for the tenant. If true, the users under
    /// the disabled tenant are not allowed to sign-in. Admins of the disabled tenant
    /// are not able to manage its users.
    /// </summary>
    public TerraformLiteralProperty<bool>? DisableAuth
    {
        get => GetProperty<TerraformLiteralProperty<bool>>("disable_auth");
        set => this.WithProperty("disable_auth", value);
    }

    /// <summary>
    /// Human friendly display name of the tenant.
    /// </summary>
    public TerraformLiteralProperty<string>? DisplayName
    {
        get => GetProperty<TerraformLiteralProperty<string>>("display_name");
        set => this.WithProperty("display_name", value);
    }

    /// <summary>
    /// Whether to enable email link user authentication.
    /// </summary>
    public TerraformLiteralProperty<bool>? EnableEmailLinkSignin
    {
        get => GetProperty<TerraformLiteralProperty<bool>>("enable_email_link_signin");
        set => this.WithProperty("enable_email_link_signin", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? Id
    {
        get => GetProperty<TerraformLiteralProperty<string>>("id");
        set => this.WithProperty("id", value);
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? Project
    {
        get => GetProperty<TerraformLiteralProperty<string>>("project");
        set => this.WithProperty("project", value);
    }

    /// <summary>
    /// The name of the tenant that is generated by the server
    /// </summary>
    public TerraformExpression Name => this["name"];

}
