using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for custom_config in .
/// Nesting mode: list
/// </summary>
public class GoogleSccOrganizationCustomModuleCustomConfigBlock : TerraformBlock
{
    /// <summary>
    /// Text that describes the vulnerability or misconfiguration that the custom
    /// module detects. This explanation is returned with each finding instance to
    /// help investigators understand the detected issue. The text must be enclosed in quotation marks.
    /// </summary>
    public TerraformProperty<string>? Description
    {
        get => GetProperty<TerraformProperty<string>>("description");
        set => WithProperty("description", value);
    }

    /// <summary>
    /// An explanation of the recommended steps that security teams can take to resolve
    /// the detected issue. This explanation is returned with each finding generated by
    /// this module in the nextSteps property of the finding JSON.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Recommendation is required")]
    public required TerraformProperty<string> Recommendation
    {
        get => GetRequiredProperty<TerraformProperty<string>>("recommendation");
        set => WithProperty("recommendation", value);
    }

    /// <summary>
    /// The severity to assign to findings generated by the module. Possible values: [&amp;quot;CRITICAL&amp;quot;, &amp;quot;HIGH&amp;quot;, &amp;quot;MEDIUM&amp;quot;, &amp;quot;LOW&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Severity is required")]
    public required TerraformProperty<string> Severity
    {
        get => GetRequiredProperty<TerraformProperty<string>>("severity");
        set => WithProperty("severity", value);
    }

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleSccOrganizationCustomModuleTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformProperty<string>? Create
    {
        get => GetProperty<TerraformProperty<string>>("create");
        set => WithProperty("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformProperty<string>? Delete
    {
        get => GetProperty<TerraformProperty<string>>("delete");
        set => WithProperty("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformProperty<string>? Update
    {
        get => GetProperty<TerraformProperty<string>>("update");
        set => WithProperty("update", value);
    }

}

/// <summary>
/// Manages a google_scc_organization_custom_module resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public class GoogleSccOrganizationCustomModule : TerraformResource
{
    public GoogleSccOrganizationCustomModule(string name) : base("google_scc_organization_custom_module", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("ancestor_module");
        this.DeclareOutput("last_editor");
        this.DeclareOutput("name");
        this.DeclareOutput("update_time");
    }

    /// <summary>
    /// The display name of the Security Health Analytics custom module. This
    /// display name becomes the finding category for all findings that are
    /// returned by this custom module. The display name must be between 1 and
    /// 128 characters, start with a lowercase letter, and contain alphanumeric
    /// characters or underscores only.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "DisplayName is required")]
    public required TerraformProperty<string> DisplayName
    {
        get => GetRequiredProperty<TerraformProperty<string>>("display_name");
        set => this.WithProperty("display_name", value);
    }

    /// <summary>
    /// The enablement state of the custom module. Possible values: [&amp;quot;ENABLED&amp;quot;, &amp;quot;DISABLED&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "EnablementState is required")]
    public required TerraformProperty<string> EnablementState
    {
        get => GetRequiredProperty<TerraformProperty<string>>("enablement_state");
        set => this.WithProperty("enablement_state", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformProperty<string>? Id
    {
        get => GetProperty<TerraformProperty<string>>("id");
        set => this.WithProperty("id", value);
    }

    /// <summary>
    /// Numerical ID of the parent organization.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Organization is required")]
    public required TerraformProperty<string> Organization
    {
        get => GetRequiredProperty<TerraformProperty<string>>("organization");
        set => this.WithProperty("organization", value);
    }

    /// <summary>
    /// Block for custom_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MinLength(1, ErrorMessage = "At least 1 CustomConfig block(s) required")]
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 CustomConfig block(s) allowed")]
    public List<GoogleSccOrganizationCustomModuleCustomConfigBlock>? CustomConfig
    {
        get => GetProperty<List<GoogleSccOrganizationCustomModuleCustomConfigBlock>>("custom_config");
        set => this.WithProperty("custom_config", value);
    }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    public GoogleSccOrganizationCustomModuleTimeoutsBlock? Timeouts
    {
        get => GetProperty<GoogleSccOrganizationCustomModuleTimeoutsBlock>("timeouts");
        set => this.WithProperty("timeouts", value);
    }

    /// <summary>
    /// If empty, indicates that the custom module was created in the organization, folder,
    /// or project in which you are viewing the custom module. Otherwise, ancestor_module
    /// specifies the organization or folder from which the custom module is inherited.
    /// </summary>
    public TerraformExpression AncestorModule => this["ancestor_module"];

    /// <summary>
    /// The editor that last updated the custom module.
    /// </summary>
    public TerraformExpression LastEditor => this["last_editor"];

    /// <summary>
    /// The resource name of the custom module. Its format is &amp;quot;organizations/{org_id}/securityHealthAnalyticsSettings/customModules/{customModule}&amp;quot;.
    /// The id {customModule} is server-generated and is not user settable. It will be a numeric id containing 1-20 digits.
    /// </summary>
    public TerraformExpression Name => this["name"];

    /// <summary>
    /// The time at which the custom module was last updated.
    /// 
    /// A timestamp in RFC3339 UTC &amp;quot;Zulu&amp;quot; format, with nanosecond resolution and
    /// up to nine fractional digits. Examples: &amp;quot;2014-10-02T15:01:23Z&amp;quot; and &amp;quot;2014-10-02T15:01:23.045123456Z&amp;quot;.
    /// </summary>
    public TerraformExpression UpdateTime => this["update_time"];

}
