using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GooglePublicCaExternalAccountKeyTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformProperty<string>? Create
    {
        get => GetProperty<TerraformProperty<string>>("create");
        set => WithProperty("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformProperty<string>? Delete
    {
        get => GetProperty<TerraformProperty<string>>("delete");
        set => WithProperty("delete", value);
    }

}

/// <summary>
/// Manages a google_public_ca_external_account_key resource.
/// </summary>
public class GooglePublicCaExternalAccountKey : TerraformResource
{
    public GooglePublicCaExternalAccountKey(string name) : base("google_public_ca_external_account_key", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("b64_mac_key");
        this.DeclareOutput("b64url_mac_key");
        this.DeclareOutput("key_id");
        this.DeclareOutput("name");
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformProperty<string>? Id
    {
        get => GetProperty<TerraformProperty<string>>("id");
        set => this.WithProperty("id", value);
    }

    /// <summary>
    /// Location for the externalAccountKey. Currently only &#39;global&#39; is supported.
    /// </summary>
    public TerraformProperty<string>? Location
    {
        get => GetProperty<TerraformProperty<string>>("location");
        set => this.WithProperty("location", value);
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public TerraformProperty<string>? Project
    {
        get => GetProperty<TerraformProperty<string>>("project");
        set => this.WithProperty("project", value);
    }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    public GooglePublicCaExternalAccountKeyTimeoutsBlock? Timeouts
    {
        get => GetProperty<GooglePublicCaExternalAccountKeyTimeoutsBlock>("timeouts");
        set => this.WithProperty("timeouts", value);
    }

    /// <summary>
    /// Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService
    /// when the ExternalAccountKey is created.
    /// </summary>
    public TerraformExpression B64MacKey => this["b64_mac_key"];

    /// <summary>
    /// Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService
    /// when the ExternalAccountKey is created.&#39;
    /// </summary>
    public TerraformExpression B64urlMacKey => this["b64url_mac_key"];

    /// <summary>
    /// It is generated by the PublicCertificateAuthorityService when the ExternalAccountKey is created.
    /// </summary>
    public TerraformExpression KeyId => this["key_id"];

    /// <summary>
    /// Resource name. projects/{project}/locations/{location}/externalAccountKeys/{keyId}.
    /// </summary>
    public TerraformExpression Name => this["name"];

}
