using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Block type for backup_config in .
/// Nesting mode: list
/// </summary>
public class GoogleNetappVolumeBackupConfigBlock : TerraformBlock
{
    /// <summary>
    /// Specify a single backup policy ID for scheduled backups. Format: &#39;projects/{{projectId}}/locations/{{location}}/backupPolicies/{{backupPolicyName}}&#39;
    /// </summary>
    public List<TerraformProperty<string>>? BackupPolicies
    {
        get => GetProperty<List<TerraformProperty<string>>>("backup_policies");
        set => WithProperty("backup_policies", value);
    }

    /// <summary>
    /// ID of the backup vault to use. A backup vault is reqired to create manual or scheduled backups.
    /// Format: &#39;projects/{{projectId}}/locations/{{location}}/backupVaults/{{backupVaultName}}&#39;
    /// </summary>
    public TerraformProperty<string>? BackupVault
    {
        get => GetProperty<TerraformProperty<string>>("backup_vault");
        set => WithProperty("backup_vault", value);
    }

    /// <summary>
    /// When set to true, scheduled backup is enabled on the volume. Omit if no backup_policy is specified.
    /// </summary>
    public TerraformProperty<bool>? ScheduledBackupEnabled
    {
        get => GetProperty<TerraformProperty<bool>>("scheduled_backup_enabled");
        set => WithProperty("scheduled_backup_enabled", value);
    }

}

/// <summary>
/// Block type for block_devices in .
/// Nesting mode: list
/// </summary>
public class GoogleNetappVolumeBlockDevicesBlock : TerraformBlock
{
    /// <summary>
    /// A list of host groups that identify hosts that can mount the block volume.
    /// Format:
    /// &#39;projects/{project_id}/locations/{location}/hostGroups/{host_group_id}&#39;
    /// This field can be updated after the block device is created.
    /// </summary>
    public List<TerraformProperty<string>>? HostGroups
    {
        get => GetProperty<List<TerraformProperty<string>>>("host_groups");
        set => WithProperty("host_groups", value);
    }

    /// <summary>
    /// Device identifier of the Block volume. This represents lun_serial_number
    /// for ISCSI volumes
    /// </summary>
    public TerraformProperty<string>? Identifier
    {
        get => GetProperty<TerraformProperty<string>>("identifier");
        set => WithProperty("identifier", value);
    }

    /// <summary>
    /// User-defined name for the block device, unique within the Volume. In case
    /// no user input is provided, name will be autogenerated in the backend.
    /// The name must meet the following requirements:
    /// *   Be between 1 and 255 characters long.
    /// *   Contain only uppercase or lowercase letters (A-Z, a-z), numbers (0-9),
    ///     and the following special characters: &amp;quot;-&amp;quot;, &amp;quot;_&amp;quot;, &amp;quot;}&amp;quot;, &amp;quot;{&amp;quot;, &amp;quot;.&amp;quot;.
    /// *   Spaces are not allowed.
    /// </summary>
    public TerraformProperty<string>? Name
    {
        get => GetProperty<TerraformProperty<string>>("name");
        set => WithProperty("name", value);
    }

    /// <summary>
    /// The OS type of the volume.
    /// This field can&#39;t be changed after the block device is created. Possible values: [&amp;quot;LINUX&amp;quot;, &amp;quot;WINDOWS&amp;quot;, &amp;quot;ESXI&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "OsType is required")]
    public required TerraformProperty<string> OsType
    {
        get => GetProperty<TerraformProperty<string>>("os_type");
        set => WithProperty("os_type", value);
    }

    /// <summary>
    /// The size of the block device in GiB.
    /// Any value provided in this field during Volume creation is IGNORED.
    /// The block device&#39;s size is system-managed and will be set to match
    /// the parent Volume&#39;s &#39;capacity_gib&#39;.
    /// </summary>
    public TerraformProperty<double>? SizeGib
    {
        get => GetProperty<TerraformProperty<double>>("size_gib");
        set => WithProperty("size_gib", value);
    }

}

/// <summary>
/// Block type for export_policy in .
/// Nesting mode: list
/// </summary>
public class GoogleNetappVolumeExportPolicyBlock : TerraformBlock
{
}

/// <summary>
/// Block type for hybrid_replication_parameters in .
/// Nesting mode: list
/// </summary>
public class GoogleNetappVolumeHybridReplicationParametersBlock : TerraformBlock
{
    /// <summary>
    /// Optional. Name of source cluster location associated with the Hybrid replication. This is a free-form field for the display purpose only.
    /// </summary>
    public TerraformProperty<string>? ClusterLocation
    {
        get => GetProperty<TerraformProperty<string>>("cluster_location");
        set => WithProperty("cluster_location", value);
    }

    /// <summary>
    /// Optional. Description of the replication.
    /// </summary>
    public TerraformProperty<string>? Description
    {
        get => GetProperty<TerraformProperty<string>>("description");
        set => WithProperty("description", value);
    }

    /// <summary>
    /// Optional. Type of the volume&#39;s hybrid replication. Possible values: [&amp;quot;MIGRATION&amp;quot;, &amp;quot;CONTINUOUS_REPLICATION&amp;quot;, &amp;quot;ONPREM_REPLICATION&amp;quot;, &amp;quot;REVERSE_ONPREM_REPLICATION&amp;quot;]
    /// </summary>
    public TerraformProperty<string>? HybridReplicationType
    {
        get => GetProperty<TerraformProperty<string>>("hybrid_replication_type");
        set => WithProperty("hybrid_replication_type", value);
    }

    /// <summary>
    /// Optional. Labels to be added to the replication as the key value pairs.
    /// An object containing a list of &amp;quot;key&amp;quot;: value pairs. Example: { &amp;quot;name&amp;quot;: &amp;quot;wrench&amp;quot;, &amp;quot;mass&amp;quot;: &amp;quot;1.3kg&amp;quot;, &amp;quot;count&amp;quot;: &amp;quot;3&amp;quot; }.
    /// </summary>
    public Dictionary<string, TerraformProperty<string>>? Labels
    {
        get => GetProperty<Dictionary<string, TerraformProperty<string>>>("labels");
        set => WithProperty("labels", value);
    }

    /// <summary>
    /// Optional. Constituent volume count for large volume.
    /// </summary>
    public TerraformProperty<double>? LargeVolumeConstituentCount
    {
        get => GetProperty<TerraformProperty<double>>("large_volume_constituent_count");
        set => WithProperty("large_volume_constituent_count", value);
    }

    /// <summary>
    /// Required. Name of the user&#39;s local source cluster to be peered with the destination cluster.
    /// </summary>
    public TerraformProperty<string>? PeerClusterName
    {
        get => GetProperty<TerraformProperty<string>>("peer_cluster_name");
        set => WithProperty("peer_cluster_name", value);
    }

    /// <summary>
    /// Required. List of node ip addresses to be peered with.
    /// </summary>
    public List<TerraformProperty<string>>? PeerIpAddresses
    {
        get => GetProperty<List<TerraformProperty<string>>>("peer_ip_addresses");
        set => WithProperty("peer_ip_addresses", value);
    }

    /// <summary>
    /// Required. Name of the user&#39;s local source vserver svm to be peered with the destination vserver svm.
    /// </summary>
    public TerraformProperty<string>? PeerSvmName
    {
        get => GetProperty<TerraformProperty<string>>("peer_svm_name");
        set => WithProperty("peer_svm_name", value);
    }

    /// <summary>
    /// Required. Name of the user&#39;s local source volume to be peered with the destination volume.
    /// </summary>
    public TerraformProperty<string>? PeerVolumeName
    {
        get => GetProperty<TerraformProperty<string>>("peer_volume_name");
        set => WithProperty("peer_volume_name", value);
    }

    /// <summary>
    /// Required. Desired name for the replication of this volume.
    /// </summary>
    public TerraformProperty<string>? Replication
    {
        get => GetProperty<TerraformProperty<string>>("replication");
        set => WithProperty("replication", value);
    }

    /// <summary>
    /// Optional. Replication Schedule for the replication created. Possible values: [&amp;quot;EVERY_10_MINUTES&amp;quot;, &amp;quot;HOURLY&amp;quot;, &amp;quot;DAILY&amp;quot;]
    /// </summary>
    public TerraformProperty<string>? ReplicationSchedule
    {
        get => GetProperty<TerraformProperty<string>>("replication_schedule");
        set => WithProperty("replication_schedule", value);
    }

}

/// <summary>
/// Block type for restore_parameters in .
/// Nesting mode: list
/// </summary>
public class GoogleNetappVolumeRestoreParametersBlock : TerraformBlock
{
    /// <summary>
    /// Full name of the backup to use for creating this volume.
    /// &#39;source_snapshot&#39; and &#39;source_backup&#39; cannot be used simultaneously.
    /// Format: &#39;projects/{{project}}/locations/{{location}}/backupVaults/{{backupVaultId}}/backups/{{backup}}&#39;.
    /// </summary>
    public TerraformProperty<string>? SourceBackup
    {
        get => GetProperty<TerraformProperty<string>>("source_backup");
        set => WithProperty("source_backup", value);
    }

    /// <summary>
    /// Full name of the snapshot to use for creating this volume.
    /// &#39;source_snapshot&#39; and &#39;source_backup&#39; cannot be used simultaneously.
    /// Format: &#39;projects/{{project}}/locations/{{location}}/volumes/{{volume}}/snapshots/{{snapshot}}&#39;.
    /// </summary>
    public TerraformProperty<string>? SourceSnapshot
    {
        get => GetProperty<TerraformProperty<string>>("source_snapshot");
        set => WithProperty("source_snapshot", value);
    }

}

/// <summary>
/// Block type for snapshot_policy in .
/// Nesting mode: list
/// </summary>
public class GoogleNetappVolumeSnapshotPolicyBlock : TerraformBlock
{
    /// <summary>
    /// Enables automated snapshot creation according to defined schedule. Default is false.
    /// To disable automatic snapshot creation you have to remove the whole snapshot_policy block.
    /// </summary>
    public TerraformProperty<bool>? Enabled
    {
        get => GetProperty<TerraformProperty<bool>>("enabled");
        set => WithProperty("enabled", value);
    }

}

/// <summary>
/// Block type for tiering_policy in .
/// Nesting mode: list
/// </summary>
public class GoogleNetappVolumeTieringPolicyBlock : TerraformBlock
{
    /// <summary>
    /// Optional. Time in days to mark the volume&#39;s data block as cold and make it eligible for tiering, can be range from 2-183.
    /// Default is 31.
    /// </summary>
    public TerraformProperty<double>? CoolingThresholdDays
    {
        get => GetProperty<TerraformProperty<double>>("cooling_threshold_days");
        set => WithProperty("cooling_threshold_days", value);
    }

    /// <summary>
    /// Optional. Flag indicating that the hot tier bypass mode is enabled. Default is false.
    /// Only applicable to Flex service level.
    /// </summary>
    public TerraformProperty<bool>? HotTierBypassModeEnabled
    {
        get => GetProperty<TerraformProperty<bool>>("hot_tier_bypass_mode_enabled");
        set => WithProperty("hot_tier_bypass_mode_enabled", value);
    }

    /// <summary>
    /// Optional. Flag indicating if the volume has tiering policy enable/pause. Default is PAUSED. Default value: &amp;quot;PAUSED&amp;quot; Possible values: [&amp;quot;ENABLED&amp;quot;, &amp;quot;PAUSED&amp;quot;]
    /// </summary>
    public TerraformProperty<string>? TierAction
    {
        get => GetProperty<TerraformProperty<string>>("tier_action");
        set => WithProperty("tier_action", value);
    }

}

/// <summary>
/// Block type for timeouts in .
/// Nesting mode: single
/// </summary>
public class GoogleNetappVolumeTimeoutsBlock : TerraformBlock
{
    /// <summary>
    /// The create attribute.
    /// </summary>
    public TerraformProperty<string>? Create
    {
        get => GetProperty<TerraformProperty<string>>("create");
        set => WithProperty("create", value);
    }

    /// <summary>
    /// The delete attribute.
    /// </summary>
    public TerraformProperty<string>? Delete
    {
        get => GetProperty<TerraformProperty<string>>("delete");
        set => WithProperty("delete", value);
    }

    /// <summary>
    /// The update attribute.
    /// </summary>
    public TerraformProperty<string>? Update
    {
        get => GetProperty<TerraformProperty<string>>("update");
        set => WithProperty("update", value);
    }

}

/// <summary>
/// Manages a google_netapp_volume resource.
/// </summary>
[System.Diagnostics.CodeAnalysis.RequiresUnreferencedCode("This class uses MinLength/MaxLength validation attributes which use reflection.")]
public class GoogleNetappVolume : TerraformResource
{
    public GoogleNetappVolume(string name) : base("google_netapp_volume", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
        this.DeclareOutput("active_directory");
        this.DeclareOutput("cold_tier_size_gib");
        this.DeclareOutput("create_time");
        this.DeclareOutput("effective_labels");
        this.DeclareOutput("encryption_type");
        this.DeclareOutput("has_replication");
        this.DeclareOutput("hot_tier_size_used_gib");
        this.DeclareOutput("kms_config");
        this.DeclareOutput("ldap_enabled");
        this.DeclareOutput("mount_options");
        this.DeclareOutput("network");
        this.DeclareOutput("psa_range");
        this.DeclareOutput("replica_zone");
        this.DeclareOutput("service_level");
        this.DeclareOutput("state");
        this.DeclareOutput("state_details");
        this.DeclareOutput("terraform_labels");
        this.DeclareOutput("used_gib");
        this.DeclareOutput("zone");
    }

    /// <summary>
    /// Capacity of the volume (in GiB).
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "CapacityGib is required")]
    public required TerraformProperty<string> CapacityGib
    {
        get => GetProperty<TerraformProperty<string>>("capacity_gib");
        set => this.WithProperty("capacity_gib", value);
    }

    /// <summary>
    /// Policy to determine if the volume should be deleted forcefully.
    /// Volumes may have nested snapshot resources. Deleting such a volume will fail.
    /// Setting this parameter to FORCE will delete volumes including nested snapshots.
    /// Possible values: DEFAULT, FORCE.
    /// </summary>
    public TerraformProperty<string>? DeletionPolicy
    {
        get => GetProperty<TerraformProperty<string>>("deletion_policy");
        set => this.WithProperty("deletion_policy", value);
    }

    /// <summary>
    /// An optional description of this resource.
    /// </summary>
    public TerraformProperty<string>? Description
    {
        get => GetProperty<TerraformProperty<string>>("description");
        set => this.WithProperty("description", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformProperty<string>? Id
    {
        get => GetProperty<TerraformProperty<string>>("id");
        set => this.WithProperty("id", value);
    }

    /// <summary>
    /// Flag indicating if the volume is a kerberos volume or not, export policy rules control kerberos security modes (krb5, krb5i, krb5p).
    /// </summary>
    public TerraformProperty<bool>? KerberosEnabled
    {
        get => GetProperty<TerraformProperty<bool>>("kerberos_enabled");
        set => this.WithProperty("kerberos_enabled", value);
    }

    /// <summary>
    /// Labels as key value pairs. Example: &#39;{ &amp;quot;owner&amp;quot;: &amp;quot;Bob&amp;quot;, &amp;quot;department&amp;quot;: &amp;quot;finance&amp;quot;, &amp;quot;purpose&amp;quot;: &amp;quot;testing&amp;quot; }&#39;.
    /// 
    /// 
    /// **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
    /// Please refer to the field &#39;effective_labels&#39; for all of the labels present on the resource.
    /// </summary>
    public Dictionary<string, TerraformProperty<string>>? Labels
    {
        get => GetProperty<Dictionary<string, TerraformProperty<string>>>("labels");
        set => this.WithProperty("labels", value);
    }

    /// <summary>
    /// Optional. Flag indicating if the volume will be a large capacity volume or a regular volume.
    /// </summary>
    public TerraformProperty<bool>? LargeCapacity
    {
        get => GetProperty<TerraformProperty<bool>>("large_capacity");
        set => this.WithProperty("large_capacity", value);
    }

    /// <summary>
    /// Name of the pool location. Usually a region name, expect for some STANDARD service level pools which require a zone name.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Location is required")]
    public required TerraformProperty<string> Location
    {
        get => GetProperty<TerraformProperty<string>>("location");
        set => this.WithProperty("location", value);
    }

    /// <summary>
    /// Optional. Flag indicating if the volume will have an IP address per node for volumes supporting multiple IP endpoints.
    /// Only the volume with largeCapacity will be allowed to have multiple endpoints.
    /// </summary>
    public TerraformProperty<bool>? MultipleEndpoints
    {
        get => GetProperty<TerraformProperty<bool>>("multiple_endpoints");
        set => this.WithProperty("multiple_endpoints", value);
    }

    /// <summary>
    /// The name of the volume. Needs to be unique per location.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    public required TerraformProperty<string> Name
    {
        get => GetProperty<TerraformProperty<string>>("name");
        set => this.WithProperty("name", value);
    }

    /// <summary>
    /// The project attribute.
    /// </summary>
    public TerraformProperty<string>? Project
    {
        get => GetProperty<TerraformProperty<string>>("project");
        set => this.WithProperty("project", value);
    }

    /// <summary>
    /// The protocol of the volume. Allowed combinations are &#39;[&#39;NFSV3&#39;]&#39;, &#39;[&#39;NFSV4&#39;]&#39;, &#39;[&#39;SMB&#39;]&#39;, &#39;[&#39;NFSV3&#39;, &#39;NFSV4&#39;]&#39;, &#39;[&#39;SMB&#39;, &#39;NFSV3&#39;]&#39; and &#39;[&#39;SMB&#39;, &#39;NFSV4&#39;]&#39;. Possible values: [&amp;quot;NFSV3&amp;quot;, &amp;quot;NFSV4&amp;quot;, &amp;quot;SMB&amp;quot;, &amp;quot;ISCSI&amp;quot;]
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Protocols is required")]
    public List<TerraformProperty<string>>? Protocols
    {
        get => GetProperty<List<TerraformProperty<string>>>("protocols");
        set => this.WithProperty("protocols", value);
    }

    /// <summary>
    /// List of actions that are restricted on this volume. Possible values: [&amp;quot;DELETE&amp;quot;]
    /// </summary>
    public List<TerraformProperty<string>>? RestrictedActions
    {
        get => GetProperty<List<TerraformProperty<string>>>("restricted_actions");
        set => this.WithProperty("restricted_actions", value);
    }

    /// <summary>
    /// Security Style of the Volume. Use UNIX to use UNIX or NFSV4 ACLs for file permissions.
    /// Use NTFS to use NTFS ACLs for file permissions. Can only be set for volumes which use SMB together with NFS as protocol. Possible values: [&amp;quot;NTFS&amp;quot;, &amp;quot;UNIX&amp;quot;]
    /// </summary>
    public TerraformProperty<string>? SecurityStyle
    {
        get => GetProperty<TerraformProperty<string>>("security_style");
        set => this.WithProperty("security_style", value);
    }

    /// <summary>
    /// Share name (SMB) or export path (NFS) of the volume. Needs to be unique per location.
    /// </summary>
    public TerraformProperty<string>? ShareName
    {
        get => GetProperty<TerraformProperty<string>>("share_name");
        set => this.WithProperty("share_name", value);
    }

    /// <summary>
    /// Settings for volumes with SMB access. Possible values: [&amp;quot;ENCRYPT_DATA&amp;quot;, &amp;quot;BROWSABLE&amp;quot;, &amp;quot;CHANGE_NOTIFY&amp;quot;, &amp;quot;NON_BROWSABLE&amp;quot;, &amp;quot;OPLOCKS&amp;quot;, &amp;quot;SHOW_SNAPSHOT&amp;quot;, &amp;quot;SHOW_PREVIOUS_VERSIONS&amp;quot;, &amp;quot;ACCESS_BASED_ENUMERATION&amp;quot;, &amp;quot;CONTINUOUSLY_AVAILABLE&amp;quot;]
    /// </summary>
    public List<TerraformProperty<string>>? SmbSettings
    {
        get => GetProperty<List<TerraformProperty<string>>>("smb_settings");
        set => this.WithProperty("smb_settings", value);
    }

    /// <summary>
    /// If enabled, a NFS volume will contain a read-only .snapshot directory which provides access to each of the volume&#39;s snapshots. Will enable &amp;quot;Previous Versions&amp;quot; support for SMB.
    /// </summary>
    public TerraformProperty<bool>? SnapshotDirectory
    {
        get => GetProperty<TerraformProperty<bool>>("snapshot_directory");
        set => this.WithProperty("snapshot_directory", value);
    }

    /// <summary>
    /// Name of the storage pool to create the volume in. Pool needs enough spare capacity to accommodate the volume.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "StoragePool is required")]
    public required TerraformProperty<string> StoragePool
    {
        get => GetProperty<TerraformProperty<string>>("storage_pool");
        set => this.WithProperty("storage_pool", value);
    }

    /// <summary>
    /// Optional. Custom Performance Total Throughput of the pool (in MiB/s).
    /// </summary>
    public TerraformProperty<double>? ThroughputMibps
    {
        get => GetProperty<TerraformProperty<double>>("throughput_mibps");
        set => this.WithProperty("throughput_mibps", value);
    }

    /// <summary>
    /// Unix permission the mount point will be created with. Default is 0770. Applicable for UNIX security style volumes only.
    /// </summary>
    public TerraformProperty<string>? UnixPermissions
    {
        get => GetProperty<TerraformProperty<string>>("unix_permissions");
        set => this.WithProperty("unix_permissions", value);
    }

    /// <summary>
    /// Block for backup_config.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 BackupConfig block(s) allowed")]
    public List<GoogleNetappVolumeBackupConfigBlock>? BackupConfig
    {
        get => GetProperty<List<GoogleNetappVolumeBackupConfigBlock>>("backup_config");
        set => this.WithProperty("backup_config", value);
    }

    /// <summary>
    /// Block for block_devices.
    /// Nesting mode: list
    /// </summary>
    public List<GoogleNetappVolumeBlockDevicesBlock>? BlockDevices
    {
        get => GetProperty<List<GoogleNetappVolumeBlockDevicesBlock>>("block_devices");
        set => this.WithProperty("block_devices", value);
    }

    /// <summary>
    /// Block for export_policy.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 ExportPolicy block(s) allowed")]
    public List<GoogleNetappVolumeExportPolicyBlock>? ExportPolicy
    {
        get => GetProperty<List<GoogleNetappVolumeExportPolicyBlock>>("export_policy");
        set => this.WithProperty("export_policy", value);
    }

    /// <summary>
    /// Block for hybrid_replication_parameters.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 HybridReplicationParameters block(s) allowed")]
    public List<GoogleNetappVolumeHybridReplicationParametersBlock>? HybridReplicationParameters
    {
        get => GetProperty<List<GoogleNetappVolumeHybridReplicationParametersBlock>>("hybrid_replication_parameters");
        set => this.WithProperty("hybrid_replication_parameters", value);
    }

    /// <summary>
    /// Block for restore_parameters.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 RestoreParameters block(s) allowed")]
    public List<GoogleNetappVolumeRestoreParametersBlock>? RestoreParameters
    {
        get => GetProperty<List<GoogleNetappVolumeRestoreParametersBlock>>("restore_parameters");
        set => this.WithProperty("restore_parameters", value);
    }

    /// <summary>
    /// Block for snapshot_policy.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 SnapshotPolicy block(s) allowed")]
    public List<GoogleNetappVolumeSnapshotPolicyBlock>? SnapshotPolicy
    {
        get => GetProperty<List<GoogleNetappVolumeSnapshotPolicyBlock>>("snapshot_policy");
        set => this.WithProperty("snapshot_policy", value);
    }

    /// <summary>
    /// Block for tiering_policy.
    /// Nesting mode: list
    /// </summary>
    [System.ComponentModel.DataAnnotations.MaxLength(1, ErrorMessage = "Maximum 1 TieringPolicy block(s) allowed")]
    public List<GoogleNetappVolumeTieringPolicyBlock>? TieringPolicy
    {
        get => GetProperty<List<GoogleNetappVolumeTieringPolicyBlock>>("tiering_policy");
        set => this.WithProperty("tiering_policy", value);
    }

    /// <summary>
    /// Block for timeouts.
    /// Nesting mode: single
    /// </summary>
    public GoogleNetappVolumeTimeoutsBlock? Timeouts
    {
        get => GetProperty<GoogleNetappVolumeTimeoutsBlock>("timeouts");
        set => this.WithProperty("timeouts", value);
    }

    /// <summary>
    /// Reports the resource name of the Active Directory policy being used. Inherited from storage pool.
    /// </summary>
    public TerraformExpression ActiveDirectory => this["active_directory"];

    /// <summary>
    /// Output only. Size of the volume cold tier data in GiB.
    /// </summary>
    public TerraformExpression ColdTierSizeGib => this["cold_tier_size_gib"];

    /// <summary>
    /// Create time of the volume. A timestamp in RFC3339 UTC &amp;quot;Zulu&amp;quot; format. Examples: &amp;quot;2023-06-22T09:13:01.617Z&amp;quot;.
    /// </summary>
    public TerraformExpression CreateTime => this["create_time"];

    /// <summary>
    /// All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.
    /// </summary>
    public TerraformExpression EffectiveLabels => this["effective_labels"];

    /// <summary>
    /// Reports the data-at-rest encryption type of the volume. Inherited from storage pool.
    /// </summary>
    public TerraformExpression EncryptionType => this["encryption_type"];

    /// <summary>
    /// Indicates whether the volume is part of a volume replication relationship.
    /// </summary>
    public TerraformExpression HasReplication => this["has_replication"];

    /// <summary>
    /// Total hot tier data rounded down to the nearest GiB used by the volume. This field is only used for flex Service Level
    /// </summary>
    public TerraformExpression HotTierSizeUsedGib => this["hot_tier_size_used_gib"];

    /// <summary>
    /// Reports the CMEK policy resurce name being used for volume encryption. Inherited from storage pool.
    /// </summary>
    public TerraformExpression KmsConfig => this["kms_config"];

    /// <summary>
    /// Flag indicating if the volume is NFS LDAP enabled or not. Inherited from storage pool.
    /// </summary>
    public TerraformExpression LdapEnabled => this["ldap_enabled"];

    /// <summary>
    /// Reports mount instructions for this volume.
    /// </summary>
    public TerraformExpression MountOptions => this["mount_options"];

    /// <summary>
    /// VPC network name with format: &#39;projects/{{project}}/global/networks/{{network}}&#39;. Inherited from storage pool.
    /// </summary>
    public TerraformExpression Network => this["network"];

    /// <summary>
    /// Name of the Private Service Access allocated range. Inherited from storage pool.
    /// </summary>
    public TerraformExpression PsaRange => this["psa_range"];

    /// <summary>
    /// Specifies the replica zone for regional volume.
    /// </summary>
    public TerraformExpression ReplicaZone => this["replica_zone"];

    /// <summary>
    /// Service level of the volume. Inherited from storage pool. Supported values are : PREMIUM, EXTREME, STANDARD, FLEX.
    /// </summary>
    public TerraformExpression ServiceLevel => this["service_level"];

    /// <summary>
    /// State of the volume.
    /// </summary>
    public TerraformExpression State => this["state"];

    /// <summary>
    /// State details of the volume.
    /// </summary>
    public TerraformExpression StateDetails => this["state_details"];

    /// <summary>
    /// The combination of labels configured directly on the resource
    ///  and default labels configured on the provider.
    /// </summary>
    public TerraformExpression TerraformLabels => this["terraform_labels"];

    /// <summary>
    /// Used capacity of the volume (in GiB). This is computed periodically and it does not represent the realtime usage.
    /// </summary>
    public TerraformExpression UsedGib => this["used_gib"];

    /// <summary>
    /// Specifies the active zone for regional volume.
    /// </summary>
    public TerraformExpression Zone => this["zone"];

}
