using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Google;

/// <summary>
/// Retrieves information about a google_cloud_run_service.
/// </summary>
public class GoogleCloudRunServiceDataSource : TerraformDataSource
{
    public GoogleCloudRunServiceDataSource(string name) : base("google_cloud_run_service", name)
    {
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    [TerraformPropertyName("id")]
    // Optional+Computed - use setter for literal value, or leave as computed reference
    public TerraformValue<string> Id { get; set; } = default!;

    /// <summary>
    /// The location of the cloud run instance. eg us-central1
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Location is required")]
    [TerraformPropertyName("location")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> Location { get; set; }

    /// <summary>
    /// Name must be unique within a Google Cloud project and region.
    /// Is required when creating resources. Name is primarily intended
    /// for creation idempotence and configuration definition. Cannot be updated.
    /// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Name is required")]
    [TerraformPropertyName("name")]
    // Required argument - user must set a value (no initializer for compile-time enforcement)
    public required TerraformValue<string> Name { get; set; }

    /// <summary>
    /// The project attribute.
    /// </summary>
    [TerraformPropertyName("project")]
    // Optional argument - user may or may not set a value
    public TerraformValue<string>? Project { get; set; }

    /// <summary>
    /// If set to &#39;true&#39;, the revision name (template.metadata.name) will be omitted and
    /// autogenerated by Cloud Run. This cannot be set to &#39;true&#39; while &#39;template.metadata.name&#39;
    /// is also set.
    /// (For legacy support, if &#39;template.metadata.name&#39; is unset in state while
    /// this field is set to false, the revision name will still autogenerate.)
    /// </summary>
    [TerraformPropertyName("autogenerate_revision_name")]
    // Output-only attribute - read-only reference
    public TerraformValue<bool> AutogenerateRevisionName => new TerraformReference(this, "autogenerate_revision_name");

    /// <summary>
    /// Metadata associated with this Service, including name, namespace, labels,
    /// and annotations.
    /// </summary>
    [TerraformPropertyName("metadata")]
    // Output-only attribute - read-only reference
    public TerraformList<object> Metadata => new TerraformReference(this, "metadata");

    /// <summary>
    /// The current status of the Service.
    /// </summary>
    [TerraformPropertyName("status")]
    // Output-only attribute - read-only reference
    public TerraformList<object> Status => new TerraformReference(this, "status");

    /// <summary>
    /// template holds the latest specification for the Revision to
    /// be stamped out. The template references the container image, and may also
    /// include labels and annotations that should be attached to the Revision.
    /// To correlate a Revision, and/or to force a Revision to be created when the
    /// spec doesn&#39;t otherwise change, a nonce label may be provided in the
    /// template metadata. For more details, see:
    /// https://github.com/knative/serving/blob/main/docs/client-conventions.md#associate-modifications-with-revisions
    /// 
    /// Cloud Run does not currently support referencing a build that is
    /// responsible for materializing the container image from source.
    /// </summary>
    [TerraformPropertyName("template")]
    // Output-only attribute - read-only reference
    public TerraformList<object> Template => new TerraformReference(this, "template");

    /// <summary>
    /// Traffic specifies how to distribute traffic over a collection of Knative Revisions
    /// and Configurations
    /// </summary>
    [TerraformPropertyName("traffic")]
    // Output-only attribute - read-only reference
    public TerraformList<object> Traffic => new TerraformReference(this, "traffic");

}
