using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.Random;

/// <summary>
/// Represents a random_bytes Terraform resource.
/// The resource `random_bytes` generates random bytes that are intended to be used as a secret, or key. Use this in preference to `random_id` when the output is considered sensitive, and should not be displayed in the CLI.
    /// 
    /// This resource *does* use a cryptographic random number generator.
/// </summary>
public partial class RandomBytes(string name) : TerraformResource("random_bytes", name)
{
    /// <summary>
    /// Arbitrary map of values that, when changed, will trigger recreation of resource. See [the main provider documentation](../index.html) for more information.
    /// </summary>
    public TerraformMap<string>? Keepers
    {
        get => GetArgument<TerraformMap<string>>("keepers");
        set => SetArgument("keepers", value);
    }

    /// <summary>
    /// The number of bytes requested. The minimum value for length is 1.
    /// </summary>
    [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "Length is required")]
    public required TerraformValue<double> Length
    {
        get => GetRequiredArgument<TerraformValue<double>>("length");
        set => SetArgument("length", value);
    }

    /// <summary>
    /// The generated bytes presented in base64 string format.
    /// </summary>
    public TerraformValue<string> Base64
        => CreateReference("base64");

    /// <summary>
    /// The generated bytes presented in lowercase hexadecimal string format. The length of the encoded string is exactly twice the `length` parameter.
    /// </summary>
    public TerraformValue<string> Hex
        => CreateReference("hex");

}
