using EmmittJ.Terraform.Sdk;

namespace EmmittJ.Terraform.Sdk.Providers.AzureRM;

/// <summary>
/// Manages a azurerm_voice_services_communications_gateway resource.
/// </summary>
public class AzurermVoiceServicesCommunicationsGateway : TerraformResource
{
    public AzurermVoiceServicesCommunicationsGateway(string name) : base("azurerm_voice_services_communications_gateway", name)
    {
        InitializeOutputs();
    }

    private void InitializeOutputs()
    {
    }

    /// <summary>
    /// The api_bridge attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? ApiBridge
    {
        get => GetProperty<TerraformLiteralProperty<string>>("api_bridge");
        set => this.WithProperty("api_bridge", value);
    }

    /// <summary>
    /// The auto_generated_domain_name_label_scope attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? AutoGeneratedDomainNameLabelScope
    {
        get => GetProperty<TerraformLiteralProperty<string>>("auto_generated_domain_name_label_scope");
        set => this.WithProperty("auto_generated_domain_name_label_scope", value);
    }

    /// <summary>
    /// The codecs attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? Codecs
    {
        get => GetProperty<TerraformLiteralProperty<string>>("codecs");
        set => this.WithProperty("codecs", value);
    }

    /// <summary>
    /// The connectivity attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? Connectivity
    {
        get => GetProperty<TerraformLiteralProperty<string>>("connectivity");
        set => this.WithProperty("connectivity", value);
    }

    /// <summary>
    /// The e911_type attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? E911Type
    {
        get => GetProperty<TerraformLiteralProperty<string>>("e911_type");
        set => this.WithProperty("e911_type", value);
    }

    /// <summary>
    /// The emergency_dial_strings attribute.
    /// </summary>
    public TerraformLiteralProperty<List<string>>? EmergencyDialStrings
    {
        get => GetProperty<TerraformLiteralProperty<List<string>>>("emergency_dial_strings");
        set => this.WithProperty("emergency_dial_strings", value);
    }

    /// <summary>
    /// The id attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? Id
    {
        get => GetProperty<TerraformLiteralProperty<string>>("id");
        set => this.WithProperty("id", value);
    }

    /// <summary>
    /// The location attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? Location
    {
        get => GetProperty<TerraformLiteralProperty<string>>("location");
        set => this.WithProperty("location", value);
    }

    /// <summary>
    /// The microsoft_teams_voicemail_pilot_number attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? MicrosoftTeamsVoicemailPilotNumber
    {
        get => GetProperty<TerraformLiteralProperty<string>>("microsoft_teams_voicemail_pilot_number");
        set => this.WithProperty("microsoft_teams_voicemail_pilot_number", value);
    }

    /// <summary>
    /// The name attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? Name
    {
        get => GetProperty<TerraformLiteralProperty<string>>("name");
        set => this.WithProperty("name", value);
    }

    /// <summary>
    /// The on_prem_mcp_enabled attribute.
    /// </summary>
    public TerraformLiteralProperty<bool>? OnPremMcpEnabled
    {
        get => GetProperty<TerraformLiteralProperty<bool>>("on_prem_mcp_enabled");
        set => this.WithProperty("on_prem_mcp_enabled", value);
    }

    /// <summary>
    /// The platforms attribute.
    /// </summary>
    public TerraformLiteralProperty<List<string>>? Platforms
    {
        get => GetProperty<TerraformLiteralProperty<List<string>>>("platforms");
        set => this.WithProperty("platforms", value);
    }

    /// <summary>
    /// The resource_group_name attribute.
    /// </summary>
    public TerraformLiteralProperty<string>? ResourceGroupName
    {
        get => GetProperty<TerraformLiteralProperty<string>>("resource_group_name");
        set => this.WithProperty("resource_group_name", value);
    }

    /// <summary>
    /// The tags attribute.
    /// </summary>
    public TerraformLiteralProperty<Dictionary<string, string>>? Tags
    {
        get => GetProperty<TerraformLiteralProperty<Dictionary<string, string>>>("tags");
        set => this.WithProperty("tags", value);
    }

}
